-- APP 5
--
-- app data entity
--
INSERT INTO <DB_SCHEMA/>.app_data_entity (id, app_id, json_data) VALUES (5000, <APP_ID/>, '{   "description":"Entity info: Swedish bank using SEPA, IBAN, VPA",
                            "name":"App Bank", 
                            "country_code":"SE", 
                            "bank_id":1234, 
                            "bban_length":16, 
                            "bank_type":"SEPA", 
                            "entity_type":"BANK"}');
--
-- app data entity resource
--
INSERT INTO <DB_SCHEMA/>.app_data_entity_resource (id, app_data_entity_app_id, app_data_entity_id, app_data_id, json_data) VALUES (5000, <APP_ID/>, 5000, 566,   '{ "description":"Accounts"}');
INSERT INTO <DB_SCHEMA/>.app_data_entity_resource (id, app_data_entity_app_id, app_data_entity_id, app_data_id, json_data) VALUES (5001, <APP_ID/>, 5000, 562,   '{ "description":"Payment requests"}');
INSERT INTO <DB_SCHEMA/>.app_data_entity_resource (id, app_data_entity_app_id, app_data_entity_id, app_data_id, json_data) VALUES (5002, <APP_ID/>, 5000, 563,   '{ "description":"Payment request metadata"}');
INSERT INTO <DB_SCHEMA/>.app_data_entity_resource (id, app_data_entity_app_id, app_data_entity_id, app_data_id, json_data) VALUES (5003, <APP_ID/>, 5000, 564,   '{ "description":"Customers"}');
INSERT INTO <DB_SCHEMA/>.app_data_entity_resource (id, app_data_entity_app_id, app_data_entity_id, app_data_id, json_data) VALUES (5004, <APP_ID/>, 5000, 565,   '{ "description":"Merchants"}');
INSERT INTO <DB_SCHEMA/>.app_data_entity_resource (id, app_data_entity_app_id, app_data_entity_id, app_data_id, json_data) VALUES (5005, <APP_ID/>, 5000, 567,   '{ "description":"Transactions"}');
INSERT INTO <DB_SCHEMA/>.app_data_entity_resource (id, app_data_entity_app_id, app_data_entity_id, app_data_id, json_data) VALUES (5006, <APP_ID/>, 5000, 568,   '{ "description":"Transactions"}');
INSERT INTO <DB_SCHEMA/>.app_data_entity_resource (id, app_data_entity_app_id, app_data_entity_id, app_data_id, json_data) VALUES (5007, <APP_ID/>, 5000, 572,   '{ "description":"Owners"}');
INSERT INTO <DB_SCHEMA/>.app_data_entity_resource (id, app_data_entity_app_id, app_data_entity_id, app_data_id, json_data) VALUES (5008, <APP_ID/>, 5000, 573,   '{ "description":"Currencies"}');
--
-- app data resource master
--
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (5000, null, null, <APP_ID/>,  5000, 5000, '{ "title":{"default_text":"Account", "length":null, "type":"LOV", "lov":"COUNTRY"}}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (5001, null, null, <APP_ID/>,  5000, 5000, '{ "bank_account_iban":{"default_text":"Bank account IBAN", "length":null, "type":"TEXT", "lov":null}}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (5002, null, null, <APP_ID/>,  5000, 5000, '{ "bank_account_number":{"default_text":"Bank account number", "length":null, "type":"TEXT", "lov":null}}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (5003, null, null, <APP_ID/>,  5000, 5000, '{ "bank_account_balance":{"default_text":"Bank account balance", "length":null, "type":"TEXT", "lov":null}}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (5004, null, null, <APP_ID/>,  5000, 5000, '{ "bank_account_secret":{"default_text":"Bank account secret", "length":null, "type":"TEXT", "lov":null}}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (5005, null, null, <APP_ID/>,  5000, 5000, '{ "bank_account_vpa":{"default_text":"Bank account VPA", "length":null, "type":"TEXT", "lov":null}}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (5006, null, null, <APP_ID/>,  5000, 5000, '{ "currency":{"default_text":"Currency", "default_value":"€", "length":null, "type":"TEXT", "lov":null}}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (5007, null, null, <APP_ID/>,  5000, 5000, '{ "currency_name":{"default_text":"Currency name", "default_value":"App Euro", "length":null, "type":"TEXT", "lov":null}}');

INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (5008, null, null, <APP_ID/>,  5000, 5002, '{ "merchant_id":     {"default_text":"Merchant ID", "length":null, "type":"TEXT", "lov":""}}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (5009, null, null, <APP_ID/>,  5000, 5002, '{ "merchant_name":   {"default_text":"Merchant name", "length":null, "type":"TEXT", "lov":""}}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (5010, null, null, <APP_ID/>,  5000, 5002, '{ "reference":       {"default_text":"Reference", "length":null, "type":"TEXT", "lov":""}}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (5011, null, null, <APP_ID/>,  5000, 5002, '{ "payeeid":         {"default_text":"Payee ID", "length":null, "type":"TEXT", "lov":""}}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (5012, null, null, <APP_ID/>,  5000, 5002, '{ "payerid":         {"default_text":"Payer ID", "length":null, "type":"TEXT", "lov":""}}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (5013, null, null, <APP_ID/>,  5000, 5002, '{ "currency_code":   {"default_text":"Currency", "length":null, "type":"TEXT", "lov":""}}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (5014, null, null, <APP_ID/>,  5000, 5002, '{ "amount":          {"default_text":"Amount", "length":null, "type":"TEXT", "lov":""}}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (5015, null, null, <APP_ID/>,  5000, 5002, '{ "message":         {"default_text":"Message", "length":null, "type":"TEXT", "lov":""}}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (5016, null, null, <APP_ID/>,  5000, 5002, '{ "timestamp":       {"default_text":"Timestamp", "length":null, "type":"TEXT", "lov":""}}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (5017, null, null, <APP_ID/>,  5000, 5002, '{ "status":          {"default_text":"Status", "length":null, "type":"TEXT", "lov":""}}');

INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (5018, null, null, <APP_ID/>,  5000, 5003, '{ "title":{"default_text": "Enter customer info to create new bank account", "length":null, "type":"TEXT", "lov":null}}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (5019, null, null, <APP_ID/>,  5000, 5003, '{ "customer_type":{"default_text":"Customer type", "length":null, "type":"LOV", "lov":"CUSTOMER_TYPE"}}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (5020, null, null, <APP_ID/>,  5000, 5003, '{ "name":{"default_text":"Name", "length":null, "type":"TEXT", "lov":null}}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (5021, null, null, <APP_ID/>,  5000, 5003, '{ "address":{"default_text":"Address", "length":null, "type":"TEXT", "lov":null}}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (5022, null, null, <APP_ID/>,  5000, 5003, '{ "city":{"default_text":"City", "length":null, "type":"TEXT", "lov":null}}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (5023, null, null, <APP_ID/>,  5000, 5003, '{ "country":{"default_text":"Country", "length":null, "type":"LOV", "lov":"COUNTRY"}}');

INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (5024, null, null, <APP_ID/>,  5000, 5004, '{ "title":               {"default_text":"Merchant", "length":null, "type":"TEXT", "lov":""}}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (5025, null, null, <APP_ID/>,  5000, 5004, '{ "merchant_id":         {"default_text":"Merchant ID", "length":null, "type":"TEXT", "lov":""}}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (5026, null, null, <APP_ID/>,  5000, 5004, '{ "merchant_name":       {"default_text":"Merchant name", "length":null, "type":"TEXT", "lov":""}}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (5027, null, null, <APP_ID/>,  5000, 5004, '{ "merchant_url":        {"default_text":"Merchant url", "length":null, "type":"TEXT", "lov":""}}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (5028, null, null, <APP_ID/>,  5000, 5004, '{ "merchant_email":      {"default_text":"Merchant email", "length":null, "type":"TEXT", "lov":""}}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (5029, null, null, <APP_ID/>,  5000, 5004, '{ "merchant_longitude":  {"default_text":"Merchant longitude", "length":null, "type":"TEXT", "lov":""}}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (5030, null, null, <APP_ID/>,  5000, 5004, '{ "merchant_latitude":   {"default_text":"Merchant latitude", "length":null, "type":"TEXT", "lov":""}}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (5031, null, null, <APP_ID/>,  5000, 5004, '{ "merchant_logo":       {"default_text":"Merchant logo", "length":null, "type":"TEXT", "lov":""}}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (5032, null, null, <APP_ID/>,  5000, 5004, '{ "merchant_type":       {"default_text":"Merchant type", "length":null, "type":"LOV", "lov":"MERCHANT_TYPE"}}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (5033, null, null, <APP_ID/>,  5000, 5004, '{ "merchant_api_url_payment_request_create":    {"default_text":"API URL", "length":null, "type":"TEXT", "lov":""}}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (5034, null, null, <APP_ID/>,  5000, 5004, '{ "merchant_api_url_payment_request_get_status":    {"default_text":"API URL", "length":null, "type":"TEXT", "lov":""}}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (5035, null, null, <APP_ID/>,  5000, 5004, '{ "merchant_api_secret": {"default_text":"API Secret", "length":null, "type":"TEXT", "lov":""}}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (5036, null, null, <APP_ID/>,  5000, 5004, '{ "merchant_public_key": {"default_text":"Public key", "length":null, "type":"TEXT", "lov":""}}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (5037, null, null, <APP_ID/>,  5000, 5004, '{ "merchant_private_key":{"default_text":"Private key", "length":null, "type":"TEXT", "lov":""}}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (5038, null, null, <APP_ID/>,  5000, 5004, '{ "merchant_vpa":        {"default_text":"Merchant VPA", "length":null, "type":"TEXT", "lov":""}}');

INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (5039, null, null, <APP_ID/>,  5000, 5006, '{ "title":               {"default_text":"Transaction", "length":null, "type":"TEXT", "lov":""}}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (5040, null, null, <APP_ID/>,  5000, 5006, '{ "timestamp":           {"default_text":"Date", "length":null, "type":"TEXT", "lov":""}}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (5041, null, null, <APP_ID/>,  5000, 5006, '{ "logo":                {"default_text":"", "length":null, "type":"TEXT", "lov":""}}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (5042, null, null, <APP_ID/>,  5000, 5006, '{ "origin":              {"default_text":"Reference", "length":null, "type":"TEXT", "lov":""}}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (5043, null, null, <APP_ID/>,  5000, 5006, '{ "amount_deposit":      {"default_text":"Deposit", "length":null, "type":"TEXT", "lov":""}}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (5044, null, null, <APP_ID/>,  5000, 5006, '{ "amount_withdrawal":   {"default_text":"Withdrawal", "length":null, "type":"TEXT", "lov":""}}');

INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (5045, null, null, <APP_ID/>,  5000, 5007, '{ "title":               {"default_text":"Bank owner", "length":null, "type":"TEXT", "lov":""}}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (5046, null, null, <APP_ID/>,  5000, 5007, '{ "name":                {"default_text":"", "length":null, "type":"TEXT", "lov":""}}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (5047, null, null, <APP_ID/>,  5000, 5007, '{ "address":             {"default_text":"", "length":null, "type":"TEXT", "lov":""}}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (5048, null, null, <APP_ID/>,  5000, 5007, '{ "city":                {"default_text":"", "length":null, "type":"TEXT", "lov":""}}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (5049, null, null, <APP_ID/>,  5000, 5007, '{ "country":             {"default_text":"", "length":null, "type":"LOV", "lov":"COUNTRY"}}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (5050, null, null, <APP_ID/>,  5000, 5007, '{ "amount_initial":      {"default_text":"", "length":null, "type":"TEXT", "lov":""}}');

INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (5051, null, null, <APP_ID/>,  5000, 5008, '{ "currency_code":"APPEUR", "currency_symbol":"€", "currency_name": "App Euro", "conversion_rate":1, "decimal_places":2}');
