const { ConfigMaintenanceGet, ConfigMaintenanceSet, ConfigGet, ConfigSave, DefaultConfig} = require ("./server.controller");
const router = require("express").Router();
const { checkAdmin} = require (global.SERVER_ROOT + "/service/auth/admin/admin.controller");
const { checkDataToken} = require (global.SERVER_ROOT + "/service/auth/auth.controller");
router.put("/config", checkAdmin, ConfigSave);
router.get("/config", checkAdmin, ConfigGet);
router.get("/config/maintenance", checkAdmin, ConfigMaintenanceGet);
router.patch("/config/maintenance", checkAdmin, ConfigMaintenanceSet);
router.post("/config/default", checkDataToken, DefaultConfig);
module.exports = router;