-- COMMON
--
-- app
--
INSERT INTO <DB_SCHEMA/>.app (id) VALUES (<APP_ID/>);

--
--initial data
--
--app data entity
--
INSERT INTO <DB_SCHEMA/>.app_data_entity (id, app_id, json_data) VALUES (6000, <APP_ID/>, '{"description":"Entity info: Shop", "name":"SHOP", entity_type:"SHOP", "store_type":"INTERNET"}');
--
--app data entity resource
--
INSERT INTO <DB_SCHEMA/>.app_data_entity_resource (id, app_data_entity_app_id, app_data_entity_id, app_setting_id, json_data) VALUES (6000, <APP_ID/>, 6000, 622, '{"description":"products"}');
INSERT INTO <DB_SCHEMA/>.app_data_entity_resource (id, app_data_entity_app_id, app_data_entity_id, app_setting_id, json_data) VALUES (6001, <APP_ID/>, 6000, 631, '{"description":"product categories"}');
INSERT INTO <DB_SCHEMA/>.app_data_entity_resource (id, app_data_entity_app_id, app_data_entity_id, app_setting_id, json_data) VALUES (6002, <APP_ID/>, 6000, 632, '{"description":"brands"}');
INSERT INTO <DB_SCHEMA/>.app_data_entity_resource (id, app_data_entity_app_id, app_data_entity_id, app_setting_id, json_data) VALUES (6003, <APP_ID/>, 6000, 633, '{"description":"catalogs"}');
INSERT INTO <DB_SCHEMA/>.app_data_entity_resource (id, app_data_entity_app_id, app_data_entity_id, app_setting_id, json_data) VALUES (6004, <APP_ID/>, 6000, 612, '{"description":"locations"}');
INSERT INTO <DB_SCHEMA/>.app_data_entity_resource (id, app_data_entity_app_id, app_data_entity_id, app_setting_id, json_data) VALUES (6005, <APP_ID/>, 6000, 621, '{"description":"pages"}');
INSERT INTO <DB_SCHEMA/>.app_data_entity_resource (id, app_data_entity_app_id, app_data_entity_id, app_setting_id, json_data) VALUES (6006, <APP_ID/>, 6000, 614, '{"description":"customers"}');
INSERT INTO <DB_SCHEMA/>.app_data_entity_resource (id, app_data_entity_app_id, app_data_entity_id, app_setting_id, json_data) VALUES (6007, <APP_ID/>, 6000, 617, '{"description":"order settings"}');
INSERT INTO <DB_SCHEMA/>.app_data_entity_resource (id, app_data_entity_app_id, app_data_entity_id, app_setting_id, json_data) VALUES (6008, <APP_ID/>, 6000, 619, '{"description":"invoice settings "}');
INSERT INTO <DB_SCHEMA/>.app_data_entity_resource (id, app_data_entity_app_id, app_data_entity_id, app_setting_id, json_data) VALUES (6009, <APP_ID/>, 6000, 615, '{"description":"membercard settings"}');
INSERT INTO <DB_SCHEMA/>.app_data_entity_resource (id, app_data_entity_app_id, app_data_entity_id, app_setting_id, json_data) VALUES (6010, <APP_ID/>, 6000, 624, '{"description":"product variants"}');
INSERT INTO <DB_SCHEMA/>.app_data_entity_resource (id, app_data_entity_app_id, app_data_entity_id, app_setting_id, json_data) VALUES (6011, <APP_ID/>, 6000, 623, '{"description":"product metadata"}');
INSERT INTO <DB_SCHEMA/>.app_data_entity_resource (id, app_data_entity_app_id, app_data_entity_id, app_setting_id, json_data) VALUES (6012, <APP_ID/>, 6000, 625, '{"description":"product variant metadata"}');
INSERT INTO <DB_SCHEMA/>.app_data_entity_resource (id, app_data_entity_app_id, app_data_entity_id, app_setting_id, json_data) VALUES (6013, <APP_ID/>, 6000, 613, '{"description":"location metadata"}');
INSERT INTO <DB_SCHEMA/>.app_data_entity_resource (id, app_data_entity_app_id, app_data_entity_id, app_setting_id, json_data) VALUES (6014, <APP_ID/>, 6000, 626, '{"description":"Product variant location metadata"}');
INSERT INTO <DB_SCHEMA/>.app_data_entity_resource (id, app_data_entity_app_id, app_data_entity_id, app_setting_id, json_data) VALUES (6015, <APP_ID/>, 6000, 627, '{"description":"Payment request"}');
INSERT INTO <DB_SCHEMA/>.app_data_entity_resource (id, app_data_entity_app_id, app_data_entity_id, app_setting_id, json_data) VALUES (6016, <APP_ID/>, 6000, 628, '{"description":"Payment request metadata"}');
INSERT INTO <DB_SCHEMA/>.app_data_entity_resource (id, app_data_entity_app_id, app_data_entity_id, app_setting_id, json_data) VALUES (6017, <APP_ID/>, 6000, 629, '{"description":"Payment metadata"}');
INSERT INTO <DB_SCHEMA/>.app_data_entity_resource (id, app_data_entity_app_id, app_data_entity_id, app_setting_id, json_data) VALUES (6018, <APP_ID/>, 6000, 630, '{"description":"currencies"}');
--
--app data resource master
--

INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (6000, null, null, <APP_ID/>,  6000, 6000, 
            '{  "name":"Product 1", 
                "image":"<svg id=''tshirt'' xmlns=''http://www.w3.org/2000/svg'' viewBox=''0 0 512.005 512.005''>
                            <path d=''M388.416,503.175V150.072c0,0,2.207-62.526,26.483-70.621c0,0,3.681-19.129-79.448-44.138 L308.968,8.83h0.026l-35.681,77.294c-6.806,14.751-27.772,14.751-34.578,0L203.064,8.83l-26.483,26.483 C93.451,60.322,97.133,79.451,97.133,79.451c24.276,8.095,26.483,70.621,26.483,70.621v353.103H388.416z''/>
                            <path d=''M123.613,150.072c0,0-2.198-61.617-26.015-70.391l-0.494-0.23L0,203.037l61.793,44.138l61.82-32.38 V150.072z''/> 
                            <path d=''M388.393,150.072c0,0,2.198-61.617,26.015-70.391l0.494-0.23l97.103,123.586l-61.793,44.138 l-61.82-32.38V150.072z''/> 
                            <path d=''M203.061,8.83l35.672,77.286c6.806,14.751,27.772,14.751,34.578,0L308.966,8.83l-1.871,0.627 c-33.165,11.052-69.014,11.052-102.179-0.009L203.061,8.83z''/>
                         </svg>",
                "description":"T shirt", 
                "attributes":[{"key":"Length", "value":"Normal"}, {"key":"Fit", "value":"Regular fit"}, {"key":"Material", "value":"Cotton"}]}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (6001, null, null, <APP_ID/>,  6000, 6000, '{"name":"Product 2", "image":"", "description":"T shirt", "attributes":[{"key":"Length", "value":"Normal"}, {"key":"Fit", "value":"Regular fit"}, {"key":"Material", "value":"Cotton"}]}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (6002, null, null, <APP_ID/>,  6000, 6000, '{"name":"Product 3", "image":"", "description":"T shirt", "attributes":[{"key":"Length", "value":"Normal"}, {"key":"Fit", "value":"Regular fit"}, {"key":"Material", "value":"Cotton"}]}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (6003, null, null, <APP_ID/>,  6000, 6000, '{"name":"Product 4", "image":"", "description":"T shirt", "attributes":[{"key":"Length", "value":"Normal"}, {"key":"Fit", "value":"Regular fit"}, {"key":"Material", "value":"Cotton"}]}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (6004, null, null, <APP_ID/>,  6000, 6000, '{"name":"Product 5", "image":"", "description":"T shirt", "attributes":[{"key":"Length", "value":"Normal"}, {"key":"Fit", "value":"Regular fit"}, {"key":"Material", "value":"Cotton"}]}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (6005, null, null, <APP_ID/>,  6000, 6000, '{"name":"Product 6", "image":"", "description":"T shirt", "attributes":[{"key":"Length", "value":"Normal"}, {"key":"Fit", "value":"Regular fit"}, {"key":"Material", "value":"Cotton"}]}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (6006, null, null, <APP_ID/>,  6000, 6000, '{"name":"Product 7", "image":"", "description":"T shirt", "attributes":[{"key":"Length", "value":"Normal"}, {"key":"Fit", "value":"Regular fit"}, {"key":"Material", "value":"Cotton"}]}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (6007, null, null, <APP_ID/>,  6000, 6000, '{"name":"Product 8", "image":"", "description":"T shirt", "attributes":[{"key":"Length", "value":"Normal"}, {"key":"Fit", "value":"Regular fit"}, {"key":"Material", "value":"Cotton"}]}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (6008, null, null, <APP_ID/>,  6000, 6000, '{"name":"Product 9", "image":"", "description":"T shirt", "attributes":[{"key":"Length", "value":"Normal"}, {"key":"Fit", "value":"Regular fit"}, {"key":"Material", "value":"Cotton"}]}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (6009, null, null, <APP_ID/>,  6000, 6000, '{"name":"Product 10", "image":"","description":"T shirt", "attributes":[{"key":"Length", "value":"Normal"}, {"key":"Fit", "value":"Regular fit"}, {"key":"Material", "value":"Cotton"}]}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (6010, null, null, <APP_ID/>,  6000, 6001, '{"name":"product category 1"}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (6011, null, null, <APP_ID/>,  6000, 6001, '{"name":"product category 2"}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (6012, null, null, <APP_ID/>,  6000, 6001, '{"name":"product category 3"}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (6013, null, null, <APP_ID/>,  6000, 6001, '{"name":"product category 4"}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (6014, null, null, <APP_ID/>,  6000, 6001, '{"name":"product category 5"}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (6015, null, null, <APP_ID/>,  6000, 6001, '{"name":"product category 6"}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (6016, null, null, <APP_ID/>,  6000, 6001, '{"name":"product category 7"}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (6017, null, null, <APP_ID/>,  6000, 6001, '{"name":"product category 8"}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (6018, null, null, <APP_ID/>,  6000, 6001, '{"name":"product category 9"}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (6019, null, null, <APP_ID/>,  6000, 6001, '{"name":"product category 10"}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (6020, null, null, <APP_ID/>,  6000, 6002, '{"name":"Brand 1"}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (6021, null, null, <APP_ID/>,  6000, 6002, '{"name":"Brand 2"}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (6022, null, null, <APP_ID/>,  6000, 6003, '{"name":"Catalog 1"}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (6023, null, null, <APP_ID/>,  6000, 6003, '{"name":"Catalog 2"}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (6024, null, null, <APP_ID/>,  6000, 6004, '{"name":"Warehouse"}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (6025, null, null, <APP_ID/>,  6000, 6004, '{"name":"Internet"}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (6026, null, null, <APP_ID/>,  6000, 6005, '{"name":"HOME"}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (6027, null, null, <APP_ID/>,  6000, 6005, '{"name":"BRAND"}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (6028, null, null, <APP_ID/>,  6000, 6005, '{"name":"CATEGORY"}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (6029, null, null, <APP_ID/>,  6000, 6005, '{"name":"PRODUCT"}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (6030, null, null, <APP_ID/>,  6000, 6005, '{"name":"SEARCH"}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (6031, null, null, <APP_ID/>,  6000, 6005, '{"name":"CART"}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (6032, null, null, <APP_ID/>,  6000, 6005, '{"name":"CHECKOUT"}');

INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (6033, null, null, <APP_ID/>,  6000, 6006, '{ "title":{"default_text": "Customer", "length":null, "type":"TEXT", "lov":null}}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (6034, null, null, <APP_ID/>,  6000, 6006, '{ "customer_type":{"default_text":"Customer type", "length":null, "type":"LOV", "lov":"CUSTOMER_TYPE"}}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (6035, null, null, <APP_ID/>,  6000, 6006, '{ "name":{"default_text":"Name", "length":null, "type":"TEXT", "lov":null}}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (6036, null, null, <APP_ID/>,  6000, 6006, '{ "address":{"default_text":"Address", "length":null, "type":"TEXT", "lov":null}}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (6037, null, null, <APP_ID/>,  6000, 6006, '{ "city":{"default_text":"City", "length":null, "type":"TEXT", "lov":null}}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (6038, null, null, <APP_ID/>,  6000, 6006, '{ "country":{"default_text":"Country", "length":null, "type":"LOV", "lov":"COUNTRY"}}');

INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (6039, null, null, <APP_ID/>,  6000, 6011, '{ "title":{"default_text": "Product", "length":null, "type":"TEXT", "lov":null}}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (6040, null, null, <APP_ID/>,  6000, 6011, '{ "name":{"default_text": "", "length":null, "type":"TEXT", "lov":null}}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (6041, null, null, <APP_ID/>,  6000, 6011, '{ "image":{"default_text": "", "length":null, "type":"IMAGE", "lov":null}}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (6042, null, null, <APP_ID/>,  6000, 6011, '{ "description":{"default_text": "", "length":null, "type":"TEXT", "lov":null}}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (6043, null, null, <APP_ID/>,  6000, 6011, '{ "attributes":{"default_text": "Attributes", "length":null, "type":"TEXT", "lov":null}}');

INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (6044, null, null, <APP_ID/>,  6000, 6012, '{ "sku":{"default_text": "SKU", "length":null, "type":"TEXT", "lov":null}}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (6045, null, null, <APP_ID/>,  6000, 6012, '{ "name":{"default_text": "Name", "length":null, "type":"TEXT", "lov":null}}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (6046, null, null, <APP_ID/>,  6000, 6012, '{ "product_color":{"default_text": "Color code", "length":null, "type":"COLOR", "lov":null}}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (6047, null, null, <APP_ID/>,  6000, 6012, '{ "product_size":{"default_text": "Size", "length":null, "type":"TEXT", "lov":null}}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (6048, null, null, <APP_ID/>,  6000, 6012, '{ "price":{"default_text": "Price", "length":null, "type":"TEXT", "lov":null}}');

INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (6049, null, null, <APP_ID/>,  6000, 6013, '{ "name":{"default_text": "Name", "length":null, "type":"TEXT", "lov":null}}');

INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (6050, null, null, <APP_ID/>,  6000, 6014, '{ "stock":{"default_text": "Stock", "length":null, "type":"TEXT", "lov":null}}');

INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (6051, null, null, <APP_ID/>,  6000, 6016, '{ "api_secret":{"default_text": "API secret", "length":null, "type":"TEXT", "lov":null}}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (6052, null, null, <APP_ID/>,  6000, 6016, '{ "reference":{"default_text": "Reference", "length":null, "type":"TEXT", "lov":null}}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (6053, null, null, <APP_ID/>,  6000, 6016, '{ "payeeid":{"default_text": "Payee ID", "length":null, "type":"TEXT", "lov":null}}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (6054, null, null, <APP_ID/>,  6000, 6016, '{ "payerid":{"default_text": "Payer ID", "length":null, "type":"TEXT", "lov":null}}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (6055, null, null, <APP_ID/>,  6000, 6016, '{ "currency_code":{"default_text": "Currency", "length":null, "type":"TEXT", "lov":null}}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (6056, null, null, <APP_ID/>,  6000, 6016, '{ "amount":{"default_text": "Amount", "length":null, "type":"TEXT", "lov":null}}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (6057, null, null, <APP_ID/>,  6000, 6016, '{ "message":{"default_text":"Message", "length":null, "type":"TEXT", "lov":null}}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (6058, null, null, <APP_ID/>,  6000, 6016, '{ "timestamp":{"default_text":"Timestamp", "length":null, "type":"TEXT", "lov":null}}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (6059, null, null, <APP_ID/>,  6000, 6016, '{ "merchant_name":{"default_text":"Merchant", "length":null, "type":"TEXT", "lov":null}}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (6060, null, null, <APP_ID/>,  6000, 6016, '{ "status":{"default_text":"Status", "length":null, "type":"TEXT", "lov":""}}');

INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (6061, null, null, <APP_ID/>,  6000, 6017, '{ "payment_method":{"default_text": "Payment method", "length":null, "type":"LOV", "lov":"PAYMENT_METHOD"}}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (6062, null, null, <APP_ID/>,  6000, 6017, '{ "payment_id":{"default_text": "Payment id (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)", "length":null, "type":"TEXT", "lov":null}}');

INSERT INTO <DB_SCHEMA/>.app_data_resource_master (id, user_account_app_user_account_id, user_account_app_app_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_entity_resource_id, json_data) VALUES (6063, null, null, <APP_ID/>,  6000, 6018, '{ "currency_code":"APPEUR", "currency_symbol":"€", "currency_name": "App Euro", "conversion_rate":1, "decimal_places":2}');


--
--app data resource detail
--
-- product variants using resource PRODUCT_VARIANT
INSERT INTO <DB_SCHEMA/>.app_data_resource_detail (id, app_data_resource_master_id, app_data_entity_resource_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_resource_master_attribute_id, json_data) VALUES ( 6000, 6000, 6010, <APP_ID/>, 6000, null, '{"sku":"PROD1V1BLUELIGHTS", "name":"product 1 variant BLUE LIGHT", "product_color": "rgb(81, 171, 255)", "product_size":"S",  "price":8}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_detail (id, app_data_resource_master_id, app_data_entity_resource_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_resource_master_attribute_id, json_data) VALUES ( 6001, 6000, 6010, <APP_ID/>, 6000, null, '{"sku":"PROD1V1BLUELIGHTM", "name":"product 1 variant BLUE LIGHT", "product_color": "rgb(81, 171, 255)", "product_size":"M",  "price":9}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_detail (id, app_data_resource_master_id, app_data_entity_resource_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_resource_master_attribute_id, json_data) VALUES ( 6002, 6000, 6010, <APP_ID/>, 6000, null, '{"sku":"PROD1V1BLUELIGHTL", "name":"product 1 variant BLUE LIGHT", "product_color": "rgb(81, 171, 255)", "product_size":"L",  "price":10}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_detail (id, app_data_resource_master_id, app_data_entity_resource_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_resource_master_attribute_id, json_data) VALUES ( 6003, 6000, 6010, <APP_ID/>, 6000, null, '{"sku":"PROD1V1BLUELIGHTXL","name":"product 1 variant BLUE LIGHT", "product_color": "rgb(81, 171, 255)", "product_size":"XL", "price":11}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_detail (id, app_data_resource_master_id, app_data_entity_resource_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_resource_master_attribute_id, json_data) VALUES ( 6004, 6000, 6010, <APP_ID/>, 6000, null, '{"sku":"PROD1V1BLUES",      "name":"product 1 variant BLUE",       "product_color": "#006dbf",           "product_size":"S",  "price":8}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_detail (id, app_data_resource_master_id, app_data_entity_resource_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_resource_master_attribute_id, json_data) VALUES ( 6005, 6000, 6010, <APP_ID/>, 6000, null, '{"sku":"PROD1V1BLUEM",      "name":"product 1 variant BLUE",       "product_color": "#006dbf",           "product_size":"M",  "price":9}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_detail (id, app_data_resource_master_id, app_data_entity_resource_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_resource_master_attribute_id, json_data) VALUES ( 6006, 6000, 6010, <APP_ID/>, 6000, null, '{"sku":"PROD1V1BLUEL",      "name":"product 1 variant BLUE",       "product_color": "#006dbf",           "product_size":"L",  "price":10}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_detail (id, app_data_resource_master_id, app_data_entity_resource_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_resource_master_attribute_id, json_data) VALUES ( 6007, 6000, 6010, <APP_ID/>, 6000, null, '{"sku":"PROD1V1BLUEXL",     "name":"product 1 variant BLUE",       "product_color": "#006dbf",           "product_size":"XL", "price":11}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_detail (id, app_data_resource_master_id, app_data_entity_resource_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_resource_master_attribute_id, json_data) VALUES ( 6008, 6000, 6010, <APP_ID/>, 6000, null, '{"sku":"PROD1V1BLUEDARKS",  "name":"product 1 variant BLUE DARK",  "product_color": "#32398D",           "product_size":"S",  "price":8}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_detail (id, app_data_resource_master_id, app_data_entity_resource_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_resource_master_attribute_id, json_data) VALUES ( 6009, 6000, 6010, <APP_ID/>, 6000, null, '{"sku":"PROD1V1BLUEDARKM",  "name":"product 1 variant BLUE DARK",  "product_color": "#32398D",           "product_size":"M",  "price":9}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_detail (id, app_data_resource_master_id, app_data_entity_resource_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_resource_master_attribute_id, json_data) VALUES ( 6010, 6000, 6010, <APP_ID/>, 6000, null, '{"sku":"PROD1V1BLUEDARKL",  "name":"product 1 variant BLUE DARK",  "product_color": "#32398D",           "product_size":"L",  "price":10}');
INSERT INTO <DB_SCHEMA/>.app_data_resource_detail (id, app_data_resource_master_id, app_data_entity_resource_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_resource_master_attribute_id, json_data) VALUES ( 6011, 6000, 6010, <APP_ID/>, 6000, null, '{"sku":"PROD1V1BLUEDARKXL", "name":"product 1 variant BLUE DARK",  "product_color": "#32398D",           "product_size":"XL", "price":11}');
-- product brand using resource BRAND
INSERT INTO <DB_SCHEMA/>.app_data_resource_detail (id, app_data_resource_master_id, app_data_entity_resource_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_resource_master_attribute_id, json_data) VALUES ( 6012, 6004, 6002, <APP_ID/>, 6000, 6020, null);
-- product category using resource PRODUCT_CATEGORY
INSERT INTO <DB_SCHEMA/>.app_data_resource_detail (id, app_data_resource_master_id, app_data_entity_resource_id, app_data_entity_resource_app_data_entity_app_id, app_data_entity_resource_app_data_entity_id, app_data_resource_master_attribute_id, json_data) VALUES ( 6013, 6005, 6001, <APP_ID/>, 6000, 6010, null);
--
--app data resource detail data
--
--insert LOCATION info warehouse
INSERT INTO <DB_SCHEMA/>.app_data_resource_detail_data (json_data, date_created, date_modified, app_data_resource_detail_id, app_data_resource_master_attribute_id) VALUES ('{ "stock":10}',  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 6000, 6024); 
INSERT INTO <DB_SCHEMA/>.app_data_resource_detail_data (json_data, date_created, date_modified, app_data_resource_detail_id, app_data_resource_master_attribute_id) VALUES ('{ "stock":20}',  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 6001, 6024);
INSERT INTO <DB_SCHEMA/>.app_data_resource_detail_data (json_data, date_created, date_modified, app_data_resource_detail_id, app_data_resource_master_attribute_id) VALUES ('{ "stock":30}',  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 6002, 6024);
INSERT INTO <DB_SCHEMA/>.app_data_resource_detail_data (json_data, date_created, date_modified, app_data_resource_detail_id, app_data_resource_master_attribute_id) VALUES ('{ "stock":40}',  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 6003, 6024);
INSERT INTO <DB_SCHEMA/>.app_data_resource_detail_data (json_data, date_created, date_modified, app_data_resource_detail_id, app_data_resource_master_attribute_id) VALUES ('{ "stock":50}',  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 6004, 6024); 
INSERT INTO <DB_SCHEMA/>.app_data_resource_detail_data (json_data, date_created, date_modified, app_data_resource_detail_id, app_data_resource_master_attribute_id) VALUES ('{ "stock":60}',  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 6005, 6024);
INSERT INTO <DB_SCHEMA/>.app_data_resource_detail_data (json_data, date_created, date_modified, app_data_resource_detail_id, app_data_resource_master_attribute_id) VALUES ('{ "stock":70}',  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 6006, 6024);
INSERT INTO <DB_SCHEMA/>.app_data_resource_detail_data (json_data, date_created, date_modified, app_data_resource_detail_id, app_data_resource_master_attribute_id) VALUES ('{ "stock":80}',  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 6007, 6024);
INSERT INTO <DB_SCHEMA/>.app_data_resource_detail_data (json_data, date_created, date_modified, app_data_resource_detail_id, app_data_resource_master_attribute_id) VALUES ('{ "stock":90}',  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 6008, 6024); 
INSERT INTO <DB_SCHEMA/>.app_data_resource_detail_data (json_data, date_created, date_modified, app_data_resource_detail_id, app_data_resource_master_attribute_id) VALUES ('{ "stock":100}',  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 6009, 6024);
INSERT INTO <DB_SCHEMA/>.app_data_resource_detail_data (json_data, date_created, date_modified, app_data_resource_detail_id, app_data_resource_master_attribute_id) VALUES ('{ "stock":110}',  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 6010, 6024);
INSERT INTO <DB_SCHEMA/>.app_data_resource_detail_data (json_data, date_created, date_modified, app_data_resource_detail_id, app_data_resource_master_attribute_id) VALUES ('{ "stock":120}',  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 6011, 6024);