const { getPlace, getPlaceAdmin, getIp, getIpAdmin, getTimezone, getTimezoneAdmin} = require ("./geolocation.controller");
const router = require("express").Router();
const { checkAdmin} = require ("../auth/admin/admin.controller");
const { checkDataToken } = require("../auth/auth.controller");
router.get("/getplace", checkDataToken, getPlace);
router.get("/getplace/admin", checkAdmin, getPlaceAdmin);
router.get("/getip", checkDataToken, getIp);
router.get("/getip/admin", checkAdmin, getIpAdmin);
router.get("/getTimezone", checkDataToken, getTimezone);
router.get("/getTimezone/admin", checkAdmin, getTimezoneAdmin);
module.exports = router;