--
-- app_translation category
--
INSERT INTO <DB_SCHEMA/>.app_translation(app_category_id, language_id, text) VALUES(1, 147, 'Business');
INSERT INTO <DB_SCHEMA/>.app_translation(app_category_id, language_id, text) VALUES(2, 147, 'Communications');
INSERT INTO <DB_SCHEMA/>.app_translation(app_category_id, language_id, text) VALUES(3, 147, 'Education');
INSERT INTO <DB_SCHEMA/>.app_translation(app_category_id, language_id, text) VALUES(4, 147, 'Finance');
INSERT INTO <DB_SCHEMA/>.app_translation(app_category_id, language_id, text) VALUES(5, 147, 'House & Home');
INSERT INTO <DB_SCHEMA/>.app_translation(app_category_id, language_id, text) VALUES(6, 147, 'Productivity');
INSERT INTO <DB_SCHEMA/>.app_translation(app_category_id, language_id, text) VALUES(7, 147, 'Shopping');
INSERT INTO <DB_SCHEMA/>.app_translation(app_category_id, language_id, text) VALUES(8, 147, 'Game');
--
-- app_translation country
--
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (251,147,'Afghanistan');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (252,147,'Åland Islands');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (253,147,'Albania');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (254,147,'Algeria');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (255,147,'American Samoa');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (256,147,'Andorra');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (257,147,'Angola');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (258,147,'Anguilla');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (259,147,'Antarctica');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (260,147,'Antigua & Barbuda');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (261,147,'Argentina');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (262,147,'Armenia');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (263,147,'Aruba');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (264,147,'Australia');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (265,147,'Austria');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (266,147,'Azerbaijan');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (267,147,'Bahamas');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (268,147,'Bahrain');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (269,147,'Bangladesh');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (270,147,'Barbados');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (271,147,'Belarus');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (272,147,'Belgium');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (273,147,'Belize');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (274,147,'Benin');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (275,147,'Bermuda');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (276,147,'Bhutan');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (277,147,'Bolivia');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (278,147,'Bosnia & Herzegovina');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (279,147,'Botswana');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (280,147,'Bouvet Island');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (281,147,'Brazil');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (282,147,'British Indian Ocean Territory');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (283,147,'British Virgin Islands');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (284,147,'Brunei');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (285,147,'Bulgaria');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (286,147,'Burkina Faso');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (287,147,'Burundi');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (288,147,'Cambodia');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (289,147,'Cameroon');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (290,147,'Canada');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (291,147,'Cape Verde');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (292,147,'Caribbean Netherlands');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (293,147,'Cayman Islands');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (294,147,'Central African Republic');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (295,147,'Chad');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (296,147,'Chile');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (297,147,'China');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (298,147,'Christmas Island');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (299,147,'Cocos (Keeling) Islands');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (300,147,'Colombia');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (301,147,'Comoros');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (302,147,'Congo - Brazzaville');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (303,147,'Congo - Kinshasa');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (304,147,'Cook Islands');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (305,147,'Costa Rica');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (306,147,'Côte d’Ivoire');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (307,147,'Croatia');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (308,147,'Cuba');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (309,147,'Curaçao');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (310,147,'Cyprus');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (311,147,'Czechia');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (312,147,'Denmark');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (313,147,'Djibouti');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (314,147,'Dominica');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (315,147,'Dominican Republic');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (316,147,'Ecuador');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (317,147,'Egypt');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (318,147,'El Salvador');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (319,147,'Equatorial Guinea');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (320,147,'Eritrea');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (321,147,'Estonia');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (322,147,'Eswatini');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (323,147,'Ethiopia');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (324,147,'Falkland Islands');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (325,147,'Faroe Islands');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (326,147,'Fiji');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (327,147,'Finland');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (328,147,'France');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (329,147,'French Guiana');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (330,147,'French Polynesia');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (331,147,'French Southern Territories');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (332,147,'Gabon');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (333,147,'Gambia');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (334,147,'Georgia');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (335,147,'Germany');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (336,147,'Ghana');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (337,147,'Gibraltar');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (338,147,'Greece');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (339,147,'Greenland');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (340,147,'Grenada');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (341,147,'Guadeloupe');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (342,147,'Guam');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (343,147,'Guatemala');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (344,147,'Guernsey');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (345,147,'Guinea');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (346,147,'Guinea-Bissau');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (347,147,'Guyana');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (348,147,'Haiti');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (349,147,'Heard & McDonald Islands Islands');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (350,147,'Honduras');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (351,147,'Hong Kong SAR China');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (352,147,'Hungary');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (353,147,'Iceland');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (354,147,'India');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (355,147,'Indonesia');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (356,147,'Iran');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (357,147,'Iraq');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (358,147,'Ireland');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (359,147,'Isle of Man');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (360,147,'Israel');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (361,147,'Italy');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (362,147,'Jamaica');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (363,147,'Japan');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (364,147,'Jersey');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (365,147,'Jordan');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (366,147,'Kazakhstan');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (367,147,'Kenya');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (368,147,'Kiribati');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (369,147,'Kuwait');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (370,147,'Kyrgyzstan');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (371,147,'Laos');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (372,147,'Latvia');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (373,147,'Lebanon');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (374,147,'Lesotho');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (375,147,'Liberia');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (376,147,'Libya');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (377,147,'Liechtenstein');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (378,147,'Lithuania');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (379,147,'Luxembourg');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (380,147,'Macao SAR China');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (381,147,'Madagascar');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (382,147,'Malawi');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (383,147,'Malaysia');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (384,147,'Maldives');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (385,147,'Mali');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (386,147,'Malta');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (387,147,'Marshall Islands');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (388,147,'Martinique');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (389,147,'Mauritania');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (390,147,'Mauritius');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (391,147,'Mayotte');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (392,147,'Mexico');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (393,147,'Micronesia');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (394,147,'Moldova');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (395,147,'Monaco');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (396,147,'Mongolia');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (397,147,'Montenegro');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (398,147,'Montserrat');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (399,147,'Morocco');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (400,147,'Mozambique');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (401,147,'Myanmar (Burma)');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (402,147,'Namibia');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (403,147,'Nauru');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (404,147,'Nepal');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (405,147,'Netherlands');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (406,147,'New Caledonia');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (407,147,'New Zealand');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (408,147,'Nicaragua');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (409,147,'Niger');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (410,147,'Nigeria');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (411,147,'Niue');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (412,147,'Norfolk Island');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (413,147,'North Korea');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (414,147,'North Macedonia');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (415,147,'Northern Mariana Islands');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (416,147,'Norway');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (417,147,'Oman');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (418,147,'Pakistan');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (419,147,'Palau');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (420,147,'Palestinian Territories');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (421,147,'Panama');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (422,147,'Papua New Guinea');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (423,147,'Paraguay');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (424,147,'Peru');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (425,147,'Philippines');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (426,147,'Pitcairn Islands');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (427,147,'Poland');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (428,147,'Portugal');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (429,147,'Puerto Rico');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (430,147,'Qatar');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (431,147,'Réunion');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (432,147,'Romania');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (433,147,'Russia');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (434,147,'Rwanda');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (435,147,'Samoa');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (436,147,'San Marino');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (437,147,'São Tomé & Príncipe');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (438,147,'Saudi Arabia');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (439,147,'Senegal');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (440,147,'Serbia');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (441,147,'Seychelles');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (442,147,'Sierra Leone');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (443,147,'Singapore');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (444,147,'Sint Maarten');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (445,147,'Slovakia');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (446,147,'Slovenia');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (447,147,'Solomon Islands');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (448,147,'Somalia');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (449,147,'South Africa');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (450,147,'South Georgia & South Sandwich Islands Sandwich Islands');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (451,147,'South Korea');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (452,147,'South Sudan');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (453,147,'Spain');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (454,147,'Sri Lanka');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (455,147,'St. Barthélemy');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (456,147,'St. Helena');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (457,147,'St. Kitts & Nevis');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (458,147,'St. Lucia');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (459,147,'St. Martin');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (460,147,'St. Pierre & Miquelon');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (461,147,'St. Vincent & Grenadines');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (462,147,'Sudan');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (463,147,'Suriname');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (464,147,'Svalbard & Jan Mayen Mayen');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (465,147,'Sweden');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (466,147,'Switzerland');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (467,147,'Syria');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (468,147,'Taiwan');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (469,147,'Tajikistan');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (470,147,'Tanzania');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (471,147,'Thailand');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (472,147,'Timor-Leste');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (473,147,'Togo');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (474,147,'Tokelau');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (475,147,'Tonga');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (476,147,'Trinidad & Tobago');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (477,147,'Tunisia');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (478,147,'Turkey');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (479,147,'Turkmenistan');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (480,147,'Turks & Caicos Islands Islands');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (481,147,'Tuvalu');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (482,147,'U.S. Outlying Islands');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (483,147,'U.S. Virgin Islands');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (484,147,'Uganda');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (485,147,'Ukraine');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (486,147,'United Arab Emirates');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (487,147,'United Kingdom');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (488,147,'United States');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (489,147,'Uruguay');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (490,147,'Uzbekistan');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (491,147,'Vanuatu');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (492,147,'Vatican City');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (493,147,'Venezuela');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (494,147,'Vietnam');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (495,147,'Wallis & Futuna');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (496,147,'Western Sahara');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (497,147,'Yemen');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (498,147,'Zambia');
INSERT INTO <DB_SCHEMA/>.app_translation (country_id, language_id, text) VALUES (499,147,'Zimbabwe');
--
-- app_translation language
--
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (1,147,'Abkhazian');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (2,147,'Achinese');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (3,147,'Acoli');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (4,147,'Adangme');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (5,147,'Adyghe');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (6,147,'Afar');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (7,147,'Afrihili');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (8,147,'Afrikaans');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (9,147,'Aghem');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (10,147,'Ainu');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (11,147,'Akan');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (12,147,'Akkadian');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (13,147,'Akoose');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (14,147,'Alabama');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (15,147,'Albanian');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (16,147,'Aleut');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (17,147,'Algerian Arabic');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (18,147,'American English');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (19,147,'American Sign Language');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (20,147,'Amharic');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (21,147,'Ancient Egyptian');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (22,147,'Ancient Greek');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (23,147,'Angika');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (24,147,'Ao Naga');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (25,147,'Arabic');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (26,147,'Aragonese');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (27,147,'Aramaic');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (28,147,'Araona');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (29,147,'Arapaho');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (30,147,'Arawak');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (31,147,'Armenian');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (32,147,'Aromanian');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (33,147,'Arpitan');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (34,147,'Assamese');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (35,147,'Asturian');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (36,147,'Asu');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (37,147,'Atsam');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (38,147,'Australian English');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (39,147,'Austrian German');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (40,147,'Avaric');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (41,147,'Avestan');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (42,147,'Awadhi');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (43,147,'Aymara');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (44,147,'Azerbaijani');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (45,147,'Badaga');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (46,147,'Bafia');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (47,147,'Bafut');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (48,147,'Bakhtiari');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (49,147,'Balinese');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (50,147,'Baluchi');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (51,147,'Bambara');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (52,147,'Bamun');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (53,147,'Banjar');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (54,147,'Basaa');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (55,147,'Bashkir');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (56,147,'Basque');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (57,147,'Batak Toba');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (58,147,'Bavarian');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (59,147,'Beja');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (60,147,'Belarusian');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (61,147,'Bemba');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (62,147,'Bena');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (63,147,'Bengali');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (64,147,'Betawi');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (65,147,'Bhojpuri');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (66,147,'Bikol');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (67,147,'Bini');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (68,147,'Bishnupriya');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (69,147,'Bislama');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (70,147,'Blin');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (71,147,'Blissymbols');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (72,147,'Bodo');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (73,147,'Bosnian');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (74,147,'Brahui');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (75,147,'Braj');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (76,147,'Brazilian Portuguese');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (77,147,'Breton');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (78,147,'British English');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (79,147,'Buginese');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (80,147,'Bulgarian');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (81,147,'Bulu');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (82,147,'Buriat');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (83,147,'Burmese');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (84,147,'Caddo');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (85,147,'Cajun French');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (86,147,'Canadian English');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (87,147,'Canadian French');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (88,147,'Cantonese');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (89,147,'Capiznon');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (90,147,'Carib');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (91,147,'Catalan');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (92,147,'Cayuga');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (93,147,'Cebuano');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (94,147,'Central Atlas Tamazight');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (95,147,'Central Dusun');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (96,147,'Central Kurdish');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (97,147,'Central Yupik');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (98,147,'Chadian Arabic');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (99,147,'Chagatai');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (100,147,'Chamorro');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (101,147,'Chechen');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (102,147,'Cherokee');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (103,147,'Cheyenne');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (104,147,'Chibcha');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (105,147,'Chiga');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (106,147,'Chimborazo Highland Quichua');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (107,147,'Chinese');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (108,147,'Chinook Jargon');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (109,147,'Chipewyan');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (110,147,'Choctaw');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (111,147,'Church Slavic');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (112,147,'Chuukese');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (113,147,'Chuvash');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (114,147,'Classical Newari');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (115,147,'Classical Syriac');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (116,147,'Colognian');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (117,147,'Comorian');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (118,147,'Congo Swahili');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (119,147,'Coptic');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (120,147,'Cornish');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (121,147,'Corsican');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (122,147,'Cree');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (123,147,'Creek');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (124,147,'Crimean Turkish');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (125,147,'Croatian');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (126,147,'Czech');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (127,147,'Dakota');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (128,147,'Danish');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (129,147,'Dargwa');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (130,147,'Dazaga');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (131,147,'Delaware');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (132,147,'Dinka');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (133,147,'Divehi');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (134,147,'Dogri');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (135,147,'Dogrib');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (136,147,'Duala');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (137,147,'Dutch');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (138,147,'Dyula');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (139,147,'Dzongkha');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (140,147,'Eastern Frisian');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (141,147,'Efik');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (142,147,'Egyptian Arabic');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (143,147,'Ekajuk');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (144,147,'Elamite');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (145,147,'Embu');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (146,147,'Emilian');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (147,147,'English');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (148,147,'Erzya');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (149,147,'Esperanto');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (150,147,'Estonian');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (151,147,'European Portuguese');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (152,147,'European Spanish');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (153,147,'Ewe');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (154,147,'Ewondo');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (155,147,'Extremaduran');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (156,147,'Fang');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (157,147,'Fanti');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (158,147,'Faroese');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (159,147,'Fiji Hindi');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (160,147,'Fijian');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (161,147,'Filipino');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (162,147,'Finnish');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (163,147,'Flemish');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (164,147,'Fon');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (165,147,'Frafra');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (166,147,'French');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (167,147,'Friulian');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (168,147,'Fulah');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (169,147,'Ga');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (170,147,'Gagauz');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (171,147,'Galician');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (172,147,'Gan Chinese');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (173,147,'Ganda');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (174,147,'Gayo');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (175,147,'Gbaya');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (176,147,'Geez');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (177,147,'Georgian');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (178,147,'German');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (179,147,'Gheg Albanian');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (180,147,'Ghomala');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (181,147,'Gilaki');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (182,147,'Gilbertese');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (183,147,'Goan Konkani');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (184,147,'Gondi');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (185,147,'Gorontalo');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (186,147,'Gothic');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (187,147,'Grebo');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (188,147,'Greek');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (189,147,'Guarani');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (190,147,'Gujarati');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (191,147,'Gusii');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (192,147,'Gwichʼin');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (193,147,'Haida');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (194,147,'Haitian');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (195,147,'Hakka Chinese');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (196,147,'Hausa');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (197,147,'Hawaiian');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (198,147,'Hebrew');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (199,147,'Herero');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (200,147,'Hiligaynon');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (201,147,'Hindi');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (202,147,'Hiri Motu');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (203,147,'Hittite');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (204,147,'Hmong');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (205,147,'Hungarian');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (206,147,'Hupa');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (207,147,'Iban');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (208,147,'Ibibio');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (209,147,'Icelandic');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (210,147,'Ido');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (211,147,'Igbo');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (212,147,'Iloko');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (213,147,'Inari Sami');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (214,147,'Indonesian');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (215,147,'Ingrian');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (216,147,'Ingush');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (217,147,'Interlingua');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (218,147,'Interlingue');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (219,147,'Inuktitut');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (220,147,'Inupiaq');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (221,147,'Irish');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (222,147,'Italian');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (223,147,'Jamaican Creole English');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (224,147,'Japanese');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (225,147,'Javanese');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (226,147,'Jju');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (227,147,'Jola-Fonyi');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (228,147,'Judeo-Arabic');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (229,147,'Judeo-Persian');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (230,147,'Jutish');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (231,147,'Kabardian');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (232,147,'Kabuverdianu');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (233,147,'Kabyle');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (234,147,'Kachin');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (235,147,'Kaingang');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (236,147,'Kako');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (237,147,'Kalaallisut');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (238,147,'Kalenjin');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (239,147,'Kalmyk');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (240,147,'Kamba');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (241,147,'Kanembu');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (242,147,'Kannada');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (243,147,'Kanuri');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (244,147,'Kara-Kalpak');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (245,147,'Karachay-Balkar');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (246,147,'Karelian');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (247,147,'Kashmiri');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (248,147,'Kashubian');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (249,147,'Kawi');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (250,147,'Kazakh');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (251,147,'Kenyang');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (252,147,'Khasi');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (253,147,'Khmer');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (254,147,'Khotanese');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (255,147,'Khowar');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (256,147,'Kikuyu');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (257,147,'Kimbundu');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (258,147,'Kinaray-a');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (259,147,'Kinyarwanda');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (260,147,'Kirmanjki');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (261,147,'Klingon');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (262,147,'Kom');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (263,147,'Komi');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (264,147,'Komi-Permyak');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (265,147,'Kongo');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (266,147,'Konkani');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (267,147,'Korean');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (268,147,'Koro');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (269,147,'Kosraean');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (270,147,'Kotava');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (271,147,'Koyra Chiini');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (272,147,'Koyraboro Senni');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (273,147,'Kpelle');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (274,147,'Krio');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (275,147,'Kuanyama');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (276,147,'Kumyk');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (277,147,'Kurdish');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (278,147,'Kurukh');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (279,147,'Kutenai');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (280,147,'Kwasio');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (281,147,'Kyrgyz');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (282,147,'Kʼicheʼ');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (283,147,'Ladino');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (284,147,'Lahnda');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (285,147,'Lakota');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (286,147,'Lamba');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (287,147,'Langi');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (288,147,'Lao');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (289,147,'Latgalian');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (290,147,'Latin');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (291,147,'Latin American Spanish');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (292,147,'Latvian');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (293,147,'Laz');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (294,147,'Lezghian');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (295,147,'Ligurian');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (296,147,'Limburgish');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (297,147,'Lingala');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (298,147,'Lingua Franca Nova');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (299,147,'Literary Chinese');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (300,147,'Lithuanian');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (301,147,'Livonian');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (302,147,'Lojban');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (303,147,'Lombard');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (304,147,'Low German');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (305,147,'Lower Silesian');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (306,147,'Lower Sorbian');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (307,147,'Lozi');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (308,147,'Luba-Katanga');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (309,147,'Luba-Lulua');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (310,147,'Luiseno');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (311,147,'Lule Sami');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (312,147,'Lunda');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (313,147,'Luo');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (314,147,'Luxembourgish');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (315,147,'Luyia');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (316,147,'Maba');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (317,147,'Macedonian');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (318,147,'Machame');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (319,147,'Madurese');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (320,147,'Mafa');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (321,147,'Magahi');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (322,147,'Main-Franconian');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (323,147,'Maithili');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (324,147,'Makasar');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (325,147,'Makhuwa-Meetto');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (326,147,'Makonde');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (327,147,'Malagasy');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (328,147,'Malay');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (329,147,'Malayalam');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (330,147,'Maltese');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (331,147,'Manchu');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (332,147,'Mandar');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (333,147,'Mandingo');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (334,147,'Manipuri');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (335,147,'Manx');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (336,147,'Maori');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (337,147,'Mapuche');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (338,147,'Marathi');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (339,147,'Mari');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (340,147,'Marshallese');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (341,147,'Marwari');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (342,147,'Masai');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (343,147,'Mazanderani');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (344,147,'Medumba');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (345,147,'Mende');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (346,147,'Mentawai');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (347,147,'Meru');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (348,147,'Metaʼ');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (349,147,'Mexican Spanish');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (350,147,'Micmac');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (351,147,'Middle Dutch');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (352,147,'Middle English');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (353,147,'Middle French');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (354,147,'Middle High German');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (355,147,'Middle Irish');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (356,147,'Min Nan Chinese');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (357,147,'Minangkabau');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (358,147,'Mingrelian');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (359,147,'Mirandese');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (360,147,'Mizo');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (361,147,'Modern Standard Arabic');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (362,147,'Mohawk');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (363,147,'Moksha');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (364,147,'Moldavian');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (365,147,'Mongo');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (366,147,'Mongolian');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (367,147,'Morisyen');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (368,147,'Moroccan Arabic');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (369,147,'Mossi');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (370,147,'Multiple Languages');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (371,147,'Mundang');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (372,147,'Muslim Tat');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (373,147,'Myene');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (374,147,'Nama');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (375,147,'Nauru');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (376,147,'Navajo');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (377,147,'Ndonga');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (378,147,'Neapolitan');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (379,147,'Nepali');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (380,147,'Newari');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (381,147,'Ngambay');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (382,147,'Ngiemboon');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (383,147,'Ngomba');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (384,147,'Nheengatu');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (385,147,'Nias');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (386,147,'Niuean');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (387,147,'No linguistic content');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (388,147,'Nogai');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (389,147,'North Ndebele');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (390,147,'Northern Frisian');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (391,147,'Northern Sami');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (392,147,'Northern Sotho');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (393,147,'Norwegian');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (394,147,'Norwegian Bokmål');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (395,147,'Norwegian Nynorsk');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (396,147,'Novial');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (397,147,'Nuer');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (398,147,'Nyamwezi');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (399,147,'Nyanja');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (400,147,'Nyankole');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (401,147,'Nyasa Tonga');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (402,147,'Nyoro');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (403,147,'Nzima');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (404,147,'NʼKo');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (405,147,'Occitan');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (406,147,'Ojibwa');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (407,147,'Old English');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (408,147,'Old French');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (409,147,'Old High German');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (410,147,'Old Irish');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (411,147,'Old Norse');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (412,147,'Old Persian');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (413,147,'Old Provençal');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (414,147,'Oriya');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (415,147,'Oromo');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (416,147,'Osage');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (417,147,'Ossetic');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (418,147,'Ottoman Turkish');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (419,147,'Pahlavi');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (420,147,'Palatine German');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (421,147,'Palauan');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (422,147,'Pali');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (423,147,'Pampanga');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (424,147,'Pangasinan');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (425,147,'Papiamento');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (426,147,'Pashto');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (427,147,'Pennsylvania German');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (428,147,'Persian');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (429,147,'Phoenician');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (430,147,'Picard');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (431,147,'Piedmontese');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (432,147,'Plautdietsch');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (433,147,'Pohnpeian');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (434,147,'Polish');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (435,147,'Pontic');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (436,147,'Portuguese');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (437,147,'Prussian');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (438,147,'Punjabi');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (439,147,'Quechua');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (440,147,'Rajasthani');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (441,147,'Rapanui');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (442,147,'Rarotongan');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (443,147,'Riffian');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (444,147,'Romagnol');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (445,147,'Romanian');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (446,147,'Romansh');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (447,147,'Romany');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (448,147,'Rombo');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (449,147,'Root');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (450,147,'Rotuman');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (451,147,'Roviana');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (452,147,'Rundi');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (453,147,'Russian');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (454,147,'Rusyn');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (455,147,'Rwa');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (456,147,'Saho');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (457,147,'Sakha');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (458,147,'Samaritan Aramaic');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (459,147,'Samburu');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (460,147,'Samoan');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (461,147,'Samogitian');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (462,147,'Sandawe');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (463,147,'Sango');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (464,147,'Sangu');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (465,147,'Sanskrit');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (466,147,'Santali');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (467,147,'Sardinian');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (468,147,'Sasak');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (469,147,'Sassarese Sardinian');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (470,147,'Saterland Frisian');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (471,147,'Saurashtra');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (472,147,'Scots');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (473,147,'Scottish Gaelic');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (474,147,'Selayar');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (475,147,'Selkup');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (476,147,'Sena');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (477,147,'Seneca');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (478,147,'Serbian');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (479,147,'Serbo-Croatian');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (480,147,'Serer');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (481,147,'Seri');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (482,147,'Shambala');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (483,147,'Shan');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (484,147,'Shona');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (485,147,'Sichuan Yi');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (486,147,'Sicilian');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (487,147,'Sidamo');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (488,147,'Siksika');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (489,147,'Silesian');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (490,147,'Chinese Simplified');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (491,147,'Sindhi');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (492,147,'Sinhala');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (493,147,'Skolt Sami');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (494,147,'Slave');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (495,147,'Slovak');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (496,147,'Slovenian');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (497,147,'Soga');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (498,147,'Sogdien');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (499,147,'Somali');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (500,147,'Soninke');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (501,147,'South Azerbaijani');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (502,147,'South Ndebele');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (503,147,'Southern Altai');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (504,147,'Southern Sami');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (505,147,'Southern Sotho');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (506,147,'Spanish');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (507,147,'Sranan Tongo');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (508,147,'Standard Moroccan Tamazight');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (509,147,'Sukuma');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (510,147,'Sumerian');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (511,147,'Sundanese');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (512,147,'Susu');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (513,147,'Swahili');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (514,147,'Swati');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (515,147,'Swedish');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (516,147,'Swiss French');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (517,147,'Swiss German');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (518,147,'Swiss High German');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (519,147,'Syriac');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (520,147,'Tachelhit');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (521,147,'Tagalog');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (522,147,'Tahitian');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (523,147,'Taita');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (524,147,'Tajik');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (525,147,'Talysh');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (526,147,'Tamashek');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (527,147,'Tamil');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (528,147,'Taroko');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (529,147,'Tasawaq');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (530,147,'Tatar');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (531,147,'Telugu');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (532,147,'Tereno');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (533,147,'Teso');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (534,147,'Tetum');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (535,147,'Thai');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (536,147,'Tibetan');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (537,147,'Tigre');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (538,147,'Tigrinya');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (539,147,'Timne');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (540,147,'Tiv');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (541,147,'Tlingit');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (542,147,'Tok Pisin');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (543,147,'Tokelau');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (544,147,'Tongan');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (545,147,'Tornedalen Finnish');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (546,147,'Chinese Traditional');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (547,147,'Tsakhur');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (548,147,'Tsakonian');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (549,147,'Tsimshian');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (550,147,'Tsonga');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (551,147,'Tswana');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (552,147,'Tulu');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (553,147,'Tumbuka');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (554,147,'Tunisian Arabic');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (555,147,'Turkish');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (556,147,'Turkmen');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (557,147,'Turoyo');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (558,147,'Tuvalu');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (559,147,'Tuvinian');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (560,147,'Twi');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (561,147,'Tyap');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (562,147,'Udmurt');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (563,147,'Ugaritic');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (564,147,'Ukrainian');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (565,147,'Umbundu');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (566,147,'Unknown Language');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (567,147,'Upper Sorbian');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (568,147,'Urdu');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (569,147,'Uyghur');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (570,147,'Uzbek');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (571,147,'Vai');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (572,147,'Venda');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (573,147,'Venetian');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (574,147,'Veps');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (575,147,'Vietnamese');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (576,147,'Volapük');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (577,147,'Võro');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (578,147,'Votic');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (579,147,'Vunjo');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (580,147,'Walloon');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (581,147,'Walser');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (582,147,'Waray');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (583,147,'Warlpiri');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (584,147,'Washo');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (585,147,'Wayuu');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (586,147,'Welsh');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (587,147,'West Flemish');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (588,147,'Western Frisian');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (589,147,'Western Mari');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (590,147,'Wolaytta');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (591,147,'Wolof');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (592,147,'Wu Chinese');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (593,147,'Xhosa');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (594,147,'Xiang Chinese');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (595,147,'Yangben');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (596,147,'Yao');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (597,147,'Yapese');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (598,147,'Yemba');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (599,147,'Yiddish');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (600,147,'Yoruba');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (601,147,'Zapotec');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (602,147,'Zarma');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (603,147,'Zaza');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (604,147,'Zeelandic');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (605,147,'Zenaga');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (606,147,'Zhuang');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (607,147,'Zoroastrian Dari');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (608,147,'Zulu');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (609,147,'Zuni');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (1024,147,'Azerbaijani (Cyrillic)');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (1025,147,'Azerbaijani (Latin)');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (1026,147,'Bambara (Latin)');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (1027,147,'Bosnian (Cyrillic)');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (1028,147,'Bosnian (Latin)');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (1029,147,'Hausa (Latin)');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (1030,147,'Kashmiri (Arabic)');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (1031,147,'Kazakh (Cyrillic)');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (1032,147,'Kyrgyz (Cyrillic)');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (1033,147,'Malay (Latin)');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (1034,147,'Mongolian (Cyrillic)');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (1035,147,'Punjabi (Arabic)');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (1036,147,'Punjabi (Gurmukhi)');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (1037,147,'Serbian (Cyrillic)');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (1038,147,'Serbian (Latin)');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (1039,147,'Uyghur (Arabic)');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (1040,147,'Uzbek (Arabic)');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (1041,147,'Uzbek (Cyrillic)');
INSERT INTO <DB_SCHEMA/>.app_translation (language_id, language_id_translation, text) VALUES (1042,147,'Uzbek (Latin)');