--
-- app_category_translation
--
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(1, 506, 'Negocio');
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(2, 506, 'Comunicaciones');
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(3, 506, 'Educación');
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(4, 506, 'Finanzas');
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(5, 506, 'Casa & home');
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(6, 506, 'Productividad');
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(7, 506, 'Compras');
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(8, 506, 'Juego');
--
-- app_object_item_translation
--
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'DIALOGUE','USERNAME',506,'Nombre de ususario');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'DIALOGUE','PASSWORD',506,'Contraseña');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'DIALOGUE','EMAIL',506,'Correo electrónico');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'DIALOGUE','NEW_EMAIL',506,'Nuevo correo electrónico');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'DIALOGUE','BIO',506,'Bio');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'DIALOGUE','PASSWORD_CONFIRM',506,'Confirmar contraseña');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'DIALOGUE','PASSWORD_REMINDER',506,'Contraseña recordar');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'DIALOGUE','NEW_PASSWORD_CONFIRM',506,'Nueva contraseña confirmar');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'DIALOGUE','NEW_PASSWORD',506,'Nueva contraseña');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'DIALOGUE','CONFIRM_QUESTION',506,'Estás seguro?');

INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_ASR',506,'Media tarde');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_ASR_IQAMAT',506,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_CALTYPE_GREGORIAN',506,'Gregoriano');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_CALTYPE_HIJRI',506,'Hijri');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_DAY',506,'Día');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_DHUHR',506,'Mediodía');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_DHUHR_IQAMAT',506,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_FAJR',506,'Alba');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_FAJR_IQAMAT',506,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_IMSAK',506,'Imsak');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_ISHA',506,'Noche');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_ISHA_IQAMAT',506,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_MAGHRIB',506,'Ocaso');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_MAGHRIB_IQAMAT',506,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_MIDNIGHT',506,'Media noche');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_NOTES',506,'Notas');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_SUNRISE',506,'Salida de sol');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_SUNSET',506,'Ocaso');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_ASR',506,'Asr');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_ASR_IQAMAT',506,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_DHUHR',506,'Dhuhr');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_DHUHR_IQAMAT',506,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_FAJR',506,'Fajr');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_FAJR_IQAMAT',506,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_IMSAK',506,'Imsak');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_ISHA',506,'Isha');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_ISHA_IQAMAT',506,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_MAGHRIB',506,'Maghrib');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_MAGHRIB_IQAMAT',506,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_MIDNIGHT',506,'Midnight');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_SUNRISE',506,'Shorook');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_SUNSET',506,'Sunset');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_WEEKDAY',506,'Día de semana');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','TIMETABLE_TITLE',506,'Horario');
--
-- app_object_subitem_translation
--
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_ASR','SETTING_SELECT_ASR_0',506,'Estándard');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_ASR','SETTING_SELECT_ASR_1',506,'Hanafi');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_REGIONAL','SETTING_SELECT_CALENDARTYPE','SETTING_SELECT_CALENDARTYPE_0',506,'Gregoriano');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_REGIONAL','SETTING_SELECT_CALENDARTYPE','SETTING_SELECT_CALENDARTYPE_1',506,'Hijri');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_HIGHLATITUDE','SETTING_SELECT_HIGHLATITUDE_0',506,'Media noche');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_HIGHLATITUDE','SETTING_SELECT_HIGHLATITUDE_1',506,'Ángulo/60˚ de la noche (recomendado)');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_HIGHLATITUDE','SETTING_SELECT_HIGHLATITUDE_2',506,'1/7th de la noche');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_HIGHLATITUDE','SETTING_SELECT_HIGHLATITUDE_3',506,'Sin ajustes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_REGIONAL','SETTING_SELECT_REPORT_COLTITLE','SETTING_SELECT_REPORT_COLTITLE_0',506,'Transliteración');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_REGIONAL','SETTING_SELECT_REPORT_COLTITLE','SETTING_SELECT_REPORT_COLTITLE_1',506,'Transliteración, traducción');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_REGIONAL','SETTING_SELECT_REPORT_COLTITLE','SETTING_SELECT_REPORT_COLTITLE_2',506,'Traducción, transliteración');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_REGIONAL','SETTING_SELECT_REPORT_COLTITLE','SETTING_SELECT_REPORT_COLTITLE_3',506,'Traducción');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_REGIONAL','SETTING_SELECT_REPORT_DIRECTION','SETTING_SELECT_REPORT_DIRECTION_0',506,'Izquierda a derecha');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_REGIONAL','SETTING_SELECT_REPORT_DIRECTION','SETTING_SELECT_REPORT_DIRECTION_1',506,'Derecha a izquierda');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_DESIGN','SETTING_SELECT_REPORT_HIGHLIGHT_ROW','SETTING_SELECT_REPORT_HIGHLIGHT_ROW_0',506,'Ninguna');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_DESIGN','SETTING_SELECT_REPORT_HIGHLIGHT_ROW','SETTING_SELECT_REPORT_HIGHLIGHT_ROW_1',506,'Viernes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_DESIGN','SETTING_SELECT_REPORT_HIGHLIGHT_ROW','SETTING_SELECT_REPORT_HIGHLIGHT_ROW_2',506,'Sábado');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_DESIGN','SETTING_SELECT_REPORT_HIGHLIGHT_ROW','SETTING_SELECT_REPORT_HIGHLIGHT_ROW_3',506,'Domingo');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_DESIGN','SETTING_SELECT_REPORT_HIGHLIGHT_ROW','SETTING_SELECT_REPORT_HIGHLIGHT_ROW_4',506,'Grupos de 10 días');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_0',506,'Ninguna');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_1',506,'10 minutos');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_2',506,'15 minutos');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_3',506,'20 minutos');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_4',506,'25 minutos');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_5',506,'30 minutos');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_6',506,'Next hour');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_7',506,'Siguiente hora + 15 minutos');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_8',506,'Siguiente hora + 30 minutos');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_0',506,'Ninguna');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_1',506,'10 minutos');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_2',506,'15 minutos');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_3',506,'20 minutos');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_4',506,'25 minutos');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_5',506,'30 minutos');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_6',506,'Siguiente hora');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_7',506,'Siguiente hora + 15 minutos');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_8',506,'Siguiente hora + 30 minutos');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_0',506,'Ninguna');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_1',506,'10 minutos');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_2',506,'15 minutos');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_3',506,'20 minutos');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_4',506,'25 minutos');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_5',506,'30 minutos');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_6',506,'Siguiente hora');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_7',506,'Siguiente hora + 15 minutos');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_8',506,'Siguiente hora + 30 minutos');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_0',506,'Ninguna');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_1',506,'10 minutos');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_2',506,'15 minutos');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_3',506,'20 minutos');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_4',506,'25 minutos');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_5',506,'30 minutos');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_6',506,'Siguiente hora');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_7',506,'Siguiente hora + 15 minutos');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_8',506,'Siguiente hora + 30 minutos');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_0',506,'Ninguna');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_1',506,'10 minutos');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_2',506,'15 minutos');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_3',506,'20 minutos');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_4',506,'25 minutos');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_5',506,'30 minutos');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_6',506,'Siguiente hora');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_7',506,'Siguiente hora + 15 minutos');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_8',506,'Siguiente hora + 30 minutos');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_REGIONAL','SETTING_SELECT_REPORT_LOCALE_SECOND','SETTING_SELECT_REPORT_LOCALE_SECOND_0',506,'Ninguna');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_SHOW_FAST_START_END','SETTING_SELECT_REPORT_SHOW_FAST_START_END_0',506,'No');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_SHOW_FAST_START_END','SETTING_SELECT_REPORT_SHOW_FAST_START_END_1',506,'Fajr & Mahgrib');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_SHOW_FAST_START_END','SETTING_SELECT_REPORT_SHOW_FAST_START_END_2',506,'Imsak & Mahgrib');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_SHOW_FAST_START_END','SETTING_SELECT_REPORT_SHOW_FAST_START_END_3',506,'Fajr & Isha');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_SHOW_FAST_START_END','SETTING_SELECT_REPORT_SHOW_FAST_START_END_4',506,'Imsak & Isha');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_TIMEFORMAT','SETTING_SELECT_TIMEFORMAT_0',506,'12-horas sin sufijo');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_TIMEFORMAT','SETTING_SELECT_TIMEFORMAT_1',506,'24-horas');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_TIMEFORMAT','SETTING_SELECT_TIMEFORMAT_2',506,'12-horas con sufijo');
--
-- app_object_translation
--
INSERT INTO app_portfolio.app_object_translation (app_object_app_id, app_object_object_name, language_id, text) VALUES (2,'APP_DESCRIPTION',506,'Aplicación de una sola página (SPA) de aplicación web progresiva (PWA)');
INSERT INTO app_portfolio.app_object_translation (app_object_app_id, app_object_object_name, language_id, text) VALUES (3,'APP_DESCRIPTION',506,'Aplicación sencilla para mostrar el modelo de datos y cómo integrar una aplicación en la plataforma de la aplicación');
--
-- message_translation
--
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (506,'20100','Nombre de usuario 5 - 100 caracteres');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (506,'20101','Nombre de usuario no válido');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (506,'20102','Bio max 100 caracteres');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (506,'20103','Correo electrónico max 100 caracteres');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (506,'20104','Recordatorio max 100 caracteres');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (506,'20105','Correo electrónico no válido');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (506,'20106','Contraseña 10 - 100 caracteres');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (506,'20107','Se requiere nombre de usuario, contraseña y correo electrónico');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (506,'20200','Correo electrónico ya existe');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (506,'20201','Provider ya existe');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (506,'20203','Usuario ya existe');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (506,'20204','Demasiado largo');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (506,'20300','Usuario o contraseña no encontrado');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (506,'20301','Contraseña no es la misma');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (506,'20302','No puede eliminar la última configuración de usuario');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (506,'20303','Por favor ingrese nombre de usuario');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (506,'20304','Por favor ingrese contraseña');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (506,'20305','Usuario no encontrado');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (506,'20306','Código no válido');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (506,'20307','Tipo de archivo no permitido');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (506,'20308','Tamaño de archivo demasiado grande');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (506,'20309','Texto no válido');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (506,'20310','Texto demasiado largo');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (506,'20400','Registro no encontrado');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (506,'20401','Contraseña inválida');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (506,'20500','Falta latitud or longitud');
--
-- regional_setting_translation
--
INSERT INTO app_portfolio.regional_setting_translation (regional_setting_id, language_id, text) VALUES (490,506,'Gregoriano');
INSERT INTO app_portfolio.regional_setting_translation (regional_setting_id, language_id, text) VALUES (491,506,'Hijri');
INSERT INTO app_portfolio.regional_setting_translation (regional_setting_id, language_id, text) VALUES (481,506,'Transliteración');
INSERT INTO app_portfolio.regional_setting_translation (regional_setting_id, language_id, text) VALUES (482,506,'Transliteración, traducción');
INSERT INTO app_portfolio.regional_setting_translation (regional_setting_id, language_id, text) VALUES (483,506,'Traducción, transliteración');
INSERT INTO app_portfolio.regional_setting_translation (regional_setting_id, language_id, text) VALUES (484,506,'Traducción');
INSERT INTO app_portfolio.regional_setting_translation (regional_setting_id, language_id, text) VALUES (479,506,'Izquierda a derecha');
INSERT INTO app_portfolio.regional_setting_translation (regional_setting_id, language_id, text) VALUES (480,506,'Derecha a izquierda');
