--Oracle, uncomment:
--SET DEFINE OFF;
--
-- app_category_translation
--
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(1, 162, 'Liiketoimintaa');
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(2, 162, 'Viestintä');
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(3, 162, 'Koulutus');
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(4, 162, 'Rahoittaa');
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(5, 162, 'Talo koti');
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(6, 162, 'Tuottavuus');
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(7, 162, 'Ostokset');
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(8, 162, 'Peli');
--
-- app_object_item_translation
--
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'COMMON','USERNAME',162,'Käyttäjätunnus');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'COMMON','PASSWORD',162,'Salasana');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'COMMON','BIO',162,'Bio');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'COMMON','EMAIL',162,'Sähköposti');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'COMMON','NEW_EMAIL',162,'Uusi sähköposti');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'COMMON','PASSWORD_CONFIRM',162,'Vahvista salasana');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'COMMON','PASSWORD_REMINDER',162,'Salasanan muistuttaja');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'COMMON','NEW_PASSWORD_CONFIRM',162,'Vahvista uusi salasana');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'COMMON','NEW_PASSWORD',162,'Uusi salasana');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'COMMON','CONFIRM_QUESTION',162,'Oletko varma?');


INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_ASR',162,'Iltapäivällä');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_ASR_IQAMAT',162,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_CALTYPE_GREGORIAN',162,'Gregoriaaninen');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_CALTYPE_HIJRI',162,'Hijri');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_DAY',162,'Päivä');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_DHUHR',162,'Keskipäivä');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_DHUHR_IQAMAT',162,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_FAJR',162,'Aamunkoitto');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_FAJR_IQAMAT',162,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_IMSAK',162,'Imsak');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_ISHA',162,'Yö');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_ISHA_IQAMAT',162,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_MAGHRIB',162,'Auringonlasku');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_MAGHRIB_IQAMAT',162,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_MIDNIGHT',162,'Keskiyö');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_NOTES',162,'Huomautuksia');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_SUNRISE',162,'Auringonnousu');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_SUNSET',162,'Auringonlasku');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_ASR',162,'Asr');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_ASR_IQAMAT',162,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_DHUHR',162,'Dhuhr');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_DHUHR_IQAMAT',162,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_FAJR',162,'Fajr');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_FAJR_IQAMAT',162,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_IMSAK',162,'Imsak');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_ISHA',162,'Isha');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_ISHA_IQAMAT',162,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_MAGHRIB',162,'Maghrib');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_MAGHRIB_IQAMAT',162,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_MIDNIGHT',162,'Midnight');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_SUNRISE',162,'Shorook');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_SUNSET',162,'Sunset');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_WEEKDAY',162,'Viikonpäivä');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','TIMETABLE_TITLE',162,'Aikataulu');
--
-- app_object_subitem_translation
--
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_ASR','SETTING_SELECT_ASR_0',162,'Vakio');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_ASR','SETTING_SELECT_ASR_1',162,'Hanafi');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_CALENDARTYPE','SETTING_SELECT_CALENDARTYPE_0',162,'Gregoriaaninen');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_CALENDARTYPE','SETTING_SELECT_CALENDARTYPE_1',162,'Hijri');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_HIGHLATITUDE','SETTING_SELECT_HIGHLATITUDE_0',162,'Keskellä yötä');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_HIGHLATITUDE','SETTING_SELECT_HIGHLATITUDE_1',162,'Kulma/60. yö (suositus)');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_HIGHLATITUDE','SETTING_SELECT_HIGHLATITUDE_2',162,'1/7 yöstä');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_HIGHLATITUDE','SETTING_SELECT_HIGHLATITUDE_3',162,'Ei säätöä');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_COLTITLE','SETTING_SELECT_REPORT_COLTITLE_0',162,'Translitterointi');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_COLTITLE','SETTING_SELECT_REPORT_COLTITLE_1',162,'Translitterointi, käännös');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_COLTITLE','SETTING_SELECT_REPORT_COLTITLE_2',162,'Käännös, translitterointi');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_COLTITLE','SETTING_SELECT_REPORT_COLTITLE_3',162,'Käännös');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_DIRECTION','SETTING_SELECT_REPORT_DIRECTION_0',162,'Vasemmalta oikealle');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_DIRECTION','SETTING_SELECT_REPORT_DIRECTION_1',162,'Oikealta vasemmalle');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_HIGHLIGHT_ROW','SETTING_SELECT_REPORT_HIGHLIGHT_ROW_0',162,'Ei mitään');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_HIGHLIGHT_ROW','SETTING_SELECT_REPORT_HIGHLIGHT_ROW_1',162,'Perjantai');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_HIGHLIGHT_ROW','SETTING_SELECT_REPORT_HIGHLIGHT_ROW_2',162,'Lauantai');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_HIGHLIGHT_ROW','SETTING_SELECT_REPORT_HIGHLIGHT_ROW_3',162,'Sunnuntai');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_HIGHLIGHT_ROW','SETTING_SELECT_REPORT_HIGHLIGHT_ROW_4',162,'10 päivän ryhmät');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_0',162,'Ei mitään');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_1',162,'10 minuuttia');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_2',162,'15 minuuttia');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_3',162,'20 minuuttia');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_4',162,'25 minuuttia');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_5',162,'30 minuuttia');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_6',162,'Seuraava tunti');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_7',162,'Seuraava tunti + 15 minuuttia');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_8',162,'Seuraava tunti + 30 minuuttia');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_0',162,'Ei mitään');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_1',162,'10 minuuttia');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_2',162,'15 minuuttia');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_3',162,'20 minuuttia');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_4',162,'25 minuuttia');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_5',162,'30 minuuttia');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_6',162,'Seuraava tunti');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_7',162,'Seuraava tunti + 15 minuuttia');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_8',162,'Seuraava tunti + 30 minuuttia');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_0',162,'Ei mitään');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_1',162,'10 minuuttia');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_2',162,'15 minuuttia');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_3',162,'20 minuuttia');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_4',162,'25 minuuttia');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_5',162,'30 minuuttia');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_6',162,'Seuraava tunti');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_7',162,'Seuraava tunti + 15 minuuttia');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_8',162,'Seuraava tunti + 30 minuuttia');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_0',162,'Ei mitään');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_1',162,'10 minuuttia');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_2',162,'15 minuuttia');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_3',162,'20 minuuttia');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_4',162,'25 minuuttia');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_5',162,'30 minuuttia');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_6',162,'Seuraava tunti');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_7',162,'Seuraava tunti + 15 minuuttia');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_8',162,'Seuraava tunti + 30 minuuttia');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_0',162,'Ei mitään');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_1',162,'10 minuuttia');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_2',162,'15 minuuttia');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_3',162,'20 minuuttia');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_4',162,'25 minuuttia');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_5',162,'30 minuuttia');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_6',162,'Seuraava tunti');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_7',162,'Seuraava tunti + 15 minuuttia');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_8',162,'Seuraava tunti + 30 minuuttia');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_LOCALE_SECOND','SETTING_SELECT_REPORT_LOCALE_SECOND_0',162,'Ei mitään');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_SHOW_FAST_START_END','SETTING_SELECT_REPORT_SHOW_FAST_START_END_0',162,'Ei');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_SHOW_FAST_START_END','SETTING_SELECT_REPORT_SHOW_FAST_START_END_1',162,'Fajr & Mahgrib');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_SHOW_FAST_START_END','SETTING_SELECT_REPORT_SHOW_FAST_START_END_2',162,'Imsak & Mahgrib');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_SHOW_FAST_START_END','SETTING_SELECT_REPORT_SHOW_FAST_START_END_3',162,'Fajr & Isha');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_SHOW_FAST_START_END','SETTING_SELECT_REPORT_SHOW_FAST_START_END_4',162,'Imsak & Isha');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_TIMEFORMAT','SETTING_SELECT_TIMEFORMAT_0',162,'12 tuntia ilman päätettä');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_TIMEFORMAT','SETTING_SELECT_TIMEFORMAT_1',162,'24 tuntia');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_TIMEFORMAT','SETTING_SELECT_TIMEFORMAT_2',162,'12 tuntia jälkiliitteellä');
--
-- app_object_translation
--
INSERT INTO app_portfolio.app_object_translation (app_object_app_id, app_object_object_name, language_id, text) VALUES (2,'APP_DESCRIPTION',162,'Progressiivinen verkkosovellus (PWA) yksisivuinen sovellus (SPA)');
INSERT INTO app_portfolio.app_object_translation (app_object_app_id, app_object_object_name, language_id, text) VALUES (3,'APP_DESCRIPTION',162,'Yksinkertainen sovellus datamallin näyttämiseen ja sovelluksen integrointiin sovellusalustaan');
--
-- message_translation
--
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (162,'20100','Käyttäjätunnus 5 - 100 merkkiä');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (162,'20101','Ei kelvollinen käyttäjätunnus');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (162,'20102','Bio max 100 merkkiä');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (162,'20103','Sähköposti enintään 100 merkkiä');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (162,'20104','Muistutus enintään 100 merkkiä');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (162,'20105','Virheellinen sähköpostiosoite');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (162,'20106','Salasana 10-100 merkkiä');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (162,'20107','Käyttäjätunnus, salasana ja sähköpostiosoite vaaditaan');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (162,'20200','Sähköposti on jo olemassa');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (162,'20201','Palveluntarjoaja on jo olemassa');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (162,'20203','Käyttäjänimi on jo olemassa');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (162,'20204','Liian pitkä arvo');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (162,'20300','Käyttäjätunnusta tai salasanaa ei löydy');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (162,'20301','Salasana ei ole sama');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (162,'20302','Et voi poistaa viimeistä käyttäjän asetusta');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (162,'20303','Anna käyttäjänimi');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (162,'20304','Anna salasana');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (162,'20305','Käyttäjää ei löydy');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (162,'20306','Koodi ei kelpaa');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (162,'20307','Tiedostotyyppiä ei sallita');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (162,'20308','Tiedoston koko on liian suuri');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (162,'20309','Teksti ei kelpaa');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (162,'20310','Teksti liian pitkä');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (162,'20400','Tietuetta ei löydy');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (162,'20401','Väärä salasana');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (162,'20500','Leveys- tai pituusaste puuttuu');
--
-- setting_translation
--
INSERT INTO app_portfolio.setting_translation (setting_id, language_id, text) VALUES (3,162,'Ei mitään');
INSERT INTO app_portfolio.setting_translation (setting_id, language_id, text) VALUES (4,162,'Perjantai');
INSERT INTO app_portfolio.setting_translation (setting_id, language_id, text) VALUES (5,162,'Lauantai');
INSERT INTO app_portfolio.setting_translation (setting_id, language_id, text) VALUES (6,162,'Sunnuntai');
INSERT INTO app_portfolio.setting_translation (setting_id, language_id, text) VALUES (7,162,'10 päivän ryhmät');
INSERT INTO app_portfolio.setting_translation (setting_id, language_id, text) VALUES (26,162,'Vakio');
INSERT INTO app_portfolio.setting_translation (setting_id, language_id, text) VALUES (27,162,'Hanafi');
INSERT INTO app_portfolio.setting_translation (setting_id, language_id, text) VALUES (28,162,'Keskellä yötä');
INSERT INTO app_portfolio.setting_translation (setting_id, language_id, text) VALUES (29,162,'Kulma/60. yö (suositus)');
INSERT INTO app_portfolio.setting_translation (setting_id, language_id, text) VALUES (30,162,'1/7 yöstä');
INSERT INTO app_portfolio.setting_translation (setting_id, language_id, text) VALUES (31,162,'Ei säätöä');
INSERT INTO app_portfolio.setting_translation (setting_id, language_id, text) VALUES (32,162,'12 tuntia ilman päätettä');
INSERT INTO app_portfolio.setting_translation (setting_id, language_id, text) VALUES (33,162,'24 tuntia');
INSERT INTO app_portfolio.setting_translation (setting_id, language_id, text) VALUES (34,162,'12 tuntia jälkiliitteellä');
INSERT INTO app_portfolio.setting_translation (setting_id, language_id, text) VALUES (40,162,'Ei mitään');
INSERT INTO app_portfolio.setting_translation (setting_id, language_id, text) VALUES (41,162,'10 minuuttia');
INSERT INTO app_portfolio.setting_translation (setting_id, language_id, text) VALUES (42,162,'15 minuuttia');
INSERT INTO app_portfolio.setting_translation (setting_id, language_id, text) VALUES (43,162,'20 minuuttia');
INSERT INTO app_portfolio.setting_translation (setting_id, language_id, text) VALUES (44,162,'25 minuuttia');
INSERT INTO app_portfolio.setting_translation (setting_id, language_id, text) VALUES (45,162,'30 minuuttia');
INSERT INTO app_portfolio.setting_translation (setting_id, language_id, text) VALUES (46,162,'Seuraava tunti');
INSERT INTO app_portfolio.setting_translation (setting_id, language_id, text) VALUES (47,162,'Seuraava tunti + 15 minuuttia');
INSERT INTO app_portfolio.setting_translation (setting_id, language_id, text) VALUES (48,162,'Seuraava tunti + 30 minuuttia');
INSERT INTO app_portfolio.setting_translation (setting_id, language_id, text) VALUES (49,162,'Ei');
INSERT INTO app_portfolio.setting_translation (setting_id, language_id, text) VALUES (50,162,'Fajr & Mahgrib');
INSERT INTO app_portfolio.setting_translation (setting_id, language_id, text) VALUES (51,162,'Imsak & Mahgrib');
INSERT INTO app_portfolio.setting_translation (setting_id, language_id, text) VALUES (52,162,'Fajr & Isha');
INSERT INTO app_portfolio.setting_translation (setting_id, language_id, text) VALUES (53,162,'Imsak & Isha');
INSERT INTO app_portfolio.setting_translation (setting_id, language_id, text) VALUES (532,162,'Vasemmalta oikealle');
INSERT INTO app_portfolio.setting_translation (setting_id, language_id, text) VALUES (533,162,'Oikealta vasemmalle');
INSERT INTO app_portfolio.setting_translation (setting_id, language_id, text) VALUES (534,162,'Translitterointi');
INSERT INTO app_portfolio.setting_translation (setting_id, language_id, text) VALUES (535,162,'Translitterointi, käännös');
INSERT INTO app_portfolio.setting_translation (setting_id, language_id, text) VALUES (536,162,'Käännös, translitterointi');
INSERT INTO app_portfolio.setting_translation (setting_id, language_id, text) VALUES (537,162,'Käännös');
INSERT INTO app_portfolio.setting_translation (setting_id, language_id, text) VALUES (543,162,'Gregoriaaninen');
INSERT INTO app_portfolio.setting_translation (setting_id, language_id, text) VALUES (544,162,'Hijri');
