--Oracle, uncomment:
--SET DEFINE OFF;
--
-- app_category_translation
--
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(1, 198, 'Business');
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(2, 198, 'Communications');
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(3, 198, 'Education');
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(4, 198, 'Finance');
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(5, 198, 'House & Home');
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(6, 198, 'Productivity');
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(7, 198, 'Shopping');
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(8, 198, 'Game');
--
-- app_object_item_translation
--
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'DIALOGUE','USERNAME',198,'Username');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'DIALOGUE','PASSWORD',198,'Password');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'DIALOGUE','BIO',198,'Bio');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'DIALOGUE','EMAIL',198,'Email');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'DIALOGUE','NEW_EMAIL',198,'New email');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'DIALOGUE','PASSWORD_CONFIRM',198,'Password confirm');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'DIALOGUE','PASSWORD_REMINDER',198,'Password reminder');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'DIALOGUE','NEW_PASSWORD_CONFIRM',198,'New password confirm');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'DIALOGUE','NEW_PASSWORD',198,'New password');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'DIALOGUE','CONFIRM_QUESTION',198,'Are you sure?');


INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_ASR',198,'Afternoon');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_ASR_IQAMAT',198,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_CALTYPE_GREGORIAN',198,'Gregorian');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_CALTYPE_HIJRI',198,'Hijri');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_DAY',198,'Day');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_DHUHR',198,'Noon');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_DHUHR_IQAMAT',198,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_FAJR',198,'Dawn');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_FAJR_IQAMAT',198,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_IMSAK',198,'Imsak');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_ISHA',198,'Night');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_ISHA_IQAMAT',198,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_MAGHRIB',198,'Sunset');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_MAGHRIB_IQAMAT',198,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_MIDNIGHT',198,'Midnight');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_NOTES',198,'Notes');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_SUNRISE',198,'Sunrise');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_SUNSET',198,'Sunset');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_ASR',198,'Asr');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_ASR_IQAMAT',198,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_DHUHR',198,'Dhuhr');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_DHUHR_IQAMAT',198,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_FAJR',198,'Fajr');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_FAJR_IQAMAT',198,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_IMSAK',198,'Imsak');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_ISHA',198,'Isha');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_ISHA_IQAMAT',198,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_MAGHRIB',198,'Maghrib');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_MAGHRIB_IQAMAT',198,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_MIDNIGHT',198,'Midnight');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_SUNRISE',198,'Shorook');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_SUNSET',198,'Sunset');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_WEEKDAY',198,'Weekday');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','TIMETABLE_TITLE',198,'Timetable');
--
-- app_object_subitem_translation
--
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_ASR','SETTING_SELECT_ASR_0',198,'Standard');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_ASR','SETTING_SELECT_ASR_1',198,'Hanafi');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_REGIONAL','SETTING_SELECT_CALENDARTYPE','SETTING_SELECT_CALENDARTYPE_0',198,'Gregorian');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_REGIONAL','SETTING_SELECT_CALENDARTYPE','SETTING_SELECT_CALENDARTYPE_1',198,'Hijri');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_HIGHLATITUDE','SETTING_SELECT_HIGHLATITUDE_0',198,'Middle of night');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_HIGHLATITUDE','SETTING_SELECT_HIGHLATITUDE_1',198,'Angle/60th of night (recommended)');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_HIGHLATITUDE','SETTING_SELECT_HIGHLATITUDE_2',198,'1/7th of night');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_HIGHLATITUDE','SETTING_SELECT_HIGHLATITUDE_3',198,'No adjustment');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_REGIONAL','SETTING_SELECT_REPORT_COLTITLE','SETTING_SELECT_REPORT_COLTITLE_0',198,'Transliteration');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_REGIONAL','SETTING_SELECT_REPORT_COLTITLE','SETTING_SELECT_REPORT_COLTITLE_1',198,'Transliteration, translation');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_REGIONAL','SETTING_SELECT_REPORT_COLTITLE','SETTING_SELECT_REPORT_COLTITLE_2',198,'Translation, transliteration');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_REGIONAL','SETTING_SELECT_REPORT_COLTITLE','SETTING_SELECT_REPORT_COLTITLE_3',198,'Translation');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_REGIONAL','SETTING_SELECT_REPORT_DIRECTION','SETTING_SELECT_REPORT_DIRECTION_0',198,'Left to right');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_REGIONAL','SETTING_SELECT_REPORT_DIRECTION','SETTING_SELECT_REPORT_DIRECTION_1',198,'Right to left');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_DESIGN','SETTING_SELECT_REPORT_HIGHLIGHT_ROW','SETTING_SELECT_REPORT_HIGHLIGHT_ROW_0',198,'None');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_DESIGN','SETTING_SELECT_REPORT_HIGHLIGHT_ROW','SETTING_SELECT_REPORT_HIGHLIGHT_ROW_1',198,'Friday');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_DESIGN','SETTING_SELECT_REPORT_HIGHLIGHT_ROW','SETTING_SELECT_REPORT_HIGHLIGHT_ROW_2',198,'Saturday');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_DESIGN','SETTING_SELECT_REPORT_HIGHLIGHT_ROW','SETTING_SELECT_REPORT_HIGHLIGHT_ROW_3',198,'Sunday');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_DESIGN','SETTING_SELECT_REPORT_HIGHLIGHT_ROW','SETTING_SELECT_REPORT_HIGHLIGHT_ROW_4',198,'10 days groups');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_0',198,'None');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_1',198,'10 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_2',198,'15 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_3',198,'20 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_4',198,'25 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_5',198,'30 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_6',198,'Next hour');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_7',198,'Next hour + 15 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_8',198,'Next hour + 30 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_0',198,'None');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_1',198,'10 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_2',198,'15 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_3',198,'20 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_4',198,'25 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_5',198,'30 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_6',198,'Next hour');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_7',198,'Next hour + 15 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_8',198,'Next hour + 30 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_0',198,'None');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_1',198,'10 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_2',198,'15 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_3',198,'20 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_4',198,'25 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_5',198,'30 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_6',198,'Next hour');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_7',198,'Next hour + 15 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_8',198,'Next hour + 30 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_0',198,'None');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_1',198,'10 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_2',198,'15 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_3',198,'20 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_4',198,'25 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_5',198,'30 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_6',198,'Next hour');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_7',198,'Next hour + 15 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_8',198,'Next hour + 30 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_0',198,'None');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_1',198,'10 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_2',198,'15 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_3',198,'20 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_4',198,'25 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_5',198,'30 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_6',198,'Next hour');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_7',198,'Next hour + 15 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_8',198,'Next hour + 30 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_REGIONAL','SETTING_SELECT_REPORT_LOCALE_SECOND','SETTING_SELECT_REPORT_LOCALE_SECOND_0',198,'None');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_SHOW_FAST_START_END','SETTING_SELECT_REPORT_SHOW_FAST_START_END_0',198,'No');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_SHOW_FAST_START_END','SETTING_SELECT_REPORT_SHOW_FAST_START_END_1',198,'Fajr & Mahgrib');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_SHOW_FAST_START_END','SETTING_SELECT_REPORT_SHOW_FAST_START_END_2',198,'Imsak & Mahgrib');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_SHOW_FAST_START_END','SETTING_SELECT_REPORT_SHOW_FAST_START_END_3',198,'Fajr & Isha');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_SHOW_FAST_START_END','SETTING_SELECT_REPORT_SHOW_FAST_START_END_4',198,'Imsak & Isha');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_TIMEFORMAT','SETTING_SELECT_TIMEFORMAT_0',198,'12-hour without suffix');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_TIMEFORMAT','SETTING_SELECT_TIMEFORMAT_1',198,'24-hour');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_TIMEFORMAT','SETTING_SELECT_TIMEFORMAT_2',198,'12-hour with suffix');
--
-- app_object_translation
--
INSERT INTO app_portfolio.app_object_translation (app_object_app_id, app_object_object_name, language_id, text) VALUES (2,'APP_DESCRIPTION',198,'Progressive web app (PWA) single page application (SPA)');
INSERT INTO app_portfolio.app_object_translation (app_object_app_id, app_object_object_name, language_id, text) VALUES (3,'APP_DESCRIPTION',198,'Simple app to display datamodel and how to integrate an app in the app platform');
--
-- message_translation
--
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (198,'20100','Username 5 - 100 characters');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (198,'20101','Not valid username');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (198,'20102','Bio max 100 characters');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (198,'20103','Email max 100 characters');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (198,'20104','Reminder max 100 characters');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (198,'20105','Not valid email');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (198,'20106','Password 10 - 100 characters');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (198,'20107','Username, password and email are required');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (198,'20200','Email already exist');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (198,'20201','Provider already exist');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (198,'20203','Username already exist');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (198,'20204','Too long value');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (198,'20300','Username or password not found');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (198,'20301','Password not the same');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (198,'20302','You can not delete last user setting');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (198,'20303','Please enter username');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (198,'20304','Please enter password');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (198,'20305','User not found');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (198,'20306','Code not valid');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (198,'20307','File type not allowed');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (198,'20308','File size too large');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (198,'20309','Text not valid');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (198,'20310','Text too long');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (198,'20400','Record not found');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (198,'20401','Invalid password');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (198,'20500','Missing latitude or longitude');
--
-- regional_setting_translation
--
INSERT INTO app_portfolio.regional_setting_translation (regional_setting_id, language_id, text) VALUES (490,198,'Gregorian');
INSERT INTO app_portfolio.regional_setting_translation (regional_setting_id, language_id, text) VALUES (491,198,'Hijri');
INSERT INTO app_portfolio.regional_setting_translation (regional_setting_id, language_id, text) VALUES (481,198,'Transliteration');
INSERT INTO app_portfolio.regional_setting_translation (regional_setting_id, language_id, text) VALUES (482,198,'Transliteration, translation');
INSERT INTO app_portfolio.regional_setting_translation (regional_setting_id, language_id, text) VALUES (483,198,'Translation, transliteration');
INSERT INTO app_portfolio.regional_setting_translation (regional_setting_id, language_id, text) VALUES (484,198,'Translation');
INSERT INTO app_portfolio.regional_setting_translation (regional_setting_id, language_id, text) VALUES (479,198,'Left to right');
INSERT INTO app_portfolio.regional_setting_translation (regional_setting_id, language_id, text) VALUES (480,198,'Right to left');
