--Oracle, uncomment:
--SET DEFINE OFF;
--
-- app_category_translation
--
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(1, 201, 'व्यवसाय');
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(2, 201, 'संचार');
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(3, 201, 'शिक्षा');
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(4, 201, 'वित्त');
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(5, 201, 'घर - बार');
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(6, 201, 'उत्पादकता');
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(7, 201, 'खरीदारी');
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(8, 201, 'खेल');
--
-- app_object_item_translation
--
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'DIALOGUE','USERNAME',201,'उपयोगकर्ता नाम');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'DIALOGUE','PASSWORD',201,'पासवर्ड');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'DIALOGUE','BIO',201,'जैव');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'DIALOGUE','EMAIL',201,'ईमेल');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'DIALOGUE','NEW_EMAIL',201,'नई ईमेल');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'DIALOGUE','PASSWORD_CONFIRM',201,'पासवर्ड की पुष्टि');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'DIALOGUE','PASSWORD_REMINDER',201,'पासवर्ड याद दिलाने वाला');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'DIALOGUE','NEW_PASSWORD_CONFIRM',201,'नया पासवर्ड पुष्टि करें');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'DIALOGUE','NEW_PASSWORD',201,'नया पासवर्ड');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'DIALOGUE','CONFIRM_QUESTION',201,'क्या आपको यकीन है?');


INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_ASR',201,'दोपहर बाद');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_ASR_IQAMAT',201,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_CALTYPE_GREGORIAN',201,'ग्रेगोरियन');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_CALTYPE_HIJRI',201,'हिजरी');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_DAY',201,'दिन');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_DHUHR',201,'दोपहर');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_DHUHR_IQAMAT',201,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_FAJR',201,'भोर');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_FAJR_IQAMAT',201,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_IMSAK',201,'Imsak');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_ISHA',201,'रात');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_ISHA_IQAMAT',201,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_MAGHRIB',201,'सूर्यास्त');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_MAGHRIB_IQAMAT',201,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_MIDNIGHT',201,'मध्यरात्रि');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_NOTES',201,'टिप्पणियाँ');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_SUNRISE',201,'सूर्योदय');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_SUNSET',201,'सूर्यास्त');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_ASR',201,'Asr');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_ASR_IQAMAT',201,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_DHUHR',201,'Dhuhr');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_DHUHR_IQAMAT',201,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_FAJR',201,'Fajr');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_FAJR_IQAMAT',201,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_IMSAK',201,'Imsak');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_ISHA',201,'Isha');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_ISHA_IQAMAT',201,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_MAGHRIB',201,'Maghrib');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_MAGHRIB_IQAMAT',201,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_MIDNIGHT',201,'Midnight');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_SUNRISE',201,'Shorook');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_SUNSET',201,'Sunset');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_WEEKDAY',201,'काम करने के दिन');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','TIMETABLE_TITLE',201,'समय सारणी');
--
-- app_object_subitem_translation
--
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_ASR','SETTING_SELECT_ASR_0',201,'मानक');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_ASR','SETTING_SELECT_ASR_1',201,'हनाफी');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_REGIONAL','SETTING_SELECT_CALENDARTYPE','SETTING_SELECT_CALENDARTYPE_0',201,'ग्रेगोरियन');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_REGIONAL','SETTING_SELECT_CALENDARTYPE','SETTING_SELECT_CALENDARTYPE_1',201,'हिजरी');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_HIGHLATITUDE','SETTING_SELECT_HIGHLATITUDE_0',201,'आधी रात');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_HIGHLATITUDE','SETTING_SELECT_HIGHLATITUDE_1',201,'रात का कोण/60वां (अनुशंसित)');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_HIGHLATITUDE','SETTING_SELECT_HIGHLATITUDE_2',201,'1/7 रात');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_HIGHLATITUDE','SETTING_SELECT_HIGHLATITUDE_3',201,'कोई समायोजन नहीं');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_REGIONAL','SETTING_SELECT_REPORT_COLTITLE','SETTING_SELECT_REPORT_COLTITLE_0',201,'लिप्यंतरण');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_REGIONAL','SETTING_SELECT_REPORT_COLTITLE','SETTING_SELECT_REPORT_COLTITLE_1',201,'लिप्यंतरण, अनुवाद');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_REGIONAL','SETTING_SELECT_REPORT_COLTITLE','SETTING_SELECT_REPORT_COLTITLE_2',201,'अनुवाद, लिप्यंतरण');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_REGIONAL','SETTING_SELECT_REPORT_COLTITLE','SETTING_SELECT_REPORT_COLTITLE_3',201,'अनुवाद');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_REGIONAL','SETTING_SELECT_REPORT_DIRECTION','SETTING_SELECT_REPORT_DIRECTION_0',201,'बाएं से दायां');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_REGIONAL','SETTING_SELECT_REPORT_DIRECTION','SETTING_SELECT_REPORT_DIRECTION_1',201,'दाएं से बाएं');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_DESIGN','SETTING_SELECT_REPORT_HIGHLIGHT_ROW','SETTING_SELECT_REPORT_HIGHLIGHT_ROW_0',201,'कोई भी नहीं');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_DESIGN','SETTING_SELECT_REPORT_HIGHLIGHT_ROW','SETTING_SELECT_REPORT_HIGHLIGHT_ROW_1',201,'शुक्रवार');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_DESIGN','SETTING_SELECT_REPORT_HIGHLIGHT_ROW','SETTING_SELECT_REPORT_HIGHLIGHT_ROW_2',201,'शनिवार');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_DESIGN','SETTING_SELECT_REPORT_HIGHLIGHT_ROW','SETTING_SELECT_REPORT_HIGHLIGHT_ROW_3',201,'रविवार');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_DESIGN','SETTING_SELECT_REPORT_HIGHLIGHT_ROW','SETTING_SELECT_REPORT_HIGHLIGHT_ROW_4',201,'10 दिन समूह');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_0',201,'कोई भी नहीं');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_1',201,'10 मिनटों');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_2',201,'15 मिनटों');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_3',201,'20 मिनटों');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_4',201,'25 मिनटों');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_5',201,'30 मिनटों');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_6',201,'अगले घंटे');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_7',201,'अगले घंटे + 15 मिनटों');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_8',201,'अगले घंटे + 30 मिनटों');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_0',201,'कोई भी नहीं');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_1',201,'10 मिनटों');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_2',201,'15 मिनटों');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_3',201,'20 मिनटों');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_4',201,'25 मिनटों');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_5',201,'30 मिनटों');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_6',201,'अगले घंटे');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_7',201,'अगले घंटे + 15 मिनटों');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_8',201,'अगले घंटे + 30 मिनटों');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_0',201,'कोई भी नहीं');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_1',201,'10 मिनटों');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_2',201,'15 मिनटों');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_3',201,'20 मिनटों');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_4',201,'25 मिनटों');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_5',201,'30 मिनटों');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_6',201,'अगले घंटे');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_7',201,'अगले घंटे + 15 मिनटों');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_8',201,'अगले घंटे + 30 मिनटों');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_0',201,'कोई भी नहीं');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_1',201,'10 मिनटों');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_2',201,'15 मिनटों');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_3',201,'20 मिनटों');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_4',201,'25 मिनटों');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_5',201,'30 मिनटों');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_6',201,'अगले घंटे');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_7',201,'अगले घंटे + 15 मिनटों');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_8',201,'अगले घंटे + 30 मिनटों');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_0',201,'कोई भी नहीं');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_1',201,'10 मिनटों');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_2',201,'15 मिनटों');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_3',201,'20 मिनटों');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_4',201,'25 मिनटों');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_5',201,'30 मिनटों');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_6',201,'अगले घंटे');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_7',201,'अगले घंटे + 15 मिनटों');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_8',201,'अगले घंटे + 30 मिनटों');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_REGIONAL','SETTING_SELECT_REPORT_LOCALE_SECOND','SETTING_SELECT_REPORT_LOCALE_SECOND_0',201,'कोई भी नहीं');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_SHOW_FAST_START_END','SETTING_SELECT_REPORT_SHOW_FAST_START_END_0',201,'नहीं');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_SHOW_FAST_START_END','SETTING_SELECT_REPORT_SHOW_FAST_START_END_1',201,'Fajr & Mahgrib');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_SHOW_FAST_START_END','SETTING_SELECT_REPORT_SHOW_FAST_START_END_2',201,'Imsak & Mahgrib');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_SHOW_FAST_START_END','SETTING_SELECT_REPORT_SHOW_FAST_START_END_3',201,'Fajr & Isha');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_SHOW_FAST_START_END','SETTING_SELECT_REPORT_SHOW_FAST_START_END_4',201,'Imsak & Isha');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_TIMEFORMAT','SETTING_SELECT_TIMEFORMAT_0',201,'प्रत्यय के बिना 12 घंटे');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_TIMEFORMAT','SETTING_SELECT_TIMEFORMAT_1',201,'24 घंटे');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_TIMEFORMAT','SETTING_SELECT_TIMEFORMAT_2',201,'प्रत्यय के साथ 12 घंटे');
--
-- app_object_translation
--
INSERT INTO app_portfolio.app_object_translation (app_object_app_id, app_object_object_name, language_id, text) VALUES (2,'APP_DESCRIPTION',201,'प्रोग्रेसिव वेब ऐप (PWA) सिंगल पेज एप्लिकेशन (SPA)');
INSERT INTO app_portfolio.app_object_translation (app_object_app_id, app_object_object_name, language_id, text) VALUES (3,'APP_DESCRIPTION',201,'डेटामॉडल प्रदर्शित करने के लिए सरल ऐप और ऐप प्लेटफ़ॉर्म में ऐप को कैसे एकीकृत किया जाए');
--
-- message_translation
--
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (201,'20100','उपयोगकर्ता नाम 5 - 100 वर्ण');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (201,'20101','मान्य उपयोगकर्ता नाम नहीं');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (201,'20102','जैव अधिकतम 100 वर्ण');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (201,'20103','ईमेल अधिकतम 100 वर्ण');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (201,'20104','रिमाइंडर अधिकतम 100 वर्ण');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (201,'20105','मान्य ईमेल नहीं');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (201,'20106','पासवर्ड 10 - 100 अक्षर');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (201,'20107','उपयोगकर्ता नाम, पासवर्ड और ईमेल की आवश्यकता है');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (201,'20200','ईमेल पहले से मौजूद है');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (201,'20201','प्रदाता पहले से मौजूद है');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (201,'20203','उपयोगकर्ता नाम पहले से मौजूद');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (201,'20204','बहुत लंबा मान');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (201,'20300','उपयोगकर्ता नाम या पासवर्ड नहीं मिला');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (201,'20301','पासवर्ड समान नहीं');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (201,'20302','आप अंतिम उपयोगकर्ता सेटिंग नहीं हटा सकते');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (201,'20303','कृपया उपयोगकर्ता नाम दर्ज करें');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (201,'20304','कृप्या पास्वर्ड भरो');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (201,'20305','उपयोगकर्ता नहीं मिला');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (201,'20306','कोड मान्य नहीं है');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (201,'20307','फ़ाइल प्रकार की अनुमति नहीं है');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (201,'20308','फ़ाइल का आकार बहुत बड़ा');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (201,'20309','टेक्स्ट मान्य नहीं है');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (201,'20310','टेक्स्ट बहुत लंबा');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (201,'20400','रिकॉर्ड नहीं मिला');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (201,'20401','अवैध पासवर्ड');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (201,'20500','लापता अक्षांश या देशांतर');
--
-- regional_setting_translation
--
INSERT INTO app_portfolio.regional_setting_translation (regional_setting_id, language_id, text) VALUES (490,201,'ग्रेगोरियन');
INSERT INTO app_portfolio.regional_setting_translation (regional_setting_id, language_id, text) VALUES (491,201,'हिजरी');
INSERT INTO app_portfolio.regional_setting_translation (regional_setting_id, language_id, text) VALUES (481,201,'लिप्यंतरण');
INSERT INTO app_portfolio.regional_setting_translation (regional_setting_id, language_id, text) VALUES (482,201,'लिप्यंतरण, अनुवाद');
INSERT INTO app_portfolio.regional_setting_translation (regional_setting_id, language_id, text) VALUES (483,201,'अनुवाद, लिप्यंतरण');
INSERT INTO app_portfolio.regional_setting_translation (regional_setting_id, language_id, text) VALUES (484,201,'अनुवाद');
INSERT INTO app_portfolio.regional_setting_translation (regional_setting_id, language_id, text) VALUES (479,201,'बाएं से दायां');
INSERT INTO app_portfolio.regional_setting_translation (regional_setting_id, language_id, text) VALUES (480,201,'दाएं से बाएं');
