--Oracle, uncomment:
--SET DEFINE OFF;
--
-- app_category_translation
--
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(1, 224, '仕事');
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(2, 224, 'コミュニケーション');
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(3, 224, '教育');
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(4, 224, 'ファイナンス');
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(5, 224, '家と家');
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(6, 224, '生産性');
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(7, 224, '買い物');
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(8, 224, 'ゲーム');
--
-- app_object_item_translation
--
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'COMMON','USERNAME',224,'ユーザー名');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'COMMON','PASSWORD',224,'パスワード');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'COMMON','BIO',224,'バイオ');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'COMMON','EMAIL',224,'Eメール');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'COMMON','NEW_EMAIL',224,'新しいメール');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'COMMON','PASSWORD_CONFIRM',224,'パスワード確認');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'COMMON','PASSWORD_REMINDER',224,'パスワードリマインダー');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'COMMON','NEW_PASSWORD_CONFIRM',224,'新しいパスワードの確認');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'COMMON','NEW_PASSWORD',224,'新しいパスワード');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'COMMON','CONFIRM_QUESTION',224,'本気ですか？');


INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_ASR',224,'午後');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_ASR_IQAMAT',224,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_CALTYPE_GREGORIAN',224,'グレゴリオ暦');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_CALTYPE_HIJRI',224,'Hijri');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_DAY',224,'日');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_DHUHR',224,'昼');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_DHUHR_IQAMAT',224,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_FAJR',224,'夜明け');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_FAJR_IQAMAT',224,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_IMSAK',224,'Imsak');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_ISHA',224,'夜');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_ISHA_IQAMAT',224,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_MAGHRIB',224,'日没');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_MAGHRIB_IQAMAT',224,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_MIDNIGHT',224,'夜中');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_NOTES',224,'ノート');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_SUNRISE',224,'日の出');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_SUNSET',224,'日没');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_ASR',224,'Asr');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_ASR_IQAMAT',224,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_DHUHR',224,'Dhuhr');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_DHUHR_IQAMAT',224,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_FAJR',224,'Fajr');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_FAJR_IQAMAT',224,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_IMSAK',224,'Imsak');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_ISHA',224,'Isha');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_ISHA_IQAMAT',224,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_MAGHRIB',224,'Maghrib');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_MAGHRIB_IQAMAT',224,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_MIDNIGHT',224,'Midnight');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_SUNRISE',224,'Shorook');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_SUNSET',224,'Sunset');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_WEEKDAY',224,'平日');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','TIMETABLE_TITLE',224,'時刻表');
--
-- app_object_subitem_translation
--
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_ASR','SETTING_SELECT_ASR_0',224,'標準');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_ASR','SETTING_SELECT_ASR_1',224,'ハナフィ');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_CALENDARTYPE','SETTING_SELECT_CALENDARTYPE_0',224,'グレゴリオ暦');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_CALENDARTYPE','SETTING_SELECT_CALENDARTYPE_1',224,'Hijri');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_HIGHLATITUDE','SETTING_SELECT_HIGHLATITUDE_0',224,'真夜中');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_HIGHLATITUDE','SETTING_SELECT_HIGHLATITUDE_1',224,'角度/夜の60度（推奨）');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_HIGHLATITUDE','SETTING_SELECT_HIGHLATITUDE_2',224,'夜の1/7');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_HIGHLATITUDE','SETTING_SELECT_HIGHLATITUDE_3',224,'調整なし');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_COLTITLE','SETTING_SELECT_REPORT_COLTITLE_0',224,'音訳');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_COLTITLE','SETTING_SELECT_REPORT_COLTITLE_1',224,'音訳、翻訳');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_COLTITLE','SETTING_SELECT_REPORT_COLTITLE_2',224,'翻訳・音訳');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_COLTITLE','SETTING_SELECT_REPORT_COLTITLE_3',224,'翻訳');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_DIRECTION','SETTING_SELECT_REPORT_DIRECTION_0',224,'左から右へ');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_DIRECTION','SETTING_SELECT_REPORT_DIRECTION_1',224,'右から左へ');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_HIGHLIGHT_ROW','SETTING_SELECT_REPORT_HIGHLIGHT_ROW_0',224,'なし');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_HIGHLIGHT_ROW','SETTING_SELECT_REPORT_HIGHLIGHT_ROW_1',224,'金曜日');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_HIGHLIGHT_ROW','SETTING_SELECT_REPORT_HIGHLIGHT_ROW_2',224,'土曜日');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_HIGHLIGHT_ROW','SETTING_SELECT_REPORT_HIGHLIGHT_ROW_3',224,'日曜日');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_HIGHLIGHT_ROW','SETTING_SELECT_REPORT_HIGHLIGHT_ROW_4',224,'10日間のグループ');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_0',224,'なし');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_1',224,'10 分');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_2',224,'15 分');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_3',224,'20 分');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_4',224,'25 分');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_5',224,'30 分');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_6',224,'次の時間');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_7',224,'次の時間 + 15 分');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_8',224,'次の時間 + 30 分');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_0',224,'なし');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_1',224,'10 分');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_2',224,'15 分');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_3',224,'20 分');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_4',224,'25 分');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_5',224,'30 分');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_6',224,'次の時間');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_7',224,'次の時間 + 15 分');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_8',224,'次の時間 + 30 分');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_0',224,'なし');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_1',224,'10 分');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_2',224,'15 分');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_3',224,'20 分');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_4',224,'25 分');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_5',224,'30 分');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_6',224,'次の時間');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_7',224,'次の時間 + 15 分');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_8',224,'次の時間 + 30 分');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_0',224,'なし');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_1',224,'10 分');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_2',224,'15 分');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_3',224,'20 分');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_4',224,'25 分');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_5',224,'30 分');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_6',224,'次の時間');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_7',224,'次の時間 + 15 分');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_8',224,'次の時間 + 30 分');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_0',224,'なし');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_1',224,'10 分');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_2',224,'15 分');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_3',224,'20 分');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_4',224,'25 分');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_5',224,'30 分');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_6',224,'次の時間');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_7',224,'次の時間 + 15 分');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_8',224,'次の時間 + 30 分');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_LOCALE_SECOND','SETTING_SELECT_REPORT_LOCALE_SECOND_0',224,'なし');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_SHOW_FAST_START_END','SETTING_SELECT_REPORT_SHOW_FAST_START_END_0',224,'いいえ');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_SHOW_FAST_START_END','SETTING_SELECT_REPORT_SHOW_FAST_START_END_1',224,'Fajr & Mahgrib');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_SHOW_FAST_START_END','SETTING_SELECT_REPORT_SHOW_FAST_START_END_2',224,'Imsak & Mahgrib');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_SHOW_FAST_START_END','SETTING_SELECT_REPORT_SHOW_FAST_START_END_3',224,'Fajr & Isha');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_SHOW_FAST_START_END','SETTING_SELECT_REPORT_SHOW_FAST_START_END_4',224,'Imsak & Isha');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_TIMEFORMAT','SETTING_SELECT_TIMEFORMAT_0',224,'サフィックスなしの 12 時間');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_TIMEFORMAT','SETTING_SELECT_TIMEFORMAT_1',224,'24時間');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_TIMEFORMAT','SETTING_SELECT_TIMEFORMAT_2',224,'接尾辞付きの 12 時間');
--
-- app_object_translation
--
INSERT INTO app_portfolio.app_object_translation (app_object_app_id, app_object_object_name, language_id, text) VALUES (2,'APP_DESCRIPTION',224,'プログレッシブ Web アプリ (PWA) シングル ページ アプリケーション (SPA)');
INSERT INTO app_portfolio.app_object_translation (app_object_app_id, app_object_object_name, language_id, text) VALUES (3,'APP_DESCRIPTION',224,'データモデルを表示するシンプルなアプリと、アプリ プラットフォームにアプリを統合する方法');
--
-- message_translation
--
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (224,'20100','ユーザー名 5～100文字');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (224,'20101','ユーザー名が無効です');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (224,'20102','バイオマックス100キャラ');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (224,'20103','メールの最大文字数は 100 文字です');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (224,'20104','リマインダー最大 100 文字');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (224,'20105','無効な電子メール');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (224,'20106','パスワード 10～100文字');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (224,'20107','ユーザー名、パスワード、メールアドレスが必要です');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (224,'20200','メールは既に存在します');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (224,'20201','プロバイダーは既に存在します');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (224,'20203','ユーザー名は既に存在します');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (224,'20204','値が長すぎます');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (224,'20300','ユーザー名またはパスワードが見つかりません');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (224,'20301','パスワードが同じではありません');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (224,'20302','最後のユーザー設定は削除できません');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (224,'20303','ユーザー名を入力してください');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (224,'20304','パスワードを入力してください');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (224,'20305','ユーザーが見つかりません');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (224,'20306','コードが無効です');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (224,'20307','ファイル形式は許可されていません');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (224,'20308','ファイルサイズが大きすぎます');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (224,'20309','テキストが無効です');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (224,'20310','テキストが長すぎます');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (224,'20400','記録が見当たりませんでした');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (224,'20401','無効なパスワード');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (224,'20500','緯度または経度がありません');
--
-- regional_setting_translation
--
INSERT INTO app_portfolio.regional_setting_translation (regional_setting_id, language_id, text) VALUES (490,224,'グレゴリオ暦');
INSERT INTO app_portfolio.regional_setting_translation (regional_setting_id, language_id, text) VALUES (491,224,'Hijri');
INSERT INTO app_portfolio.regional_setting_translation (regional_setting_id, language_id, text) VALUES (481,224,'音訳');
INSERT INTO app_portfolio.regional_setting_translation (regional_setting_id, language_id, text) VALUES (482,224,'音訳、翻訳');
INSERT INTO app_portfolio.regional_setting_translation (regional_setting_id, language_id, text) VALUES (483,224,'翻訳・音訳');
INSERT INTO app_portfolio.regional_setting_translation (regional_setting_id, language_id, text) VALUES (484,224,'翻訳');
INSERT INTO app_portfolio.regional_setting_translation (regional_setting_id, language_id, text) VALUES (479,224,'左から右へ');
INSERT INTO app_portfolio.regional_setting_translation (regional_setting_id, language_id, text) VALUES (480,224,'右から左へ');
