--Oracle, uncomment:
--SET DEFINE OFF;
--
-- app_category_translation
--
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(1, 338, 'Business');
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(2, 338, 'Communications');
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(3, 338, 'Education');
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(4, 338, 'Finance');
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(5, 338, 'House & Home');
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(6, 338, 'Productivity');
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(7, 338, 'Shopping');
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(8, 338, 'Game');
--
-- app_object_item_translation
--
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'COMMON','USERNAME',338,'Username');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'COMMON','PASSWORD',338,'Password');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'COMMON','BIO',338,'Bio');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'COMMON','EMAIL',338,'Email');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'COMMON','NEW_EMAIL',338,'New email');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'COMMON','PASSWORD_CONFIRM',338,'Password confirm');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'COMMON','PASSWORD_REMINDER',338,'Password reminder');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'COMMON','NEW_PASSWORD_CONFIRM',338,'New password confirm');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'COMMON','NEW_PASSWORD',338,'New password');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'COMMON','CONFIRM_QUESTION',338,'Are you sure?');


INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_ASR',338,'Afternoon');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_ASR_IQAMAT',338,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_CALTYPE_GREGORIAN',338,'Gregorian');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_CALTYPE_HIJRI',338,'Hijri');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_DAY',338,'Day');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_DHUHR',338,'Noon');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_DHUHR_IQAMAT',338,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_FAJR',338,'Dawn');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_FAJR_IQAMAT',338,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_IMSAK',338,'Imsak');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_ISHA',338,'Night');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_ISHA_IQAMAT',338,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_MAGHRIB',338,'Sunset');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_MAGHRIB_IQAMAT',338,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_MIDNIGHT',338,'Midnight');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_NOTES',338,'Notes');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_SUNRISE',338,'Sunrise');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_SUNSET',338,'Sunset');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_ASR',338,'Asr');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_ASR_IQAMAT',338,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_DHUHR',338,'Dhuhr');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_DHUHR_IQAMAT',338,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_FAJR',338,'Fajr');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_FAJR_IQAMAT',338,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_IMSAK',338,'Imsak');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_ISHA',338,'Isha');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_ISHA_IQAMAT',338,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_MAGHRIB',338,'Maghrib');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_MAGHRIB_IQAMAT',338,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_MIDNIGHT',338,'Midnight');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_SUNRISE',338,'Shorook');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_SUNSET',338,'Sunset');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_WEEKDAY',338,'Weekday');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','TIMETABLE_TITLE',338,'Timetable');
--
-- app_object_subitem_translation
--
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_ASR','SETTING_SELECT_ASR_0',338,'Standard');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_ASR','SETTING_SELECT_ASR_1',338,'Hanafi');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_CALENDARTYPE','SETTING_SELECT_CALENDARTYPE_0',338,'Gregorian');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_CALENDARTYPE','SETTING_SELECT_CALENDARTYPE_1',338,'Hijri');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_HIGHLATITUDE','SETTING_SELECT_HIGHLATITUDE_0',338,'Middle of night');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_HIGHLATITUDE','SETTING_SELECT_HIGHLATITUDE_1',338,'Angle/60th of night (recommended)');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_HIGHLATITUDE','SETTING_SELECT_HIGHLATITUDE_2',338,'1/7th of night');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_HIGHLATITUDE','SETTING_SELECT_HIGHLATITUDE_3',338,'No adjustment');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_COLTITLE','SETTING_SELECT_REPORT_COLTITLE_0',338,'Transliteration');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_COLTITLE','SETTING_SELECT_REPORT_COLTITLE_1',338,'Transliteration, translation');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_COLTITLE','SETTING_SELECT_REPORT_COLTITLE_2',338,'Translation, transliteration');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_COLTITLE','SETTING_SELECT_REPORT_COLTITLE_3',338,'Translation');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_DIRECTION','SETTING_SELECT_REPORT_DIRECTION_0',338,'Left to right');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_DIRECTION','SETTING_SELECT_REPORT_DIRECTION_1',338,'Right to left');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_HIGHLIGHT_ROW','SETTING_SELECT_REPORT_HIGHLIGHT_ROW_0',338,'None');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_HIGHLIGHT_ROW','SETTING_SELECT_REPORT_HIGHLIGHT_ROW_1',338,'Friday');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_HIGHLIGHT_ROW','SETTING_SELECT_REPORT_HIGHLIGHT_ROW_2',338,'Saturday');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_HIGHLIGHT_ROW','SETTING_SELECT_REPORT_HIGHLIGHT_ROW_3',338,'Sunday');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_HIGHLIGHT_ROW','SETTING_SELECT_REPORT_HIGHLIGHT_ROW_4',338,'10 days groups');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_0',338,'None');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_1',338,'10 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_2',338,'15 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_3',338,'20 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_4',338,'25 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_5',338,'30 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_6',338,'Next hour');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_7',338,'Next hour + 15 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_8',338,'Next hour + 30 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_0',338,'None');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_1',338,'10 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_2',338,'15 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_3',338,'20 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_4',338,'25 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_5',338,'30 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_6',338,'Next hour');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_7',338,'Next hour + 15 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_8',338,'Next hour + 30 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_0',338,'None');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_1',338,'10 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_2',338,'15 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_3',338,'20 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_4',338,'25 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_5',338,'30 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_6',338,'Next hour');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_7',338,'Next hour + 15 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_8',338,'Next hour + 30 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_0',338,'None');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_1',338,'10 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_2',338,'15 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_3',338,'20 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_4',338,'25 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_5',338,'30 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_6',338,'Next hour');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_7',338,'Next hour + 15 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_8',338,'Next hour + 30 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_0',338,'None');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_1',338,'10 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_2',338,'15 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_3',338,'20 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_4',338,'25 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_5',338,'30 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_6',338,'Next hour');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_7',338,'Next hour + 15 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_8',338,'Next hour + 30 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_LOCALE_SECOND','SETTING_SELECT_REPORT_LOCALE_SECOND_0',338,'None');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_SHOW_FAST_START_END','SETTING_SELECT_REPORT_SHOW_FAST_START_END_0',338,'No');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_SHOW_FAST_START_END','SETTING_SELECT_REPORT_SHOW_FAST_START_END_1',338,'Fajr & Mahgrib');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_SHOW_FAST_START_END','SETTING_SELECT_REPORT_SHOW_FAST_START_END_2',338,'Imsak & Mahgrib');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_SHOW_FAST_START_END','SETTING_SELECT_REPORT_SHOW_FAST_START_END_3',338,'Fajr & Isha');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_SHOW_FAST_START_END','SETTING_SELECT_REPORT_SHOW_FAST_START_END_4',338,'Imsak & Isha');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_TIMEFORMAT','SETTING_SELECT_TIMEFORMAT_0',338,'12-hour without suffix');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_TIMEFORMAT','SETTING_SELECT_TIMEFORMAT_1',338,'24-hour');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_TIMEFORMAT','SETTING_SELECT_TIMEFORMAT_2',338,'12-hour with suffix');
--
-- app_object_translation
--
INSERT INTO app_portfolio.app_object_translation (app_object_app_id, app_object_object_name, language_id, text) VALUES (2,'APP_DESCRIPTION',338,'Progressive web app (PWA) single page application (SPA)');
INSERT INTO app_portfolio.app_object_translation (app_object_app_id, app_object_object_name, language_id, text) VALUES (3,'APP_DESCRIPTION',338,'Simple app to display datamodel and how to integrate an app in the app platform');
--
-- message_translation
--
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (338,'20100','Username 5 - 100 characters');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (338,'20101','Not valid username');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (338,'20102','Bio max 100 characters');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (338,'20103','Email max 100 characters');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (338,'20104','Reminder max 100 characters');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (338,'20105','Not valid email');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (338,'20106','Password 10 - 100 characters');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (338,'20107','Username, password and email are required');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (338,'20200','Email already exist');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (338,'20201','Provider already exist');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (338,'20203','Username already exist');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (338,'20204','Too long value');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (338,'20300','Username or password not found');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (338,'20301','Password not the same');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (338,'20302','You can not delete last user setting');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (338,'20303','Please enter username');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (338,'20304','Please enter password');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (338,'20305','User not found');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (338,'20306','Code not valid');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (338,'20307','File type not allowed');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (338,'20308','File size too large');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (338,'20309','Text not valid');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (338,'20310','Text too long');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (338,'20400','Record not found');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (338,'20401','Invalid password');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (338,'20500','Missing latitude or longitude');
--
-- regional_setting_translation
--
INSERT INTO app_portfolio.regional_setting_translation (regional_setting_id, language_id, text) VALUES (490,338,'Gregorian');
INSERT INTO app_portfolio.regional_setting_translation (regional_setting_id, language_id, text) VALUES (491,338,'Hijri');
INSERT INTO app_portfolio.regional_setting_translation (regional_setting_id, language_id, text) VALUES (481,338,'Transliteration');
INSERT INTO app_portfolio.regional_setting_translation (regional_setting_id, language_id, text) VALUES (482,338,'Transliteration, translation');
INSERT INTO app_portfolio.regional_setting_translation (regional_setting_id, language_id, text) VALUES (483,338,'Translation, transliteration');
INSERT INTO app_portfolio.regional_setting_translation (regional_setting_id, language_id, text) VALUES (484,338,'Translation');
INSERT INTO app_portfolio.regional_setting_translation (regional_setting_id, language_id, text) VALUES (479,338,'Left to right');
INSERT INTO app_portfolio.regional_setting_translation (regional_setting_id, language_id, text) VALUES (480,338,'Right to left');
