--Oracle, uncomment:
--SET DEFINE OFF;
--
-- app_category_translation
--
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(1, 436, 'Business');
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(2, 436, 'Communications');
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(3, 436, 'Education');
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(4, 436, 'Finance');
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(5, 436, 'House & Home');
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(6, 436, 'Productivity');
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(7, 436, 'Shopping');
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(8, 436, 'Game');
--
-- app_object_item_translation
--
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'DIALOGUE','USERNAME',436,'Username');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'DIALOGUE','PASSWORD',436,'Password');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'DIALOGUE','BIO',436,'Bio');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'DIALOGUE','EMAIL',436,'Email');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'DIALOGUE','NEW_EMAIL',436,'New email');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'DIALOGUE','PASSWORD_CONFIRM',436,'Password confirm');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'DIALOGUE','PASSWORD_REMINDER',436,'Password reminder');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'DIALOGUE','NEW_PASSWORD_CONFIRM',436,'New password confirm');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'DIALOGUE','NEW_PASSWORD',436,'New password');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'DIALOGUE','CONFIRM_QUESTION',436,'Are you sure?');


INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_ASR',436,'Afternoon');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_ASR_IQAMAT',436,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_CALTYPE_GREGORIAN',436,'Gregorian');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_CALTYPE_HIJRI',436,'Hijri');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_DAY',436,'Day');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_DHUHR',436,'Noon');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_DHUHR_IQAMAT',436,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_FAJR',436,'Dawn');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_FAJR_IQAMAT',436,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_IMSAK',436,'Imsak');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_ISHA',436,'Night');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_ISHA_IQAMAT',436,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_MAGHRIB',436,'Sunset');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_MAGHRIB_IQAMAT',436,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_MIDNIGHT',436,'Midnight');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_NOTES',436,'Notes');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_SUNRISE',436,'Sunrise');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_SUNSET',436,'Sunset');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_ASR',436,'Asr');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_ASR_IQAMAT',436,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_DHUHR',436,'Dhuhr');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_DHUHR_IQAMAT',436,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_FAJR',436,'Fajr');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_FAJR_IQAMAT',436,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_IMSAK',436,'Imsak');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_ISHA',436,'Isha');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_ISHA_IQAMAT',436,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_MAGHRIB',436,'Maghrib');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_MAGHRIB_IQAMAT',436,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_MIDNIGHT',436,'Midnight');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_SUNRISE',436,'Shorook');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_SUNSET',436,'Sunset');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_WEEKDAY',436,'Weekday');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','TIMETABLE_TITLE',436,'Timetable');
--
-- app_object_subitem_translation
--
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_ASR','SETTING_SELECT_ASR_0',436,'Standard');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_ASR','SETTING_SELECT_ASR_1',436,'Hanafi');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_REGIONAL','SETTING_SELECT_CALENDARTYPE','SETTING_SELECT_CALENDARTYPE_0',436,'Gregorian');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_REGIONAL','SETTING_SELECT_CALENDARTYPE','SETTING_SELECT_CALENDARTYPE_1',436,'Hijri');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_HIGHLATITUDE','SETTING_SELECT_HIGHLATITUDE_0',436,'Middle of night');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_HIGHLATITUDE','SETTING_SELECT_HIGHLATITUDE_1',436,'Angle/60th of night (recommended)');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_HIGHLATITUDE','SETTING_SELECT_HIGHLATITUDE_2',436,'1/7th of night');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_HIGHLATITUDE','SETTING_SELECT_HIGHLATITUDE_3',436,'No adjustment');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_REGIONAL','SETTING_SELECT_REPORT_COLTITLE','SETTING_SELECT_REPORT_COLTITLE_0',436,'Transliteration');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_REGIONAL','SETTING_SELECT_REPORT_COLTITLE','SETTING_SELECT_REPORT_COLTITLE_1',436,'Transliteration, translation');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_REGIONAL','SETTING_SELECT_REPORT_COLTITLE','SETTING_SELECT_REPORT_COLTITLE_2',436,'Translation, transliteration');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_REGIONAL','SETTING_SELECT_REPORT_COLTITLE','SETTING_SELECT_REPORT_COLTITLE_3',436,'Translation');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_REGIONAL','SETTING_SELECT_REPORT_DIRECTION','SETTING_SELECT_REPORT_DIRECTION_0',436,'Left to right');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_REGIONAL','SETTING_SELECT_REPORT_DIRECTION','SETTING_SELECT_REPORT_DIRECTION_1',436,'Right to left');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_DESIGN','SETTING_SELECT_REPORT_HIGHLIGHT_ROW','SETTING_SELECT_REPORT_HIGHLIGHT_ROW_0',436,'None');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_DESIGN','SETTING_SELECT_REPORT_HIGHLIGHT_ROW','SETTING_SELECT_REPORT_HIGHLIGHT_ROW_1',436,'Friday');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_DESIGN','SETTING_SELECT_REPORT_HIGHLIGHT_ROW','SETTING_SELECT_REPORT_HIGHLIGHT_ROW_2',436,'Saturday');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_DESIGN','SETTING_SELECT_REPORT_HIGHLIGHT_ROW','SETTING_SELECT_REPORT_HIGHLIGHT_ROW_3',436,'Sunday');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_DESIGN','SETTING_SELECT_REPORT_HIGHLIGHT_ROW','SETTING_SELECT_REPORT_HIGHLIGHT_ROW_4',436,'10 days groups');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_0',436,'None');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_1',436,'10 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_2',436,'15 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_3',436,'20 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_4',436,'25 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_5',436,'30 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_6',436,'Next hour');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_7',436,'Next hour + 15 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_8',436,'Next hour + 30 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_0',436,'None');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_1',436,'10 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_2',436,'15 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_3',436,'20 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_4',436,'25 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_5',436,'30 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_6',436,'Next hour');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_7',436,'Next hour + 15 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_8',436,'Next hour + 30 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_0',436,'None');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_1',436,'10 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_2',436,'15 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_3',436,'20 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_4',436,'25 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_5',436,'30 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_6',436,'Next hour');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_7',436,'Next hour + 15 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_8',436,'Next hour + 30 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_0',436,'None');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_1',436,'10 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_2',436,'15 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_3',436,'20 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_4',436,'25 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_5',436,'30 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_6',436,'Next hour');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_7',436,'Next hour + 15 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_8',436,'Next hour + 30 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_0',436,'None');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_1',436,'10 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_2',436,'15 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_3',436,'20 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_4',436,'25 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_5',436,'30 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_6',436,'Next hour');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_7',436,'Next hour + 15 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_8',436,'Next hour + 30 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_REGIONAL','SETTING_SELECT_REPORT_LOCALE_SECOND','SETTING_SELECT_REPORT_LOCALE_SECOND_0',436,'None');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_SHOW_FAST_START_END','SETTING_SELECT_REPORT_SHOW_FAST_START_END_0',436,'No');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_SHOW_FAST_START_END','SETTING_SELECT_REPORT_SHOW_FAST_START_END_1',436,'Fajr & Mahgrib');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_SHOW_FAST_START_END','SETTING_SELECT_REPORT_SHOW_FAST_START_END_2',436,'Imsak & Mahgrib');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_SHOW_FAST_START_END','SETTING_SELECT_REPORT_SHOW_FAST_START_END_3',436,'Fajr & Isha');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_SHOW_FAST_START_END','SETTING_SELECT_REPORT_SHOW_FAST_START_END_4',436,'Imsak & Isha');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_TIMEFORMAT','SETTING_SELECT_TIMEFORMAT_0',436,'12-hour without suffix');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_TIMEFORMAT','SETTING_SELECT_TIMEFORMAT_1',436,'24-hour');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_TIMEFORMAT','SETTING_SELECT_TIMEFORMAT_2',436,'12-hour with suffix');
--
-- app_object_translation
--
INSERT INTO app_portfolio.app_object_translation (app_object_app_id, app_object_object_name, language_id, text) VALUES (2,'APP_DESCRIPTION',436,'Progressive web app (PWA) single page application (SPA)');
INSERT INTO app_portfolio.app_object_translation (app_object_app_id, app_object_object_name, language_id, text) VALUES (3,'APP_DESCRIPTION',436,'Simple app to display datamodel and how to integrate an app in the app platform');
--
-- message_translation
--
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (436,'20100','Username 5 - 100 characters');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (436,'20101','Not valid username');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (436,'20102','Bio max 100 characters');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (436,'20103','Email max 100 characters');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (436,'20104','Reminder max 100 characters');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (436,'20105','Not valid email');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (436,'20106','Password 10 - 100 characters');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (436,'20107','Username, password and email are required');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (436,'20200','Email already exist');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (436,'20201','Provider already exist');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (436,'20203','Username already exist');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (436,'20204','Too long value');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (436,'20300','Username or password not found');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (436,'20301','Password not the same');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (436,'20302','You can not delete last user setting');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (436,'20303','Please enter username');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (436,'20304','Please enter password');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (436,'20305','User not found');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (436,'20306','Code not valid');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (436,'20307','File type not allowed');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (436,'20308','File size too large');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (436,'20309','Text not valid');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (436,'20310','Text too long');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (436,'20400','Record not found');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (436,'20401','Invalid password');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (436,'20500','Missing latitude or longitude');