--Oracle, uncomment:
--SET DEFINE OFF;
--
-- app_category_translation
--
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(1, 515, 'Affär');
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(2, 515, 'Kommunikation');
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(3, 515, 'Utbildning');
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(4, 515, 'Finans');
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(5, 515, 'Hus & Hem');
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(6, 515, 'Produktivitet');
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(7, 515, 'Shopping');
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(8, 515, 'Spel');
--
-- app_object_item_translation
--
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'COMMON','USERNAME',515,'Användarnamn');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'COMMON','PASSWORD',515,'Lösenord');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'COMMON','BIO',515,'Bio');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'COMMON','EMAIL',515,'E-post');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'COMMON','NEW_EMAIL',515,'Ny e-post');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'COMMON','PASSWORD_CONFIRM',515,'Bekräfta lösenord');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'COMMON','PASSWORD_REMINDER',515,'Lösenordspåminnelse');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'COMMON','NEW_PASSWORD_CONFIRM',515,'Nytt bekräfta lösenord');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'COMMON','NEW_PASSWORD',515,'Nytt lösenord');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'COMMON','CONFIRM_QUESTION',515,'Är du säker?');

INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_ASR',515,'Eftermiddag');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_ASR_IQAMAT',515,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_CALTYPE_GREGORIAN',515,'Gregoriansk');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_CALTYPE_HIJRI',515,'Hijri');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_DAY',515,'Dag');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_DHUHR',515,'Middag');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_DHUHR_IQAMAT',515,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_FAJR',515,'Gryning');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_FAJR_IQAMAT',515,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_IMSAK',515,'Imsak');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_ISHA',515,'Natt');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_ISHA_IQAMAT',515,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_MAGHRIB',515,'Solnedgång');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_MAGHRIB_IQAMAT',515,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_MIDNIGHT',515,'Midnatt');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_NOTES',515,'Noteringar');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_SUNRISE',515,'Soluppgång');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_SUNSET',515,'Solnedgång');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_ASR',515,'Asr');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_ASR_IQAMAT',515,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_DHUHR',515,'Dhuhr');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_DHUHR_IQAMAT',515,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_FAJR',515,'Fajr');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_FAJR_IQAMAT',515,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_IMSAK',515,'Imsak');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_ISHA',515,'Isha');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_ISHA_IQAMAT',515,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_MAGHRIB',515,'Maghrib');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_MAGHRIB_IQAMAT',515,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_MIDNIGHT',515,'Midnight');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_SUNRISE',515,'Shorook');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_SUNSET',515,'Sunset');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_WEEKDAY',515,'Veckodag');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','TIMETABLE_TITLE',515,'Tidtabell');
--
-- app_object_subitem_translation
--
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_ASR','SETTING_SELECT_ASR_0',515,'Standard');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_ASR','SETTING_SELECT_ASR_1',515,'Hanafi');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_CALENDARTYPE','SETTING_SELECT_CALENDARTYPE_0',515,'Gregoriansk');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_CALENDARTYPE','SETTING_SELECT_CALENDARTYPE_1',515,'Hijri');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_HIGHLATITUDE','SETTING_SELECT_HIGHLATITUDE_0',515,'Mitten av natten');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_HIGHLATITUDE','SETTING_SELECT_HIGHLATITUDE_1',515,'Vinkel/60 av natt (rekommenderad)');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_HIGHLATITUDE','SETTING_SELECT_HIGHLATITUDE_2',515,'1/7 av natt');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_HIGHLATITUDE','SETTING_SELECT_HIGHLATITUDE_3',515,'Ingen justering');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_COLTITLE','SETTING_SELECT_REPORT_COLTITLE_0',515,'Translitterering');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_COLTITLE','SETTING_SELECT_REPORT_COLTITLE_1',515,'Translitterering, översättning');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_COLTITLE','SETTING_SELECT_REPORT_COLTITLE_2',515,'Översättning, translitterering');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_COLTITLE','SETTING_SELECT_REPORT_COLTITLE_3',515,'Översättning');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_DIRECTION','SETTING_SELECT_REPORT_DIRECTION_0',515,'Vänster till höger');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_DIRECTION','SETTING_SELECT_REPORT_DIRECTION_1',515,'Höger till vänster');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_HIGHLIGHT_ROW','SETTING_SELECT_REPORT_HIGHLIGHT_ROW_0',515,'Inga');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_HIGHLIGHT_ROW','SETTING_SELECT_REPORT_HIGHLIGHT_ROW_1',515,'Fredag');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_HIGHLIGHT_ROW','SETTING_SELECT_REPORT_HIGHLIGHT_ROW_2',515,'Lördag');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_HIGHLIGHT_ROW','SETTING_SELECT_REPORT_HIGHLIGHT_ROW_3',515,'Söndag');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_HIGHLIGHT_ROW','SETTING_SELECT_REPORT_HIGHLIGHT_ROW_4',515,'10 dagars grupp');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_0',515,'Inga');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_1',515,'10 minuter');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_2',515,'15 minuter');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_3',515,'20 minuter');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_4',515,'25 minuter');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_5',515,'30 minuter');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_6',515,'Nästa timme');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_7',515,'Nästa timme + 15 minuter');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_8',515,'Nästa timme + 30 minuter');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_0',515,'Inga');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_1',515,'10 minuter');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_2',515,'15 minuter');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_3',515,'20 minuter');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_4',515,'25 minuter');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_5',515,'30 minuter');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_6',515,'Nästa timme');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_7',515,'Nästa timme + 15 minuter');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_8',515,'Nästa timme + 30 minuter');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_0',515,'Inga');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_1',515,'10 minuter');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_2',515,'15 minuter');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_3',515,'20 minuter');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_4',515,'25 minuter');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_5',515,'30 minuter');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_6',515,'Nästa timme');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_7',515,'Nästa timme + 15 minuter');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_8',515,'Nästa timme + 30 minuter');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_0',515,'Inga');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_1',515,'10 minuter');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_2',515,'15 minuter');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_3',515,'20 minuter');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_4',515,'25 minuter');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_5',515,'30 minuter');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_6',515,'Nästa timme');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_7',515,'Nästa timme + 15 minuter');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_8',515,'Nästa timme + 30 minuter');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_0',515,'Inga');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_1',515,'10 minuter');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_2',515,'15 minuter');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_3',515,'20 minuter');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_4',515,'25 minuter');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_5',515,'30 minuter');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_6',515,'Nästa timme');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_7',515,'Nästa timme + 15 minuter');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_8',515,'Nästa timme + 30 minuter');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_LOCALE_SECOND','SETTING_SELECT_REPORT_LOCALE_SECOND_0',515,'Inget');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_SHOW_FAST_START_END','SETTING_SELECT_REPORT_SHOW_FAST_START_END_0',515,'Nej');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_SHOW_FAST_START_END','SETTING_SELECT_REPORT_SHOW_FAST_START_END_1',515,'Fajr & Mahgrib');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_SHOW_FAST_START_END','SETTING_SELECT_REPORT_SHOW_FAST_START_END_2',515,'Imsak & Mahgrib');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_SHOW_FAST_START_END','SETTING_SELECT_REPORT_SHOW_FAST_START_END_3',515,'Fajr & Isha');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_SHOW_FAST_START_END','SETTING_SELECT_REPORT_SHOW_FAST_START_END_4',515,'Imsak & Isha');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_TIMEFORMAT','SETTING_SELECT_TIMEFORMAT_0',515,'12-tim utan suffix');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_TIMEFORMAT','SETTING_SELECT_TIMEFORMAT_1',515,'24-tim');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_TIMEFORMAT','SETTING_SELECT_TIMEFORMAT_2',515,'12-tim med suffix');
--
-- app_object_translation
--
INSERT INTO app_portfolio.app_object_translation (app_object_app_id, app_object_object_name, language_id, text) VALUES (2,'APP_DESCRIPTION',515,'Ensidesprogram för progressiv webbapp (PWA) (SPA)');
INSERT INTO app_portfolio.app_object_translation (app_object_app_id, app_object_object_name, language_id, text) VALUES (3,'APP_DESCRIPTION',515,'Enkel app för att visa datamodell och hur man integrerar en app i app plattformen');
--
-- message_translation
--
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (515,'20100','Username 5 - 100 characters');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (515,'20101','Not valid username');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (515,'20102','Bio max 100 tecken');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (515,'20103','E-post max 100 tecken');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (515,'20104','Påminnelse max 100 tecken');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (515,'20105','Vänlingen ange giltig e-post');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (515,'20106','Lösenord 10 - 100 tecken');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (515,'20107','Användarnamn, lösenord och e-post är obligatoriskt');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (515,'20200','E-post finns redan');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (515,'20201','Provider finns redan');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (515,'20203','Användare finns redan');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (515,'20204','För långt värde');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (515,'20300','Användare eller lösenord hittades inte');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (515,'20301','Lösenord är inte samma');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (515,'20302','Du kan inte ta bort sista användarinställningen');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (515,'20303','Vänlingen ange användarenamn');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (515,'20304','Vänlingen ange lösenord');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (515,'20305','Användare hittades inte');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (515,'20306','Kod inte giltig');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (515,'20307','Fil typ inte tillåten');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (515,'20308','Fil storlek för stor');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (515,'20309','Text inte giltig');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (515,'20310','Text för lång');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (515,'20400','Post finns inte');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (515,'20401','Ogiltigt lösenord');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (515,'20500','Saknar latitud eller longitud');
--
-- regional_setting_translation
--
INSERT INTO app_portfolio.regional_setting_translation (regional_setting_id, language_id, text) VALUES (490,515,'Gregoriansk');
INSERT INTO app_portfolio.regional_setting_translation (regional_setting_id, language_id, text) VALUES (491,515,'Hijri');
INSERT INTO app_portfolio.regional_setting_translation (regional_setting_id, language_id, text) VALUES (481,515,'Translitterering');
INSERT INTO app_portfolio.regional_setting_translation (regional_setting_id, language_id, text) VALUES (482,515,'Translitterering, översättning');
INSERT INTO app_portfolio.regional_setting_translation (regional_setting_id, language_id, text) VALUES (483,515,'Översättning, translitterering');
INSERT INTO app_portfolio.regional_setting_translation (regional_setting_id, language_id, text) VALUES (484,515,'Översättning');
INSERT INTO app_portfolio.regional_setting_translation (regional_setting_id, language_id, text) VALUES (479,515,'Vänster till höger');
INSERT INTO app_portfolio.regional_setting_translation (regional_setting_id, language_id, text) VALUES (480,515,'Höger till vänster');