--Oracle, uncomment:
--SET DEFINE OFF;
--
-- app_category_translation
--
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(1, 515, 'Affär');
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(2, 515, 'Kommunikation');
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(3, 515, 'Utbildning');
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(4, 515, 'Finans');
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(5, 515, 'Hus & Hem');
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(6, 515, 'Produktivitet');
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(7, 515, 'Shopping');
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(8, 515, 'Spel');
--
-- app_object_item_translation
--
INSERT INTO app_portfolio.app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (0,'DIALOGUE','USERNAME',515,'Användarnamn');
INSERT INTO app_portfolio.app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (0,'DIALOGUE','PASSWORD',515,'Lösenord');
INSERT INTO app_portfolio.app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (0,'DIALOGUE','BIO',515,'Bio');
INSERT INTO app_portfolio.app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (0,'DIALOGUE','EMAIL',515,'E-post');
INSERT INTO app_portfolio.app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (0,'DIALOGUE','NEW_EMAIL',515,'Ny e-post');
INSERT INTO app_portfolio.app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (0,'DIALOGUE','PASSWORD_CONFIRM',515,'Bekräfta lösenord');
INSERT INTO app_portfolio.app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (0,'DIALOGUE','PASSWORD_REMINDER',515,'Lösenordspåminnelse');
INSERT INTO app_portfolio.app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (0,'DIALOGUE','NEW_PASSWORD_CONFIRM',515,'Nytt bekräfta lösenord');
INSERT INTO app_portfolio.app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (0,'DIALOGUE','NEW_PASSWORD',515,'Nytt lösenord');
INSERT INTO app_portfolio.app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (0,'DIALOGUE','CONFIRM_QUESTION',515,'Är du säker?');

INSERT INTO app_portfolio.app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_ASR',515,'Eftermiddag');
INSERT INTO app_portfolio.app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_ASR_IQAMAT',515,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_CALTYPE_GREGORIAN',515,'Gregoriansk');
INSERT INTO app_portfolio.app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_CALTYPE_HIJRI',515,'Hijri');
INSERT INTO app_portfolio.app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_DAY',515,'Dag');
INSERT INTO app_portfolio.app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_DHUHR',515,'Middag');
INSERT INTO app_portfolio.app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_DHUHR_IQAMAT',515,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_FAJR',515,'Gryning');
INSERT INTO app_portfolio.app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_FAJR_IQAMAT',515,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_IMSAK',515,'Imsak');
INSERT INTO app_portfolio.app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_ISHA',515,'Natt');
INSERT INTO app_portfolio.app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_ISHA_IQAMAT',515,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_MAGHRIB',515,'Solnedgång');
INSERT INTO app_portfolio.app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_MAGHRIB_IQAMAT',515,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_MIDNIGHT',515,'Midnatt');
INSERT INTO app_portfolio.app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_NOTES',515,'Noteringar');
INSERT INTO app_portfolio.app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_SUNRISE',515,'Soluppgång');
INSERT INTO app_portfolio.app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_SUNSET',515,'Solnedgång');
INSERT INTO app_portfolio.app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_ASR',515,'Asr');
INSERT INTO app_portfolio.app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_ASR_IQAMAT',515,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_DHUHR',515,'Dhuhr');
INSERT INTO app_portfolio.app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_DHUHR_IQAMAT',515,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_FAJR',515,'Fajr');
INSERT INTO app_portfolio.app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_FAJR_IQAMAT',515,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_IMSAK',515,'Imsak');
INSERT INTO app_portfolio.app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_ISHA',515,'Isha');
INSERT INTO app_portfolio.app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_ISHA_IQAMAT',515,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_MAGHRIB',515,'Maghrib');
INSERT INTO app_portfolio.app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_MAGHRIB_IQAMAT',515,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_MIDNIGHT',515,'Midnight');
INSERT INTO app_portfolio.app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_SUNRISE',515,'Shorook');
INSERT INTO app_portfolio.app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_SUNSET',515,'Sunset');
INSERT INTO app_portfolio.app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_WEEKDAY',515,'Veckodag');
INSERT INTO app_portfolio.app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (2,'REPORT','TIMETABLE_TITLE',515,'Tidtabell');
--
-- app_object_subitem_translation
--
INSERT INTO app_portfolio.app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_ASR','SETTING_SELECT_ASR_0',515,'Standard');
INSERT INTO app_portfolio.app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_ASR','SETTING_SELECT_ASR_1',515,'Hanafi');
INSERT INTO app_portfolio.app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (2,'SETTING_NAV_REGIONAL','SETTING_SELECT_CALENDARTYPE','SETTING_SELECT_CALENDARTYPE_0',515,'Gregoriansk');
INSERT INTO app_portfolio.app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (2,'SETTING_NAV_REGIONAL','SETTING_SELECT_CALENDARTYPE','SETTING_SELECT_CALENDARTYPE_1',515,'Hijri');
INSERT INTO app_portfolio.app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_HIGHLATITUDE','SETTING_SELECT_HIGHLATITUDE_0',515,'Mitten av natten');
INSERT INTO app_portfolio.app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_HIGHLATITUDE','SETTING_SELECT_HIGHLATITUDE_1',515,'Vinkel/60 av natt (rekommenderad)');
INSERT INTO app_portfolio.app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_HIGHLATITUDE','SETTING_SELECT_HIGHLATITUDE_2',515,'1/7 av natt');
INSERT INTO app_portfolio.app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_HIGHLATITUDE','SETTING_SELECT_HIGHLATITUDE_3',515,'Ingen justering');
INSERT INTO app_portfolio.app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (2,'SETTING_NAV_REGIONAL','SETTING_SELECT_REPORT_COLTITLE','SETTING_SELECT_REPORT_COLTITLE_0',515,'Translitterering');
INSERT INTO app_portfolio.app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (2,'SETTING_NAV_REGIONAL','SETTING_SELECT_REPORT_COLTITLE','SETTING_SELECT_REPORT_COLTITLE_1',515,'Translitterering, översättning');
INSERT INTO app_portfolio.app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (2,'SETTING_NAV_REGIONAL','SETTING_SELECT_REPORT_COLTITLE','SETTING_SELECT_REPORT_COLTITLE_2',515,'Översättning, translitterering');
INSERT INTO app_portfolio.app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (2,'SETTING_NAV_REGIONAL','SETTING_SELECT_REPORT_COLTITLE','SETTING_SELECT_REPORT_COLTITLE_3',515,'Översättning');
INSERT INTO app_portfolio.app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (2,'SETTING_NAV_REGIONAL','SETTING_SELECT_REPORT_DIRECTION','SETTING_SELECT_REPORT_DIRECTION_0',515,'Vänster till höger');
INSERT INTO app_portfolio.app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (2,'SETTING_NAV_REGIONAL','SETTING_SELECT_REPORT_DIRECTION','SETTING_SELECT_REPORT_DIRECTION_1',515,'Höger till vänster');
INSERT INTO app_portfolio.app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (2,'SETTING_NAV_DESIGN','SETTING_SELECT_REPORT_HIGHLIGHT_ROW','SETTING_SELECT_REPORT_HIGHLIGHT_ROW_0',515,'Inga');
INSERT INTO app_portfolio.app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (2,'SETTING_NAV_DESIGN','SETTING_SELECT_REPORT_HIGHLIGHT_ROW','SETTING_SELECT_REPORT_HIGHLIGHT_ROW_1',515,'Fredag');
INSERT INTO app_portfolio.app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (2,'SETTING_NAV_DESIGN','SETTING_SELECT_REPORT_HIGHLIGHT_ROW','SETTING_SELECT_REPORT_HIGHLIGHT_ROW_2',515,'Lördag');
INSERT INTO app_portfolio.app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (2,'SETTING_NAV_DESIGN','SETTING_SELECT_REPORT_HIGHLIGHT_ROW','SETTING_SELECT_REPORT_HIGHLIGHT_ROW_3',515,'Söndag');
INSERT INTO app_portfolio.app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (2,'SETTING_NAV_DESIGN','SETTING_SELECT_REPORT_HIGHLIGHT_ROW','SETTING_SELECT_REPORT_HIGHLIGHT_ROW_4',515,'10 dagars grupp');
INSERT INTO app_portfolio.app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_0',515,'Inga');
INSERT INTO app_portfolio.app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_1',515,'10 minuter');
INSERT INTO app_portfolio.app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_2',515,'15 minuter');
INSERT INTO app_portfolio.app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_3',515,'20 minuter');
INSERT INTO app_portfolio.app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_4',515,'25 minuter');
INSERT INTO app_portfolio.app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_5',515,'30 minuter');
INSERT INTO app_portfolio.app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_6',515,'Nästa timme');
INSERT INTO app_portfolio.app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_7',515,'Nästa timme + 15 minuter');
INSERT INTO app_portfolio.app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_8',515,'Nästa timme + 30 minuter');
INSERT INTO app_portfolio.app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_0',515,'Inga');
INSERT INTO app_portfolio.app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_1',515,'10 minuter');
INSERT INTO app_portfolio.app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_2',515,'15 minuter');
INSERT INTO app_portfolio.app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_3',515,'20 minuter');
INSERT INTO app_portfolio.app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_4',515,'25 minuter');
INSERT INTO app_portfolio.app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_5',515,'30 minuter');
INSERT INTO app_portfolio.app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_6',515,'Nästa timme');
INSERT INTO app_portfolio.app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_7',515,'Nästa timme + 15 minuter');
INSERT INTO app_portfolio.app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_8',515,'Nästa timme + 30 minuter');
INSERT INTO app_portfolio.app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_0',515,'Inga');
INSERT INTO app_portfolio.app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_1',515,'10 minuter');
INSERT INTO app_portfolio.app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_2',515,'15 minuter');
INSERT INTO app_portfolio.app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_3',515,'20 minuter');
INSERT INTO app_portfolio.app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_4',515,'25 minuter');
INSERT INTO app_portfolio.app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_5',515,'30 minuter');
INSERT INTO app_portfolio.app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_6',515,'Nästa timme');
INSERT INTO app_portfolio.app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_7',515,'Nästa timme + 15 minuter');
INSERT INTO app_portfolio.app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_8',515,'Nästa timme + 30 minuter');
INSERT INTO app_portfolio.app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_0',515,'Inga');
INSERT INTO app_portfolio.app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_1',515,'10 minuter');
INSERT INTO app_portfolio.app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_2',515,'15 minuter');
INSERT INTO app_portfolio.app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_3',515,'20 minuter');
INSERT INTO app_portfolio.app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_4',515,'25 minuter');
INSERT INTO app_portfolio.app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_5',515,'30 minuter');
INSERT INTO app_portfolio.app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_6',515,'Nästa timme');
INSERT INTO app_portfolio.app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_7',515,'Nästa timme + 15 minuter');
INSERT INTO app_portfolio.app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_8',515,'Nästa timme + 30 minuter');
INSERT INTO app_portfolio.app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_0',515,'Inga');
INSERT INTO app_portfolio.app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_1',515,'10 minuter');
INSERT INTO app_portfolio.app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_2',515,'15 minuter');
INSERT INTO app_portfolio.app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_3',515,'20 minuter');
INSERT INTO app_portfolio.app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_4',515,'25 minuter');
INSERT INTO app_portfolio.app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_5',515,'30 minuter');
INSERT INTO app_portfolio.app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_6',515,'Nästa timme');
INSERT INTO app_portfolio.app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_7',515,'Nästa timme + 15 minuter');
INSERT INTO app_portfolio.app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_8',515,'Nästa timme + 30 minuter');
INSERT INTO app_portfolio.app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (2,'SETTING_NAV_REGIONAL','SETTING_SELECT_REPORT_LOCALE_SECOND','SETTING_SELECT_REPORT_LOCALE_SECOND_0',515,'Inget');
INSERT INTO app_portfolio.app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_SHOW_FAST_START_END','SETTING_SELECT_REPORT_SHOW_FAST_START_END_0',515,'Nej');
INSERT INTO app_portfolio.app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_SHOW_FAST_START_END','SETTING_SELECT_REPORT_SHOW_FAST_START_END_1',515,'Fajr & Mahgrib');
INSERT INTO app_portfolio.app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_SHOW_FAST_START_END','SETTING_SELECT_REPORT_SHOW_FAST_START_END_2',515,'Imsak & Mahgrib');
INSERT INTO app_portfolio.app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_SHOW_FAST_START_END','SETTING_SELECT_REPORT_SHOW_FAST_START_END_3',515,'Fajr & Isha');
INSERT INTO app_portfolio.app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_SHOW_FAST_START_END','SETTING_SELECT_REPORT_SHOW_FAST_START_END_4',515,'Imsak & Isha');
INSERT INTO app_portfolio.app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_TIMEFORMAT','SETTING_SELECT_TIMEFORMAT_0',515,'12-tim utan suffix');
INSERT INTO app_portfolio.app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_TIMEFORMAT','SETTING_SELECT_TIMEFORMAT_1',515,'24-tim');
INSERT INTO app_portfolio.app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_TIMEFORMAT','SETTING_SELECT_TIMEFORMAT_2',515,'12-tim med suffix');
--
-- app_object_translation
--
INSERT INTO app_portfolio.app_object_translation (app_id, object_name, language_id, text) VALUES (2,'APP_DESCRIPTION',515,'Ensidesprogram för progressiv webbapp (PWA) (SPA)');
INSERT INTO app_portfolio.app_object_translation (app_id, object_name, language_id, text) VALUES (3,'APP_DESCRIPTION',515,'Enkel app för att visa datamodell och hur man integrerar en app i app plattformen');
--
-- language_translation
--
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (1,515,'abchaziska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (2,515,'acehnesiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (3,515,'acholi');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (4,515,'adangme');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (5,515,'adygeiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (6,515,'afar');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (7,515,'afrihili');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (8,515,'afrikaans');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (9,515,'aghem');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (10,515,'ainu');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (11,515,'akan');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (12,515,'akkadiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (13,515,'bakossi');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (14,515,'Alabama');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (15,515,'albanska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (16,515,'aleutiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (17,515,'algerisk arabiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (19,515,'amerikanskt teckenspråk');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (20,515,'amhariska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (21,515,'fornegyptiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (22,515,'forngrekiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (23,515,'angika');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (24,515,'Ao Naga');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (25,515,'arabiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (26,515,'aragonesiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (27,515,'arameiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (28,515,'araoniska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (29,515,'arapaho');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (30,515,'arawakiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (31,515,'armeniska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (32,515,'arumänska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (33,515,'frankoprovensalska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (34,515,'assamesiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (35,515,'asturiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (36,515,'asu');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (37,515,'atsam');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (40,515,'avariska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (41,515,'avestiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (42,515,'awadhi');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (43,515,'aymara');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (44,515,'azerbajdzjanska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (45,515,'bagada');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (46,515,'bafia');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (47,515,'bafut');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (48,515,'bakhtiari');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (49,515,'balinesiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (50,515,'baluchiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (51,515,'bambara');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (52,515,'bamunska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (53,515,'banjariska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (54,515,'basa');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (55,515,'basjkiriska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (56,515,'baskiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (57,515,'Batak Toba');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (58,515,'bayerska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (59,515,'beja');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (60,515,'vitryska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (61,515,'bemba');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (62,515,'bena');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (63,515,'bengali');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (64,515,'betawiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (65,515,'bhojpuri');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (66,515,'bikol');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (67,515,'bini');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (68,515,'bishnupriya');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (69,515,'bislama');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (70,515,'blin');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (71,515,'blissymboler');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (72,515,'bodo');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (73,515,'bosniska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (74,515,'brahuiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (75,515,'braj');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (77,515,'bretonska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (79,515,'buginesiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (80,515,'bulgariska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (81,515,'boulou');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (82,515,'burjätiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (83,515,'burmesiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (84,515,'caddo');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (85,515,'cajun-franska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (88,515,'kantonesiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (89,515,'Capiznon');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (90,515,'karibiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (91,515,'katalanska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (92,515,'cayuga');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (93,515,'cebuano');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (94,515,'centralmarockansk tamazight');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (95,515,'Central Dusun');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (96,515,'soranisk kurdiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (97,515,'Central Yupik');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (98,515,'Chad-arabiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (99,515,'chagatai');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (100,515,'chamorro');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (101,515,'tjetjenska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (102,515,'cherokesiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (103,515,'cheyenne');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (104,515,'chibcha');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (105,515,'chiga');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (106,515,'Chimborazo-höglandskichwa');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (107,515,'kinesiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (108,515,'chinook');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (109,515,'chipewyan');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (110,515,'choctaw');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (111,515,'kyrkslaviska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (112,515,'chuukesiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (113,515,'tjuvasjiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (114,515,'klassisk newariska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (115,515,'klassisk syriska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (116,515,'kölniska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (117,515,'shimaoré');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (118,515,'Kongo-swahili');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (119,515,'koptiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (120,515,'korniska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (121,515,'korsikanska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (122,515,'cree');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (123,515,'muskogee');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (124,515,'krimtatariska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (125,515,'kroatiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (126,515,'tjeckiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (127,515,'dakota');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (128,515,'danska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (129,515,'darginska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (130,515,'dazaga');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (131,515,'delaware');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (132,515,'dinka');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (133,515,'divehi');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (134,515,'dogri');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (135,515,'dogrib');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (136,515,'duala');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (137,515,'nederländska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (138,515,'dyula');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (139,515,'bhutanesiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (140,515,'östfrisiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (141,515,'efik');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (142,515,'egyptisk arabiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (143,515,'ekajuk');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (144,515,'elamitiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (145,515,'embu');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (146,515,'emiliska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (147,515,'engelska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (148,515,'erjya');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (149,515,'esperanto');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (150,515,'estniska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (153,515,'ewe');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (154,515,'ewondo');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (155,515,'Extremaduran');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (156,515,'fang');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (157,515,'fanti');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (158,515,'färöiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (159,515,'Fiji-hindi');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (160,515,'fijianska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (161,515,'filippinska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (162,515,'finska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (164,515,'fonspråket');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (165,515,'Frafra');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (166,515,'franska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (167,515,'friulianska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (168,515,'fulani');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (169,515,'gã');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (170,515,'gagauziska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (171,515,'galiciska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (172,515,'gan');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (173,515,'luganda');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (174,515,'gayo');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (175,515,'gbaya');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (176,515,'etiopiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (177,515,'georgiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (178,515,'tyska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (179,515,'gegiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (180,515,'ghomala');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (181,515,'gilaki');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (182,515,'gilbertiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (183,515,'Goa-konkani');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (184,515,'gondi');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (185,515,'gorontalo');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (186,515,'gotiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (187,515,'grebo');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (188,515,'grekiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (189,515,'guaraní');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (190,515,'gujarati');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (191,515,'gusii');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (192,515,'gwichin');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (193,515,'haida');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (194,515,'haitiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (195,515,'hakka');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (196,515,'hausa');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (197,515,'hawaiiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (198,515,'hebreiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (199,515,'herero');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (200,515,'hiligaynon');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (201,515,'hindi');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (202,515,'hirimotu');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (203,515,'hettitiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (204,515,'hmongspråk');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (205,515,'ungerska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (206,515,'hupa');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (207,515,'ibanska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (208,515,'ibibio');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (209,515,'isländska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (210,515,'ido');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (211,515,'igbo');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (212,515,'iloko');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (213,515,'enaresamiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (214,515,'indonesiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (215,515,'ingriska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (216,515,'ingusjiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (217,515,'interlingua');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (218,515,'interlingue');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (219,515,'inuktitut');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (220,515,'inupiak');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (221,515,'iriska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (222,515,'italienska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (223,515,'jamaikansk engelsk kreol');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (224,515,'japanska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (225,515,'javanesiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (226,515,'jju');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (227,515,'jola-fonyi');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (228,515,'judisk arabiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (229,515,'judisk persiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (230,515,'jylländska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (231,515,'kabardinska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (232,515,'kapverdiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (233,515,'kabyliska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (234,515,'kachin');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (235,515,'Kaingang');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (236,515,'mkako');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (237,515,'grönländska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (238,515,'kalenjin');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (239,515,'kalmuckiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (240,515,'kamba');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (241,515,'kanembu');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (242,515,'kannada');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (243,515,'kanuri');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (244,515,'karakalpakiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (245,515,'karachay-balkar');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (246,515,'karelska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (247,515,'kashmiriska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (248,515,'kasjubiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (249,515,'kawi');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (250,515,'kazakiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (251,515,'Kenyang');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (252,515,'khasi');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (253,515,'kambodjanska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (254,515,'khotanesiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (255,515,'khowar');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (256,515,'kikuyu');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (257,515,'kimbundu');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (258,515,'Kinaray-a');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (259,515,'kinjarwanda');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (260,515,'Kirmanjki');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (261,515,'klingonska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (262,515,'bamekon');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (263,515,'kome');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (264,515,'komi-permjakiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (265,515,'kikongo');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (266,515,'konkani');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (267,515,'koreanska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (268,515,'koro');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (269,515,'kosreanska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (270,515,'kotava');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (271,515,'Timbuktu-songhoy');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (272,515,'Gao-songhay');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (273,515,'kpelle');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (274,515,'Krio');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (275,515,'kuanyama');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (276,515,'kumykiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (277,515,'kurdiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (278,515,'kurukh');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (279,515,'kutenaj');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (280,515,'kwasio');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (281,515,'kirgisiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (282,515,'kʼicheʼ');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (283,515,'ladino');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (284,515,'lahnda');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (285,515,'lakota');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (286,515,'lamba');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (287,515,'langi');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (288,515,'laotiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (289,515,'lettgalliska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (290,515,'latin');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (292,515,'lettiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (293,515,'Laz');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (294,515,'lezghien');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (295,515,'liguriska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (296,515,'limburgiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (297,515,'lingala');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (298,515,'Lingua Franca Nova');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (299,515,'Literary Chinese');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (300,515,'litauiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (301,515,'livoniska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (302,515,'lojban');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (303,515,'lombardiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (304,515,'lågtyska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (305,515,'lågsilesiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (306,515,'lågsorbiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (307,515,'lozi');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (308,515,'luba-katanga');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (309,515,'luba-lulua');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (310,515,'luiseño');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (311,515,'lulesamiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (312,515,'lunda');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (313,515,'luo');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (314,515,'luxemburgiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (315,515,'luhya');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (316,515,'maba');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (317,515,'makedonska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (318,515,'kimashami');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (319,515,'maduresiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (320,515,'mafa');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (321,515,'magahi');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (322,515,'Main-frankiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (323,515,'maithili');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (324,515,'makasar');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (325,515,'makhuwa-meetto');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (326,515,'makonde');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (327,515,'malagassiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (328,515,'malajiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (329,515,'malayalam');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (330,515,'maltesiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (331,515,'manchuriska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (332,515,'mandar');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (333,515,'mande');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (334,515,'manipuri');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (335,515,'manx');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (336,515,'maori');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (337,515,'araukanska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (338,515,'marathi');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (339,515,'mariska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (340,515,'marshalliska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (341,515,'marwari');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (342,515,'massajiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (343,515,'mazanderani');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (344,515,'bagangte');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (345,515,'mende');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (346,515,'Mentawai');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (347,515,'meru');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (348,515,'meta’');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (350,515,'mi’kmaq');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (351,515,'medelnederländska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (352,515,'medelengelska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (353,515,'medelfranska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (354,515,'medelhögtyska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (355,515,'medeliriska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (356,515,'min nan');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (357,515,'minangkabau');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (358,515,'Mingrelian');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (359,515,'mirandesiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (360,515,'lushai');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (362,515,'mohawk');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (363,515,'moksja');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (365,515,'mongo');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (366,515,'mongoliska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (367,515,'mauritansk kreol');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (368,515,'marockansk arabiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (369,515,'mossi');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (370,515,'flera språk');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (371,515,'mundang');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (372,515,'Muslim Tat');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (373,515,'myene');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (374,515,'nama');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (375,515,'nauru');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (376,515,'navaho');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (377,515,'ndonga');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (378,515,'napolitanska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (379,515,'nepalesiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (380,515,'newariska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (381,515,'ngambay');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (382,515,'bamileké-ngiemboon');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (383,515,'ngomba');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (384,515,'Nheengatu');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (385,515,'nias');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (386,515,'niueanska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (387,515,'inget språkligt innehåll');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (388,515,'nogai');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (389,515,'nordndebele');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (390,515,'nordfrisiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (391,515,'nordsamiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (392,515,'nordsotho');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (393,515,'norska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (394,515,'norskt bokmål');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (395,515,'nynorska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (396,515,'Novial');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (397,515,'nuer');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (398,515,'nyamwezi');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (399,515,'nyanja');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (400,515,'nyankole');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (401,515,'nyasatonganska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (402,515,'nyoro');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (403,515,'nzima');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (404,515,'n-kå');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (405,515,'occitanska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (406,515,'odjibwa');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (407,515,'fornengelska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (408,515,'fornfranska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (409,515,'fornhögtyska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (410,515,'forniriska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (411,515,'fornnordiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (412,515,'fornpersiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (413,515,'fornprovensalska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (414,515,'oriya');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (415,515,'oromo');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (416,515,'osage');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (417,515,'ossetiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (418,515,'ottomanska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (419,515,'medelpersiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (420,515,'Pfalz-tyska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (421,515,'palau');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (422,515,'pali');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (423,515,'pampanga');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (424,515,'pangasinan');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (425,515,'papiamento');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (426,515,'afghanska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (427,515,'Pennsylvaniatyska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (428,515,'persiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (429,515,'feniciska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (430,515,'pikardiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (431,515,'piemontesiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (432,515,'mennonitisk lågtyska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (433,515,'ponape');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (434,515,'polska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (435,515,'pontiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (436,515,'portugisiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (437,515,'fornpreussiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (438,515,'punjabi');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (439,515,'quechua');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (440,515,'rajasthani');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (441,515,'rapanui');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (442,515,'rarotonganska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (443,515,'riffianska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (444,515,'romagnol');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (445,515,'rumänska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (446,515,'rätoromanska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (447,515,'romani');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (448,515,'rombo');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (449,515,'rot');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (450,515,'rotumänska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (451,515,'rovianska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (452,515,'rundi');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (453,515,'ryska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (454,515,'rusyn');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (455,515,'rwa');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (456,515,'saho');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (457,515,'jakutiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (458,515,'samaritanska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (459,515,'samburu');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (460,515,'samoanska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (461,515,'samogitiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (462,515,'sandawe');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (463,515,'sango');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (464,515,'sangu');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (465,515,'sanskrit');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (466,515,'santali');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (467,515,'sardiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (468,515,'sasak');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (469,515,'sassaresisk sardiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (470,515,'saterfrisiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (471,515,'saurashtra');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (472,515,'skotska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (473,515,'skotsk gäliska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (474,515,'Selayar');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (475,515,'selkup');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (476,515,'sena');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (477,515,'seneca');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (478,515,'serbiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (479,515,'serbokroatiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (480,515,'serer');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (481,515,'Seri');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (482,515,'kisambaa');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (483,515,'shan');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (484,515,'shona');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (485,515,'szezuan i');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (486,515,'sicilianska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (487,515,'sidamo');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (488,515,'siksika');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (489,515,'silesiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (491,515,'sindhi');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (492,515,'singalesiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (493,515,'skoltsamiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (494,515,'slavej');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (495,515,'slovakiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (496,515,'slovenska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (497,515,'lusoga');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (498,515,'sogdiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (499,515,'somaliska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (500,515,'soninke');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (501,515,'sydazerbadjanska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (502,515,'sydndebele');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (503,515,'sydaltaiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (504,515,'sydsamiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (505,515,'sydsotho');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (506,515,'spanska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (507,515,'sranan tongo');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (508,515,'marockansk standard-tamazight');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (509,515,'sukuma');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (510,515,'sumeriska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (511,515,'sundanesiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (512,515,'susu');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (513,515,'swahili');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (514,515,'swati');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (515,515,'svenska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (517,515,'schweizertyska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (519,515,'syriska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (520,515,'tachelhit');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (521,515,'tagalog');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (522,515,'tahitiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (523,515,'taita');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (524,515,'tadzjikiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (525,515,'talysh');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (526,515,'tamashek');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (527,515,'tamil');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (528,515,'taroko');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (529,515,'tasawaq');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (530,515,'tatariska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (531,515,'telugiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (532,515,'tereno');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (533,515,'teso');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (534,515,'tetum');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (535,515,'thailändska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (536,515,'tibetanska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (537,515,'tigré');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (538,515,'tigrinja');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (539,515,'temne');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (540,515,'tivi');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (541,515,'tlingit');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (542,515,'tok pisin');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (543,515,'tokelauiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (544,515,'tonganska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (545,515,'meänkieli');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (547,515,'Tsakhur');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (548,515,'tsakodiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (549,515,'tsimshian');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (550,515,'tsonga');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (551,515,'tswana');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (552,515,'tulu');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (553,515,'tumbuka');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (554,515,'tunisisk arabiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (555,515,'turkiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (556,515,'turkmeniska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (557,515,'Turoyo');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (558,515,'tuvaluanska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (559,515,'tuviniska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (560,515,'twi');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (561,515,'tyap');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (562,515,'udmurtiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (563,515,'ugaritiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (564,515,'ukrainska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (565,515,'umbundu');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (566,515,'obestämt språk');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (567,515,'högsorbiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (568,515,'urdu');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (569,515,'uiguriska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (570,515,'uzbekiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (571,515,'vaj');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (572,515,'venda');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (573,515,'venetianska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (574,515,'veps');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (575,515,'vietnamesiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (576,515,'volapük');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (577,515,'võru');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (578,515,'votiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (579,515,'vunjo');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (580,515,'vallonska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (581,515,'walsertyska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (582,515,'waray');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (583,515,'Warlpiri');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (584,515,'washo');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (585,515,'Wayuu');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (586,515,'walesiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (587,515,'västflamländska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (588,515,'västfrisiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (589,515,'västmariska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (590,515,'walamo');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (591,515,'wolof');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (592,515,'wu');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (593,515,'xhosa');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (594,515,'xiang');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (595,515,'yangben');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (596,515,'kiyao');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (597,515,'japetiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (598,515,'bamileké-jemba');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (599,515,'jiddisch');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (600,515,'yoruba');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (601,515,'zapotek');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (602,515,'zarma');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (603,515,'zazaiska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (604,515,'zeeländska');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (605,515,'zenaga');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (606,515,'zhuang');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (607,515,'zoroastrisk dari');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (608,515,'zulu');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (609,515,'zuni');
--
-- message_translation
--
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (515,'20100','Username 5 - 100 characters');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (515,'20101','Not valid username');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (515,'20102','Bio max 100 tecken');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (515,'20103','E-post max 100 tecken');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (515,'20104','Påminnelse max 100 tecken');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (515,'20105','Vänlingen ange giltig e-post');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (515,'20106','Lösenord 10 - 100 tecken');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (515,'20107','Användarnamn, lösenord och e-post är obligatoriskt');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (515,'20200','E-post finns redan');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (515,'20201','Provider finns redan');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (515,'20203','Användare finns redan');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (515,'20204','För långt värde');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (515,'20300','Användare eller lösenord hittades inte');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (515,'20301','Lösenord är inte samma');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (515,'20302','Du kan inte ta bort sista användarinställningen');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (515,'20303','Vänlingen ange användarenamn');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (515,'20304','Vänlingen ange lösenord');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (515,'20305','Användare hittades inte');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (515,'20306','Kod inte giltig');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (515,'20307','Fil typ inte tillåten');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (515,'20308','Fil storlek för stor');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (515,'20309','Text inte giltig');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (515,'20310','Text för lång');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (515,'20400','Post finns inte');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (515,'20401','Ogiltigt lösenord');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (515,'20500','Saknar latitud eller longitud');
--
-- regional_setting_translation
--
INSERT INTO app_portfolio.regional_setting_translation (regional_setting_id, language_id, text) VALUES (490,515,'Gregoriansk');
INSERT INTO app_portfolio.regional_setting_translation (regional_setting_id, language_id, text) VALUES (491,515,'Hijri');
INSERT INTO app_portfolio.regional_setting_translation (regional_setting_id, language_id, text) VALUES (481,515,'Translitterering');
INSERT INTO app_portfolio.regional_setting_translation (regional_setting_id, language_id, text) VALUES (482,515,'Translitterering, översättning');
INSERT INTO app_portfolio.regional_setting_translation (regional_setting_id, language_id, text) VALUES (483,515,'Översättning, translitterering');
INSERT INTO app_portfolio.regional_setting_translation (regional_setting_id, language_id, text) VALUES (484,515,'Översättning');
INSERT INTO app_portfolio.regional_setting_translation (regional_setting_id, language_id, text) VALUES (479,515,'Vänster till höger');
INSERT INTO app_portfolio.regional_setting_translation (regional_setting_id, language_id, text) VALUES (480,515,'Höger till vänster');