--Oracle, uncomment:
--SET DEFINE OFF;
--
-- app_category_translation
--
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(1, 531, 'Business');
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(2, 531, 'Communications');
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(3, 531, 'Education');
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(4, 531, 'Finance');
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(5, 531, 'House & Home');
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(6, 531, 'Productivity');
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(7, 531, 'Shopping');
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(8, 531, 'Game');
--
-- app_object_item_translation
--
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'DIALOGUE','USERNAME',531,'Username');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'DIALOGUE','PASSWORD',531,'Password');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'DIALOGUE','BIO',531,'Bio');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'DIALOGUE','EMAIL',531,'Email');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'DIALOGUE','NEW_EMAIL',531,'New email');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'DIALOGUE','PASSWORD_CONFIRM',531,'Password confirm');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'DIALOGUE','PASSWORD_REMINDER',531,'Password reminder');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'DIALOGUE','NEW_PASSWORD_CONFIRM',531,'New password confirm');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'DIALOGUE','NEW_PASSWORD',531,'New password');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'DIALOGUE','CONFIRM_QUESTION',531,'Are you sure?');


INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_ASR',531,'Afternoon');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_ASR_IQAMAT',531,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_CALTYPE_GREGORIAN',531,'Gregorian');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_CALTYPE_HIJRI',531,'Hijri');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_DAY',531,'Day');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_DHUHR',531,'Noon');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_DHUHR_IQAMAT',531,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_FAJR',531,'Dawn');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_FAJR_IQAMAT',531,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_IMSAK',531,'Imsak');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_ISHA',531,'Night');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_ISHA_IQAMAT',531,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_MAGHRIB',531,'Sunset');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_MAGHRIB_IQAMAT',531,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_MIDNIGHT',531,'Midnight');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_NOTES',531,'Notes');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_SUNRISE',531,'Sunrise');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_SUNSET',531,'Sunset');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_ASR',531,'Asr');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_ASR_IQAMAT',531,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_DHUHR',531,'Dhuhr');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_DHUHR_IQAMAT',531,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_FAJR',531,'Fajr');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_FAJR_IQAMAT',531,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_IMSAK',531,'Imsak');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_ISHA',531,'Isha');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_ISHA_IQAMAT',531,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_MAGHRIB',531,'Maghrib');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_MAGHRIB_IQAMAT',531,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_MIDNIGHT',531,'Midnight');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_SUNRISE',531,'Shorook');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_SUNSET',531,'Sunset');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_WEEKDAY',531,'Weekday');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_id, app_object_item_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','TIMETABLE_TITLE',531,'Timetable');
--
-- app_object_subitem_translation
--
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_ASR','SETTING_SELECT_ASR_0',531,'Standard');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_ASR','SETTING_SELECT_ASR_1',531,'Hanafi');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_REGIONAL','SETTING_SELECT_CALENDARTYPE','SETTING_SELECT_CALENDARTYPE_0',531,'Gregorian');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_REGIONAL','SETTING_SELECT_CALENDARTYPE','SETTING_SELECT_CALENDARTYPE_1',531,'Hijri');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_HIGHLATITUDE','SETTING_SELECT_HIGHLATITUDE_0',531,'Middle of night');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_HIGHLATITUDE','SETTING_SELECT_HIGHLATITUDE_1',531,'Angle/60th of night (recommended)');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_HIGHLATITUDE','SETTING_SELECT_HIGHLATITUDE_2',531,'1/7th of night');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_HIGHLATITUDE','SETTING_SELECT_HIGHLATITUDE_3',531,'No adjustment');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_REGIONAL','SETTING_SELECT_REPORT_COLTITLE','SETTING_SELECT_REPORT_COLTITLE_0',531,'Transliteration');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_REGIONAL','SETTING_SELECT_REPORT_COLTITLE','SETTING_SELECT_REPORT_COLTITLE_1',531,'Transliteration, translation');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_REGIONAL','SETTING_SELECT_REPORT_COLTITLE','SETTING_SELECT_REPORT_COLTITLE_2',531,'Translation, transliteration');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_REGIONAL','SETTING_SELECT_REPORT_COLTITLE','SETTING_SELECT_REPORT_COLTITLE_3',531,'Translation');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_REGIONAL','SETTING_SELECT_REPORT_DIRECTION','SETTING_SELECT_REPORT_DIRECTION_0',531,'Left to right');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_REGIONAL','SETTING_SELECT_REPORT_DIRECTION','SETTING_SELECT_REPORT_DIRECTION_1',531,'Right to left');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_DESIGN','SETTING_SELECT_REPORT_HIGHLIGHT_ROW','SETTING_SELECT_REPORT_HIGHLIGHT_ROW_0',531,'None');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_DESIGN','SETTING_SELECT_REPORT_HIGHLIGHT_ROW','SETTING_SELECT_REPORT_HIGHLIGHT_ROW_1',531,'Friday');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_DESIGN','SETTING_SELECT_REPORT_HIGHLIGHT_ROW','SETTING_SELECT_REPORT_HIGHLIGHT_ROW_2',531,'Saturday');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_DESIGN','SETTING_SELECT_REPORT_HIGHLIGHT_ROW','SETTING_SELECT_REPORT_HIGHLIGHT_ROW_3',531,'Sunday');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_DESIGN','SETTING_SELECT_REPORT_HIGHLIGHT_ROW','SETTING_SELECT_REPORT_HIGHLIGHT_ROW_4',531,'10 days groups');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_0',531,'None');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_1',531,'10 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_2',531,'15 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_3',531,'20 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_4',531,'25 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_5',531,'30 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_6',531,'Next hour');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_7',531,'Next hour + 15 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_8',531,'Next hour + 30 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_0',531,'None');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_1',531,'10 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_2',531,'15 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_3',531,'20 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_4',531,'25 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_5',531,'30 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_6',531,'Next hour');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_7',531,'Next hour + 15 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_8',531,'Next hour + 30 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_0',531,'None');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_1',531,'10 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_2',531,'15 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_3',531,'20 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_4',531,'25 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_5',531,'30 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_6',531,'Next hour');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_7',531,'Next hour + 15 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_8',531,'Next hour + 30 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_0',531,'None');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_1',531,'10 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_2',531,'15 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_3',531,'20 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_4',531,'25 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_5',531,'30 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_6',531,'Next hour');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_7',531,'Next hour + 15 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_8',531,'Next hour + 30 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_0',531,'None');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_1',531,'10 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_2',531,'15 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_3',531,'20 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_4',531,'25 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_5',531,'30 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_6',531,'Next hour');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_7',531,'Next hour + 15 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_8',531,'Next hour + 30 minutes');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_REGIONAL','SETTING_SELECT_REPORT_LOCALE_SECOND','SETTING_SELECT_REPORT_LOCALE_SECOND_0',531,'None');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_SHOW_FAST_START_END','SETTING_SELECT_REPORT_SHOW_FAST_START_END_0',531,'No');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_SHOW_FAST_START_END','SETTING_SELECT_REPORT_SHOW_FAST_START_END_1',531,'Fajr & Mahgrib');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_SHOW_FAST_START_END','SETTING_SELECT_REPORT_SHOW_FAST_START_END_2',531,'Imsak & Mahgrib');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_SHOW_FAST_START_END','SETTING_SELECT_REPORT_SHOW_FAST_START_END_3',531,'Fajr & Isha');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_SHOW_FAST_START_END','SETTING_SELECT_REPORT_SHOW_FAST_START_END_4',531,'Imsak & Isha');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_TIMEFORMAT','SETTING_SELECT_TIMEFORMAT_0',531,'12-hour without suffix');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_TIMEFORMAT','SETTING_SELECT_TIMEFORMAT_1',531,'24-hour');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_id, app_object_item_subitem_object_name, app_object_item_subitem_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'SETTING_NAV_PRAYER','SETTING_SELECT_TIMEFORMAT','SETTING_SELECT_TIMEFORMAT_2',531,'12-hour with suffix');
--
-- app_object_translation
--
INSERT INTO app_portfolio.app_object_translation (app_object_app_id, app_object_object_name, language_id, text) VALUES (2,'APP_DESCRIPTION',531,'Progressive web app (PWA) single page application (SPA)');
INSERT INTO app_portfolio.app_object_translation (app_object_app_id, app_object_object_name, language_id, text) VALUES (3,'APP_DESCRIPTION',531,'Simple app to display datamodel and how to integrate an app in the app platform');
--
-- message_translation
--
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (531,'20100','Username 5 - 100 characters');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (531,'20101','Not valid username');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (531,'20102','Bio max 100 characters');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (531,'20103','Email max 100 characters');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (531,'20104','Reminder max 100 characters');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (531,'20105','Not valid email');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (531,'20106','Password 10 - 100 characters');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (531,'20107','Username, password and email are required');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (531,'20200','Email already exist');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (531,'20201','Provider already exist');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (531,'20203','Username already exist');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (531,'20204','Too long value');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (531,'20300','Username or password not found');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (531,'20301','Password not the same');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (531,'20302','You can not delete last user setting');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (531,'20303','Please enter username');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (531,'20304','Please enter password');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (531,'20305','User not found');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (531,'20306','Code not valid');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (531,'20307','File type not allowed');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (531,'20308','File size too large');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (531,'20309','Text not valid');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (531,'20310','Text too long');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (531,'20400','Record not found');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (531,'20401','Invalid password');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (531,'20500','Missing latitude or longitude');
--
-- regional_setting_translation
--
INSERT INTO app_portfolio.regional_setting_translation (regional_setting_id, language_id, text) VALUES (490,531,'Gregorian');
INSERT INTO app_portfolio.regional_setting_translation (regional_setting_id, language_id, text) VALUES (491,531,'Hijri');
INSERT INTO app_portfolio.regional_setting_translation (regional_setting_id, language_id, text) VALUES (481,531,'Transliteration');
INSERT INTO app_portfolio.regional_setting_translation (regional_setting_id, language_id, text) VALUES (482,531,'Transliteration, translation');
INSERT INTO app_portfolio.regional_setting_translation (regional_setting_id, language_id, text) VALUES (483,531,'Translation, transliteration');
INSERT INTO app_portfolio.regional_setting_translation (regional_setting_id, language_id, text) VALUES (484,531,'Translation');
INSERT INTO app_portfolio.regional_setting_translation (regional_setting_id, language_id, text) VALUES (479,531,'Left to right');
INSERT INTO app_portfolio.regional_setting_translation (regional_setting_id, language_id, text) VALUES (480,531,'Right to left');
