--Oracle, uncomment:
--SET DEFINE OFF;
--
-- app_category_translation
--
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(1, 546, '商');
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(2, 546, '通信');
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(3, 546, '教育');
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(4, 546, '金融');
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(5, 546, '房子和家');
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(6, 546, '生產力');
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(7, 546, '購物');
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(8, 546, '遊戲');
--
-- app_object_item_translation
--
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'COMMON','USERNAME',546,'用戶名');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'COMMON','PASSWORD',546,'密碼');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'COMMON','BIO',546,'傳');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'COMMON','EMAIL',546,'電子郵件');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'COMMON','NEW_EMAIL',546,'新電子郵件');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'COMMON','PASSWORD_CONFIRM',546,'確認密碼');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'COMMON','PASSWORD_REMINDER',546,'密碼提醒');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'COMMON','NEW_PASSWORD_CONFIRM',546,'新的確認密碼');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'COMMON','NEW_PASSWORD',546,'新密碼');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (0,'COMMON','CONFIRM_QUESTION',546,'你確定嗎？');

INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_ASR',546,'下午');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_ASR_IQAMAT',546,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_CALTYPE_GREGORIAN',546,'格里高利安');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_CALTYPE_HIJRI',546,'Hijri');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_DAY',546,'天');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_DHUHR',546,'中午');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_DHUHR_IQAMAT',546,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_FAJR',546,'黎明');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_FAJR_IQAMAT',546,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_IMSAK',546,'Imsak');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_ISHA',546,'晚');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_ISHA_IQAMAT',546,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_MAGHRIB',546,'日落');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_MAGHRIB_IQAMAT',546,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_MIDNIGHT',546,'午夜');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_NOTES',546,'筆記');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_SUNRISE',546,'日出');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_SUNSET',546,'日落');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_ASR',546,'Asr');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_ASR_IQAMAT',546,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_DHUHR',546,'Dhuhr');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_DHUHR_IQAMAT',546,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_FAJR',546,'Fajr');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_FAJR_IQAMAT',546,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_IMSAK',546,'Imsak');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_ISHA',546,'Isha');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_ISHA_IQAMAT',546,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_MAGHRIB',546,'Maghrib');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_MAGHRIB_IQAMAT',546,'Iqamat');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_MIDNIGHT',546,'Midnight');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_SUNRISE',546,'Shorook');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_TRANSLITERATION_SUNSET',546,'Sunset');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','COLTITLE_WEEKDAY',546,'平日');
INSERT INTO app_portfolio.app_object_item_translation (app_object_item_app_object_app_id, app_object_item_app_object_object_name, app_object_item_object_item_name, language_id, text) VALUES (2,'REPORT','TIMETABLE_TITLE',546,'時間表');
--
-- app_object_subitem_translation
--
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_ASR','SETTING_SELECT_ASR_0',546,'標準');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_ASR','SETTING_SELECT_ASR_1',546,'Hanafi');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_CALENDARTYPE','SETTING_SELECT_CALENDARTYPE_0',546,'格里高利安');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_CALENDARTYPE','SETTING_SELECT_CALENDARTYPE_1',546,'Hijri');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_HIGHLATITUDE','SETTING_SELECT_HIGHLATITUDE_0',546,'午夜');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_HIGHLATITUDE','SETTING_SELECT_HIGHLATITUDE_1',546,'角度/夜間60度（推薦）');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_HIGHLATITUDE','SETTING_SELECT_HIGHLATITUDE_2',546,'晚上1/7');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_HIGHLATITUDE','SETTING_SELECT_HIGHLATITUDE_3',546,'沒有調整');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_COLTITLE','SETTING_SELECT_REPORT_COLTITLE_0',546,'音譯');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_COLTITLE','SETTING_SELECT_REPORT_COLTITLE_1',546,'音譯，翻譯');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_COLTITLE','SETTING_SELECT_REPORT_COLTITLE_2',546,'翻譯，音譯');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_COLTITLE','SETTING_SELECT_REPORT_COLTITLE_3',546,'翻譯');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_DIRECTION','SETTING_SELECT_REPORT_DIRECTION_0',546,'左到右');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_DIRECTION','SETTING_SELECT_REPORT_DIRECTION_1',546,'右到左');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_HIGHLIGHT_ROW','SETTING_SELECT_REPORT_HIGHLIGHT_ROW_0',546,'沒有');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_HIGHLIGHT_ROW','SETTING_SELECT_REPORT_HIGHLIGHT_ROW_1',546,'星期五');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_HIGHLIGHT_ROW','SETTING_SELECT_REPORT_HIGHLIGHT_ROW_2',546,'星期六');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_HIGHLIGHT_ROW','SETTING_SELECT_REPORT_HIGHLIGHT_ROW_3',546,'星期日');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_HIGHLIGHT_ROW','SETTING_SELECT_REPORT_HIGHLIGHT_ROW_4',546,'10天組');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_0',546,'沒有');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_1',546,'10 分鐘');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_2',546,'15 分鐘');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_3',546,'20 分鐘');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_4',546,'25 分鐘');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_5',546,'30 分鐘');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_6',546,'下一個小時');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_7',546,'下一個小時 + 15 分鐘');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_8',546,'下一個小時 + 30 分鐘');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_0',546,'沒有');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_1',546,'10 分鐘');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_2',546,'15 分鐘');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_3',546,'20 分鐘');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_4',546,'25 分鐘');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_5',546,'30 分鐘');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_6',546,'下一個小時');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_7',546,'下一個小時 + 15 分鐘');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_8',546,'下一個小時 + 30 分鐘');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_0',546,'沒有');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_1',546,'10 分鐘');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_2',546,'15 分鐘');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_3',546,'20 分鐘');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_4',546,'25 分鐘');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_5',546,'30 分鐘');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_6',546,'下一個小時');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_7',546,'下一個小時 + 15 分鐘');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_8',546,'下一個小時 + 30 分鐘');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_0',546,'沒有');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_1',546,'10 分鐘');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_2',546,'15 分鐘');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_3',546,'20 分鐘');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_4',546,'25 分鐘');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_5',546,'30 分鐘');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_6',546,'下一個小時');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_7',546,'下一個小時 + 15 分鐘');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_8',546,'下一個小時 + 30 分鐘');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_0',546,'沒有');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_1',546,'10 分鐘');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_2',546,'15 分鐘');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_3',546,'20 分鐘');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_4',546,'25 分鐘');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_5',546,'30 分鐘');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_6',546,'下一個小時');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_7',546,'下一個小時 + 15 分鐘');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_8',546,'下一個小時 + 30 分鐘');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_LOCALE_SECOND','SETTING_SELECT_REPORT_LOCALE_SECOND_0',546,'沒有');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_SHOW_FAST_START_END','SETTING_SELECT_REPORT_SHOW_FAST_START_END_0',546,'沒有');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_SHOW_FAST_START_END','SETTING_SELECT_REPORT_SHOW_FAST_START_END_1',546,'Fajr & Mahgrib');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_SHOW_FAST_START_END','SETTING_SELECT_REPORT_SHOW_FAST_START_END_2',546,'Imsak & Mahgrib');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_SHOW_FAST_START_END','SETTING_SELECT_REPORT_SHOW_FAST_START_END_3',546,'Fajr & Isha');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_REPORT_SHOW_FAST_START_END','SETTING_SELECT_REPORT_SHOW_FAST_START_END_4',546,'Imsak & Isha');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_TIMEFORMAT','SETTING_SELECT_TIMEFORMAT_0',546,'12小時無後綴');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_TIMEFORMAT','SETTING_SELECT_TIMEFORMAT_1',546,'24小時');
INSERT INTO app_portfolio.app_object_subitem_translation (app_object_item_subitem_app_object_item_app_id, app_object_item_subitem_app_object_item_object_name, app_object_item_subitem_app_object_item_object_item_name, app_object_item_subitem_subitem_name, language_id, text) VALUES (2,'APP','SETTING_SELECT_TIMEFORMAT','SETTING_SELECT_TIMEFORMAT_2',546,'12小時帶後綴');
--
-- app_object_translation
--
INSERT INTO app_portfolio.app_object_translation (app_object_app_id, app_object_object_name, language_id, text) VALUES (2,'APP_DESCRIPTION',546,'漸進式 Web 應用 （PWA） 單頁應用程式 （SPA）');
INSERT INTO app_portfolio.app_object_translation (app_object_app_id, app_object_object_name, language_id, text) VALUES (3,'APP_DESCRIPTION',546,'用於顯示數據模型的簡單應用程式以及如何在應用程式平臺中集成應用程式');
--
-- message_translation
--
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (546,'20100','用戶名 5 - 100 個字符');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (546,'20101','無效的用戶名');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (546,'20102','簡歷最多 100 個字符');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (546,'20103','電子郵件最多 100 個字符');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (546,'20104','提醒最多 100 個字符');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (546,'20105','無效的電子郵件');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (546,'20106','密碼 10 - 100 個字符');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (546,'20107','需要用戶名、密碼和電子郵件');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (546,'20200','電子郵件已存在');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (546,'20201','Provider 已存在');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (546,'20203','用戶名已存在');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (546,'20204','值太長');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (546,'20300','未找到用戶名或密碼');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (546,'20301','密碼不一樣');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (546,'20302','您不能刪除最後一個用戶設置');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (546,'20303','請輸入用戶名');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (546,'20304','請輸入密碼');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (546,'20305','未找到用戶');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (546,'20306','代碼無效');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (546,'20307','不允許的文件類型');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (546,'20308','文件過大');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (546,'20309','文本無效');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (546,'20310','文本太長');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (546,'20400','記錄不存在');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (546,'20401','無效的密碼');
INSERT INTO app_portfolio.message_translation (language_id, message_code, text) VALUES (546,'20500','缺少緯度或經度');
--
-- regional_setting_translation
--
INSERT INTO app_portfolio.regional_setting_translation (regional_setting_id, language_id, text) VALUES (490,546,'格里高利安');
INSERT INTO app_portfolio.regional_setting_translation (regional_setting_id, language_id, text) VALUES (491,546,'Hijri');
INSERT INTO app_portfolio.regional_setting_translation (regional_setting_id, language_id, text) VALUES (481,546,'音譯');
INSERT INTO app_portfolio.regional_setting_translation (regional_setting_id, language_id, text) VALUES (482,546,'音譯，翻譯');
INSERT INTO app_portfolio.regional_setting_translation (regional_setting_id, language_id, text) VALUES (483,546,'翻譯，音譯');
INSERT INTO app_portfolio.regional_setting_translation (regional_setting_id, language_id, text) VALUES (484,546,'翻譯');
INSERT INTO app_portfolio.regional_setting_translation (regional_setting_id, language_id, text) VALUES (479,546,'左到右');
INSERT INTO app_portfolio.regional_setting_translation (regional_setting_id, language_id, text) VALUES (480,546,'右到左');