--Oracle, uncomment:
--SET DEFINE OFF;
--
-- app_category_translation
--
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(1, 546, '商');
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(2, 546, '通信');
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(3, 546, '教育');
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(4, 546, '金融');
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(5, 546, '房子和家');
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(6, 546, '生產力');
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(7, 546, '購物');
INSERT INTO app_portfolio.app_category_translation(app_category_id, language_id, text) VALUES(8, 546, '遊戲');
--
-- app_object_item_translation
--
INSERT INTO app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (0,'DIALOGUE','USERNAME',546,'用戶名');
INSERT INTO app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (0,'DIALOGUE','PASSWORD',546,'密碼');
INSERT INTO app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (0,'DIALOGUE','BIO',546,'傳');
INSERT INTO app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (0,'DIALOGUE','EMAIL',546,'電子郵件');
INSERT INTO app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (0,'DIALOGUE','NEW_EMAIL',546,'新電子郵件');
INSERT INTO app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (0,'DIALOGUE','PASSWORD_CONFIRM',546,'確認密碼');
INSERT INTO app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (0,'DIALOGUE','PASSWORD_REMINDER',546,'密碼提醒');
INSERT INTO app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (0,'DIALOGUE','NEW_PASSWORD_CONFIRM',546,'新的確認密碼');
INSERT INTO app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (0,'DIALOGUE','NEW_PASSWORD',546,'新密碼');
INSERT INTO app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (0,'DIALOGUE','CONFIRM_QUESTION',546,'你確定嗎？');

INSERT INTO app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (1,'REPORT','COLTITLE_ASR',546,'下午');
INSERT INTO app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (1,'REPORT','COLTITLE_ASR_IQAMAT',546,'Iqamat');
INSERT INTO app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (1,'REPORT','COLTITLE_CALTYPE_GREGORIAN',546,'格里高利安');
INSERT INTO app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (1,'REPORT','COLTITLE_CALTYPE_HIJRI',546,'Hijri');
INSERT INTO app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (1,'REPORT','COLTITLE_DAY',546,'天');
INSERT INTO app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (1,'REPORT','COLTITLE_DHUHR',546,'中午');
INSERT INTO app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (1,'REPORT','COLTITLE_DHUHR_IQAMAT',546,'Iqamat');
INSERT INTO app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (1,'REPORT','COLTITLE_FAJR',546,'黎明');
INSERT INTO app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (1,'REPORT','COLTITLE_FAJR_IQAMAT',546,'Iqamat');
INSERT INTO app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (1,'REPORT','COLTITLE_IMSAK',546,'Imsak');
INSERT INTO app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (1,'REPORT','COLTITLE_ISHA',546,'晚');
INSERT INTO app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (1,'REPORT','COLTITLE_ISHA_IQAMAT',546,'Iqamat');
INSERT INTO app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (1,'REPORT','COLTITLE_MAGHRIB',546,'日落');
INSERT INTO app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (1,'REPORT','COLTITLE_MAGHRIB_IQAMAT',546,'Iqamat');
INSERT INTO app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (1,'REPORT','COLTITLE_MIDNIGHT',546,'午夜');
INSERT INTO app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (1,'REPORT','COLTITLE_NOTES',546,'筆記');
INSERT INTO app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (1,'REPORT','COLTITLE_SUNRISE',546,'日出');
INSERT INTO app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (1,'REPORT','COLTITLE_SUNSET',546,'日落');
INSERT INTO app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (1,'REPORT','COLTITLE_TRANSLITERATION_ASR',546,'Asr');
INSERT INTO app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (1,'REPORT','COLTITLE_TRANSLITERATION_ASR_IQAMAT',546,'Iqamat');
INSERT INTO app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (1,'REPORT','COLTITLE_TRANSLITERATION_DHUHR',546,'Dhuhr');
INSERT INTO app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (1,'REPORT','COLTITLE_TRANSLITERATION_DHUHR_IQAMAT',546,'Iqamat');
INSERT INTO app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (1,'REPORT','COLTITLE_TRANSLITERATION_FAJR',546,'Fajr');
INSERT INTO app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (1,'REPORT','COLTITLE_TRANSLITERATION_FAJR_IQAMAT',546,'Iqamat');
INSERT INTO app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (1,'REPORT','COLTITLE_TRANSLITERATION_IMSAK',546,'Imsak');
INSERT INTO app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (1,'REPORT','COLTITLE_TRANSLITERATION_ISHA',546,'Isha');
INSERT INTO app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (1,'REPORT','COLTITLE_TRANSLITERATION_ISHA_IQAMAT',546,'Iqamat');
INSERT INTO app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (1,'REPORT','COLTITLE_TRANSLITERATION_MAGHRIB',546,'Maghrib');
INSERT INTO app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (1,'REPORT','COLTITLE_TRANSLITERATION_MAGHRIB_IQAMAT',546,'Iqamat');
INSERT INTO app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (1,'REPORT','COLTITLE_TRANSLITERATION_MIDNIGHT',546,'Midnight');
INSERT INTO app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (1,'REPORT','COLTITLE_TRANSLITERATION_SUNRISE',546,'Shorook');
INSERT INTO app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (1,'REPORT','COLTITLE_TRANSLITERATION_SUNSET',546,'Sunset');
INSERT INTO app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (1,'REPORT','COLTITLE_WEEKDAY',546,'平日');
INSERT INTO app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (1,'REPORT','TIMETABLE_TITLE',546,'時間表');

INSERT INTO app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (1,'TOOLBAR','TOOLBAR_BTN_DAY_LABEL',546,'天');
INSERT INTO app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (1,'TOOLBAR','TOOLBAR_BTN_MONTH_LABEL',546,'月');
INSERT INTO app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (1,'TOOLBAR','TOOLBAR_BTN_PRINT_LABEL',546,'打印');
INSERT INTO app_object_item_translation (app_id, object_name, object_item_name, language_id, text) VALUES (1,'TOOLBAR','TOOLBAR_BTN_YEAR_LABEL',546,'年');
--
-- app_object_subitem_translation
--
INSERT INTO app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (1,'SETTING_NAV_PRAYER','SETTING_SELECT_ASR','SETTING_SELECT_ASR_0',546,'標準');
INSERT INTO app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (1,'SETTING_NAV_PRAYER','SETTING_SELECT_ASR','SETTING_SELECT_ASR_1',546,'Hanafi');
INSERT INTO app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (1,'SETTING_NAV_REGIONAL','SETTING_SELECT_CALENDARTYPE','SETTING_SELECT_CALENDARTYPE_0',546,'格里高利安');
INSERT INTO app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (1,'SETTING_NAV_REGIONAL','SETTING_SELECT_CALENDARTYPE','SETTING_SELECT_CALENDARTYPE_1',546,'Hijri');
INSERT INTO app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (1,'SETTING_NAV_PRAYER','SETTING_SELECT_HIGHLATITUDE','SETTING_SELECT_HIGHLATITUDE_0',546,'午夜');
INSERT INTO app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (1,'SETTING_NAV_PRAYER','SETTING_SELECT_HIGHLATITUDE','SETTING_SELECT_HIGHLATITUDE_1',546,'角度/夜間60度（推薦）');
INSERT INTO app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (1,'SETTING_NAV_PRAYER','SETTING_SELECT_HIGHLATITUDE','SETTING_SELECT_HIGHLATITUDE_2',546,'晚上1/7');
INSERT INTO app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (1,'SETTING_NAV_PRAYER','SETTING_SELECT_HIGHLATITUDE','SETTING_SELECT_HIGHLATITUDE_3',546,'沒有調整');
INSERT INTO app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (1,'SETTING_NAV_REGIONAL','SETTING_SELECT_REPORT_COLTITLE','SETTING_SELECT_REPORT_COLTITLE_0',546,'音譯');
INSERT INTO app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (1,'SETTING_NAV_REGIONAL','SETTING_SELECT_REPORT_COLTITLE','SETTING_SELECT_REPORT_COLTITLE_1',546,'音譯，翻譯');
INSERT INTO app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (1,'SETTING_NAV_REGIONAL','SETTING_SELECT_REPORT_COLTITLE','SETTING_SELECT_REPORT_COLTITLE_2',546,'翻譯，音譯');
INSERT INTO app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (1,'SETTING_NAV_REGIONAL','SETTING_SELECT_REPORT_COLTITLE','SETTING_SELECT_REPORT_COLTITLE_3',546,'翻譯');
INSERT INTO app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (1,'SETTING_NAV_REGIONAL','SETTING_SELECT_REPORT_DIRECTION','SETTING_SELECT_REPORT_DIRECTION_0',546,'左到右');
INSERT INTO app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (1,'SETTING_NAV_REGIONAL','SETTING_SELECT_REPORT_DIRECTION','SETTING_SELECT_REPORT_DIRECTION_1',546,'右到左');
INSERT INTO app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (1,'SETTING_NAV_DESIGN','SETTING_SELECT_REPORT_HIGHLIGHT_ROW','SETTING_SELECT_REPORT_HIGHLIGHT_ROW_0',546,'沒有');
INSERT INTO app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (1,'SETTING_NAV_DESIGN','SETTING_SELECT_REPORT_HIGHLIGHT_ROW','SETTING_SELECT_REPORT_HIGHLIGHT_ROW_1',546,'星期五');
INSERT INTO app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (1,'SETTING_NAV_DESIGN','SETTING_SELECT_REPORT_HIGHLIGHT_ROW','SETTING_SELECT_REPORT_HIGHLIGHT_ROW_2',546,'星期六');
INSERT INTO app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (1,'SETTING_NAV_DESIGN','SETTING_SELECT_REPORT_HIGHLIGHT_ROW','SETTING_SELECT_REPORT_HIGHLIGHT_ROW_3',546,'星期日');
INSERT INTO app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (1,'SETTING_NAV_DESIGN','SETTING_SELECT_REPORT_HIGHLIGHT_ROW','SETTING_SELECT_REPORT_HIGHLIGHT_ROW_4',546,'10天組');
INSERT INTO app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (1,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_0',546,'沒有');
INSERT INTO app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (1,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_1',546,'10 分鐘');
INSERT INTO app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (1,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_2',546,'15 分鐘');
INSERT INTO app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (1,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_3',546,'20 分鐘');
INSERT INTO app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (1,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_4',546,'25 分鐘');
INSERT INTO app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (1,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_5',546,'30 分鐘');
INSERT INTO app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (1,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_6',546,'下一個小時');
INSERT INTO app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (1,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_7',546,'下一個小時 + 15 分鐘');
INSERT INTO app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (1,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR','SETTING_SELECT_REPORT_IQAMAT_TITLE_ASR_8',546,'下一個小時 + 30 分鐘');
INSERT INTO app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (1,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_0',546,'沒有');
INSERT INTO app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (1,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_1',546,'10 分鐘');
INSERT INTO app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (1,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_2',546,'15 分鐘');
INSERT INTO app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (1,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_3',546,'20 分鐘');
INSERT INTO app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (1,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_4',546,'25 分鐘');
INSERT INTO app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (1,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_5',546,'30 分鐘');
INSERT INTO app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (1,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_6',546,'下一個小時');
INSERT INTO app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (1,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_7',546,'下一個小時 + 15 分鐘');
INSERT INTO app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (1,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR','SETTING_SELECT_REPORT_IQAMAT_TITLE_DHUHR_8',546,'下一個小時 + 30 分鐘');
INSERT INTO app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (1,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_0',546,'沒有');
INSERT INTO app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (1,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_1',546,'10 分鐘');
INSERT INTO app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (1,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_2',546,'15 分鐘');
INSERT INTO app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (1,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_3',546,'20 分鐘');
INSERT INTO app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (1,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_4',546,'25 分鐘');
INSERT INTO app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (1,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_5',546,'30 分鐘');
INSERT INTO app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (1,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_6',546,'下一個小時');
INSERT INTO app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (1,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_7',546,'下一個小時 + 15 分鐘');
INSERT INTO app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (1,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR','SETTING_SELECT_REPORT_IQAMAT_TITLE_FAJR_8',546,'下一個小時 + 30 分鐘');
INSERT INTO app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (1,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_0',546,'沒有');
INSERT INTO app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (1,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_1',546,'10 分鐘');
INSERT INTO app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (1,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_2',546,'15 分鐘');
INSERT INTO app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (1,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_3',546,'20 分鐘');
INSERT INTO app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (1,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_4',546,'25 分鐘');
INSERT INTO app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (1,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_5',546,'30 分鐘');
INSERT INTO app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (1,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_6',546,'下一個小時');
INSERT INTO app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (1,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_7',546,'下一個小時 + 15 分鐘');
INSERT INTO app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (1,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA','SETTING_SELECT_REPORT_IQAMAT_TITLE_ISHA_8',546,'下一個小時 + 30 分鐘');
INSERT INTO app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (1,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_0',546,'沒有');
INSERT INTO app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (1,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_1',546,'10 分鐘');
INSERT INTO app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (1,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_2',546,'15 分鐘');
INSERT INTO app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (1,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_3',546,'20 分鐘');
INSERT INTO app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (1,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_4',546,'25 分鐘');
INSERT INTO app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (1,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_5',546,'30 分鐘');
INSERT INTO app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (1,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_6',546,'下一個小時');
INSERT INTO app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (1,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_7',546,'下一個小時 + 15 分鐘');
INSERT INTO app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (1,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB','SETTING_SELECT_REPORT_IQAMAT_TITLE_MAGHRIB_8',546,'下一個小時 + 30 分鐘');
INSERT INTO app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (1,'SETTING_NAV_REGIONAL','SETTING_SELECT_REPORT_LOCALE_SECOND','SETTING_SELECT_REPORT_LOCALE_SECOND_0',546,'沒有');
INSERT INTO app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (1,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_SHOW_FAST_START_END','SETTING_SELECT_REPORT_SHOW_FAST_START_END_0',546,'沒有');
INSERT INTO app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (1,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_SHOW_FAST_START_END','SETTING_SELECT_REPORT_SHOW_FAST_START_END_1',546,'Fajr & Mahgrib');
INSERT INTO app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (1,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_SHOW_FAST_START_END','SETTING_SELECT_REPORT_SHOW_FAST_START_END_2',546,'Imsak & Mahgrib');
INSERT INTO app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (1,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_SHOW_FAST_START_END','SETTING_SELECT_REPORT_SHOW_FAST_START_END_3',546,'Fajr & Isha');
INSERT INTO app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (1,'SETTING_NAV_PRAYER','SETTING_SELECT_REPORT_SHOW_FAST_START_END','SETTING_SELECT_REPORT_SHOW_FAST_START_END_4',546,'Imsak & Isha');
INSERT INTO app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (1,'SETTING_NAV_PRAYER','SETTING_SELECT_TIMEFORMAT','SETTING_SELECT_TIMEFORMAT_0',546,'12小時無後綴');
INSERT INTO app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (1,'SETTING_NAV_PRAYER','SETTING_SELECT_TIMEFORMAT','SETTING_SELECT_TIMEFORMAT_1',546,'24小時');
INSERT INTO app_object_subitem_translation (app_id, object_name, object_item_name, subitem_name, language_id, text) VALUES (1,'SETTING_NAV_PRAYER','SETTING_SELECT_TIMEFORMAT','SETTING_SELECT_TIMEFORMAT_2',546,'12小時帶後綴');
--
-- app_object_translation
--
INSERT INTO app_object_translation (app_id, object_name, language_id, text) VALUES (1,'APP_DESCRIPTION',546,'漸進式 Web 應用 （PWA） 單頁應用程式 （SPA）');
INSERT INTO app_object_translation (app_id, object_name, language_id, text) VALUES (2,'APP_DESCRIPTION',546,'用於顯示數據模型的簡單應用程式以及如何在應用程式平臺中集成應用程式');
--
-- language_translation
--
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (1,546,'阿布哈茲文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (2,546,'亞齊文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (3,546,'阿僑利文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (4,546,'阿當莫文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (5,546,'阿迪各文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (6,546,'阿法文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (7,546,'阿弗里希利文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (8,546,'南非荷蘭文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (9,546,'亞罕文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (10,546,'阿伊努文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (11,546,'阿坎文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (12,546,'阿卡德文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (13,546,'阿庫色文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (14,546,'阿拉巴馬文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (15,546,'阿爾巴尼亞文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (16,546,'阿留申文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (17,546,'阿爾及利亞阿拉伯文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (19,546,'美國手語');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (20,546,'阿姆哈拉文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (21,546,'古埃及文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (22,546,'古希臘文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (23,546,'昂加文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (24,546,'阿沃那加文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (25,546,'阿拉伯文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (26,546,'阿拉貢文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (27,546,'阿拉米文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (28,546,'阿拉奧納文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (29,546,'阿拉帕霍文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (30,546,'阿拉瓦克文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (31,546,'亞美尼亞文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (32,546,'羅馬尼亞語系');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (33,546,'法蘭克-普羅旺斯文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (34,546,'阿薩姆文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (35,546,'阿斯圖里亞文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (36,546,'阿蘇文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (37,546,'阿燦文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (40,546,'阿瓦爾文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (41,546,'阿緯斯陀文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (42,546,'阿瓦文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (43,546,'艾馬拉文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (44,546,'亞塞拜然文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (45,546,'巴達加文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (46,546,'巴菲亞文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (47,546,'富特文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (48,546,'巴赫蒂亞里文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (49,546,'峇里文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (50,546,'俾路支文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (51,546,'班巴拉文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (52,546,'巴姆穆文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (53,546,'班亞爾文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (54,546,'巴薩文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (55,546,'巴什客爾文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (56,546,'巴斯克文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (57,546,'巴塔克托巴文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (58,546,'巴伐利亞文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (59,546,'貝扎文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (60,546,'白俄羅斯文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (61,546,'別姆巴文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (62,546,'貝納文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (63,546,'孟加拉文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (64,546,'貝塔維文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (65,546,'博傑普爾文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (66,546,'比科爾文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (67,546,'比尼文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (68,546,'比什奴普萊利亞文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (69,546,'比斯拉馬文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (70,546,'比林文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (71,546,'布列斯符號');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (72,546,'博多文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (73,546,'波士尼亞文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (74,546,'布拉維文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (75,546,'布拉杰文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (77,546,'布列塔尼文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (79,546,'布吉斯文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (80,546,'保加利亞文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (81,546,'布魯文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (82,546,'布里阿特文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (83,546,'緬甸文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (84,546,'卡多文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (85,546,'卡真法文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (88,546,'粵語');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (89,546,'卡皮茲文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (90,546,'加勒比文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (91,546,'加泰羅尼亞文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (92,546,'卡尤加文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (93,546,'宿霧文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (94,546,'塔馬齊格特文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (95,546,'中部杜順文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (96,546,'索拉尼庫爾德文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (97,546,'中尤皮克文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (98,546,'阿拉伯文（查德）');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (99,546,'查加文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (100,546,'查莫洛文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (101,546,'車臣文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (102,546,'柴羅基文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (103,546,'沙伊安文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (104,546,'奇布查文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (105,546,'奇加文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (106,546,'欽博拉索海蘭蓋丘亞文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (107,546,'中文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (108,546,'契奴克文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (109,546,'奇佩瓦揚文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (110,546,'喬克托文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (111,546,'宗教斯拉夫文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (112,546,'處奇斯文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (113,546,'楚瓦什文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (114,546,'古尼瓦爾文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (115,546,'古敘利亞文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (116,546,'科隆文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (117,546,'葛摩文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (118,546,'史瓦希里文（剛果）');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (119,546,'科普特文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (120,546,'康瓦耳文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (121,546,'科西嘉文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (122,546,'克裡文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (123,546,'克里克文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (124,546,'克里米亞半島的土耳其文；克里米亞半島的塔塔爾文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (125,546,'克羅埃西亞文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (126,546,'捷克文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (127,546,'達科他文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (128,546,'丹麥文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (129,546,'達爾格瓦文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (130,546,'達薩文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (131,546,'德拉瓦文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (132,546,'丁卡文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (133,546,'迪維西文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (134,546,'多格來文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (135,546,'多格里布文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (136,546,'杜亞拉文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (137,546,'荷蘭文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (138,546,'迪尤拉文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (139,546,'宗卡文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (140,546,'東弗里西亞文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (141,546,'埃菲克文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (142,546,'埃及阿拉伯文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (143,546,'艾卡朱克文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (144,546,'埃蘭文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (145,546,'恩布文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (146,546,'埃米利安文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (147,546,'英文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (148,546,'厄爾茲亞文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (149,546,'世界文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (150,546,'愛沙尼亞文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (153,546,'埃維文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (154,546,'依汪都文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (155,546,'埃斯特雷馬杜拉文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (156,546,'芳族文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (157,546,'芳蒂文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (158,546,'法羅文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (159,546,'斐濟印地文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (160,546,'斐濟文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (161,546,'菲律賓文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (162,546,'芬蘭文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (164,546,'豐文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (165,546,'弗拉弗拉文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (166,546,'法文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (167,546,'弗留利文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (168,546,'富拉文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (169,546,'加族文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (170,546,'加告茲文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (171,546,'加利西亞文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (172,546,'贛語');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (173,546,'干達文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (174,546,'加約文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (175,546,'葛巴亞文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (176,546,'吉茲文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (177,546,'喬治亞文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (178,546,'德文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (179,546,'蓋格阿爾巴尼亞文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (180,546,'戈馬拉文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (181,546,'吉拉基文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (182,546,'吉爾伯特群島文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (183,546,'孔卡尼文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (184,546,'岡德文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (185,546,'科隆達羅文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (186,546,'哥德文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (187,546,'格列博文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (188,546,'希臘文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (189,546,'瓜拉尼文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (190,546,'古吉拉特文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (191,546,'古西文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (192,546,'圭契文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (193,546,'海達文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (194,546,'海地文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (195,546,'客家話');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (196,546,'豪撒文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (197,546,'夏威夷文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (198,546,'希伯來文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (199,546,'赫雷羅文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (200,546,'希利蓋農文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (201,546,'北印度文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (202,546,'西里莫圖土文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (203,546,'赫梯文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (204,546,'孟文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (205,546,'匈牙利文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (206,546,'胡帕文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (207,546,'伊班文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (208,546,'伊比比奧文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (209,546,'冰島文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (210,546,'伊多文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (211,546,'伊布文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (212,546,'伊洛闊文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (213,546,'伊納裡薩米文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (214,546,'印尼文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (215,546,'英格裏亞文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (216,546,'印古什文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (217,546,'國際文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (218,546,'國際文（E）');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (219,546,'因紐特文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (220,546,'依奴皮維克文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (221,546,'愛爾蘭文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (222,546,'義大利文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (223,546,'牙買加克裏奧爾英文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (224,546,'日文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (225,546,'爪哇文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (226,546,'卡捷文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (227,546,'朱拉文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (228,546,'猶太阿拉伯文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (229,546,'猶太教-波斯文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (230,546,'日德蘭文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (231,546,'卡巴爾達文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (232,546,'卡布威爾第文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (233,546,'卡比爾文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (234,546,'卡琴文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (235,546,'坎剛文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (236,546,'卡庫文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (237,546,'格陵蘭文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (238,546,'卡倫金文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (239,546,'卡爾梅克文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (240,546,'卡姆巴文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (241,546,'卡念布文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (242,546,'坎那達文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (243,546,'卡努裡文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (244,546,'卡拉卡爾帕克文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (245,546,'卡拉柴-包爾卡爾文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (246,546,'卡累利阿文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (247,546,'喀什米爾文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (248,546,'卡舒布文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (249,546,'卡威文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (250,546,'哈薩克文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (251,546,'肯揚文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (252,546,'卡西文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (253,546,'高棉文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (254,546,'和闐文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (255,546,'科瓦文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (256,546,'吉庫尤文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (257,546,'金邦杜文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (258,546,'基那來阿文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (259,546,'盧安達文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (260,546,'北紮紮其文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (261,546,'克林貢文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (262,546,'康姆文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (263,546,'科米文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (264,546,'科米-彼爾米亞克文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (265,546,'剛果文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (266,546,'貢根文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (267,546,'韓文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (268,546,'科羅文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (269,546,'科斯雷恩文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (270,546,'科塔瓦文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (271,546,'西桑海文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (272,546,'東桑海文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (273,546,'克佩列文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (274,546,'塞拉利昂克裏奧爾文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (275,546,'廣亞馬文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (276,546,'庫密克文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (277,546,'庫爾德文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (278,546,'庫魯科文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (279,546,'庫特奈文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (280,546,'夸西奧文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (281,546,'吉爾吉斯文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (282,546,'基切文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (283,546,'拉迪諾文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (284,546,'拉亨達文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (285,546,'拉科塔文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (286,546,'蘭巴文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (287,546,'朗吉文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (288,546,'寮文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (289,546,'拉特加萊文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (290,546,'拉丁文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (292,546,'拉脫維亞文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (293,546,'拉茲文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (294,546,'列茲干文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (295,546,'利古里亞文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (296,546,'林堡文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (297,546,'林加拉文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (298,546,'新共同語言');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (299,546,'文言文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (300,546,'立陶宛文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (301,546,'利伏尼亞文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (302,546,'邏輯文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (303,546,'倫巴底文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (304,546,'低地德文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (305,546,'下西利西亞文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (306,546,'下索布文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (307,546,'洛齊文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (308,546,'魯巴加丹加文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (309,546,'魯巴魯魯亞文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (310,546,'路易塞諾文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (311,546,'魯勒薩米文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (312,546,'盧恩達文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (313,546,'盧奧文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (314,546,'盧森堡文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (315,546,'盧雅文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (316,546,'馬巴文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (317,546,'馬其頓文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (318,546,'馬恰美文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (319,546,'馬都拉文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (320,546,'馬法文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (321,546,'馬加伊文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (322,546,'美茵-法蘭克尼亞文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (323,546,'邁蒂利文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (324,546,'望加錫文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (325,546,'馬夸文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (326,546,'馬孔德文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (327,546,'馬拉加什文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (328,546,'馬來文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (329,546,'馬來亞拉姆文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (330,546,'馬爾他文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (331,546,'滿族文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (332,546,'曼達文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (333,546,'曼丁哥文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (334,546,'曼尼普裡文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (335,546,'曼島文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (336,546,'毛利文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (337,546,'馬普切文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (338,546,'馬拉地文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (339,546,'馬里文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (340,546,'馬紹爾文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (341,546,'馬爾尼裡文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (342,546,'馬賽文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (343,546,'瑪詹德拉尼文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (344,546,'梅敦巴文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (345,546,'門德文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (346,546,'明打威文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (347,546,'梅魯文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (348,546,'美塔文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (350,546,'米克馬克文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (351,546,'中古荷蘭文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (352,546,'中古英文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (353,546,'中古法文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (354,546,'中古高地德文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (355,546,'中古愛爾蘭文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (356,546,'閩南語');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (357,546,'米南卡堡文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (358,546,'明格列爾文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (359,546,'米蘭德斯文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (360,546,'盧晒文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (362,546,'莫霍克文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (363,546,'莫克沙文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (365,546,'芒戈文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (366,546,'蒙古文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (367,546,'克里奧文（模里西斯）');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (368,546,'摩洛哥阿拉伯文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (369,546,'莫西文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (370,546,'多種語言');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (371,546,'蒙當文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (372,546,'穆斯林塔特文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (373,546,'姆耶內文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (374,546,'納馬文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (375,546,'諾魯文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (376,546,'納瓦霍文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (377,546,'恩東加文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (378,546,'拿波里文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (379,546,'尼泊爾文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (380,546,'尼瓦爾文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (381,546,'甘拜文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (382,546,'恩甘澎文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (383,546,'恩格姆巴文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (384,546,'奈恩加圖文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (385,546,'尼亞斯文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (386,546,'紐埃文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (387,546,'無語言內容');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (388,546,'諾蓋文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (389,546,'北地畢列文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (390,546,'北弗里西亞文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (391,546,'北方薩米文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (392,546,'北索托文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (393,546,'挪威文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (394,546,'巴克摩挪威文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (395,546,'耐諾斯克挪威文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (396,546,'諾維亞文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (397,546,'努埃爾文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (398,546,'尼揚韋齊文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (399,546,'尼揚賈文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (400,546,'尼揚科萊文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (401,546,'東加文（尼亞薩）');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (402,546,'尼奧囉文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (403,546,'尼茲馬文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (404,546,'曼德文字 (N’Ko)');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (405,546,'奧克西坦文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (406,546,'奧杰布瓦文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (407,546,'古英文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (408,546,'古法文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (409,546,'古高地日耳曼文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (410,546,'古愛爾蘭文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (411,546,'古諾爾斯文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (412,546,'古波斯文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (413,546,'古普羅旺斯文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (414,546,'歐利亞文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (415,546,'奧羅莫文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (416,546,'歐塞奇文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (417,546,'奧塞提文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (418,546,'鄂圖曼土耳其文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (419,546,'巴列維文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (420,546,'普法爾茨德文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (421,546,'帛琉文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (422,546,'巴利文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (423,546,'潘帕嘉文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (424,546,'潘加辛文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (425,546,'帕皮阿門托文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (426,546,'普什圖文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (427,546,'賓夕法尼亞德文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (428,546,'波斯文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (429,546,'腓尼基文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (430,546,'庇卡底文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (431,546,'皮埃蒙特文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (432,546,'門諾低地德文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (433,546,'波那貝文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (434,546,'波蘭文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (435,546,'旁狄希臘文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (436,546,'葡萄牙文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (437,546,'普魯士文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (438,546,'旁遮普文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (439,546,'蓋楚瓦文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (440,546,'拉賈斯坦諸文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (441,546,'復活島文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (442,546,'拉羅通加文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (443,546,'里菲亞諾文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (444,546,'羅馬格諾里文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (445,546,'羅馬尼亞文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (446,546,'羅曼斯文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (447,546,'吉普賽文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (448,546,'蘭博文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (449,546,'根語言');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (450,546,'羅圖馬島文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (451,546,'羅維阿納文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (452,546,'隆迪文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (453,546,'俄文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (454,546,'盧森尼亞文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (455,546,'羅瓦文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (456,546,'薩霍文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (457,546,'雅庫特文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (458,546,'薩瑪利亞阿拉姆文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (459,546,'薩布魯文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (460,546,'薩摩亞文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (461,546,'薩莫吉希亞文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (462,546,'桑達韋文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (463,546,'桑戈文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (464,546,'桑古文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (465,546,'梵文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (466,546,'散塔利文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (467,546,'撒丁文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (468,546,'撒撒克文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (469,546,'薩丁尼亞-薩薩里文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (470,546,'沙特菲士蘭文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (471,546,'索拉什特拉文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (472,546,'蘇格蘭文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (473,546,'蘇格蘭蓋爾文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (474,546,'塞拉亞文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (475,546,'瑟爾卡普文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (476,546,'賽納文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (477,546,'塞訥卡文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (478,546,'塞爾維亞文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (479,546,'塞爾維亞克羅埃西亞文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (480,546,'塞雷爾文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (481,546,'瑟里文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (482,546,'尚巴拉文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (483,546,'撣文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (484,546,'塞內加爾文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (485,546,'四川彝文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (486,546,'西西里文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (487,546,'希達摩文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (488,546,'錫克錫卡文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (489,546,'西利西亞文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (491,546,'信德文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (492,546,'僧伽羅文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (493,546,'斯科特薩米文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (494,546,'斯拉夫');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (495,546,'斯洛伐克文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (496,546,'斯洛維尼亞文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (497,546,'索加文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (498,546,'索格底亞納文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (499,546,'索馬利文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (500,546,'索尼基文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (501,546,'南亞塞拜然文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (502,546,'南地畢列文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (503,546,'南阿爾泰文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (504,546,'南薩米文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (505,546,'塞索托文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (506,546,'西班牙文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (507,546,'蘇拉南東墎文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (508,546,'標準摩洛哥塔馬塞特文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (509,546,'蘇庫馬文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (510,546,'蘇美文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (511,546,'巽他文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (512,546,'蘇蘇文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (513,546,'史瓦希里文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (514,546,'斯瓦特文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (515,546,'瑞典文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (517,546,'德文（瑞士）');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (519,546,'敘利亞文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (520,546,'希爾哈文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (521,546,'塔加路族文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (522,546,'大溪地文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (523,546,'台塔文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (524,546,'塔吉克文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (525,546,'塔里什文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (526,546,'塔馬奇克文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (527,546,'坦米爾文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (528,546,'太魯閣文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (529,546,'北桑海文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (530,546,'韃靼文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (531,546,'泰盧固文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (532,546,'泰雷諾文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (533,546,'特索文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (534,546,'泰頓文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (535,546,'泰文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (536,546,'藏文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (537,546,'蒂格雷文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (538,546,'提格利尼亞文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (539,546,'提姆文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (540,546,'提夫文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (541,546,'特林基特文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (542,546,'托比辛文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (543,546,'托克勞文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (544,546,'東加文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (545,546,'托爾訥芬蘭文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (547,546,'查庫爾文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (548,546,'特薩克尼恩文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (549,546,'欽西安文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (550,546,'特松加文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (551,546,'突尼西亞文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (552,546,'圖盧文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (553,546,'圖姆布卡文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (554,546,'突尼斯阿拉伯文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (555,546,'土耳其文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (556,546,'土庫曼文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (557,546,'圖羅尤文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (558,546,'吐瓦魯文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (559,546,'土凡文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (560,546,'特威文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (561,546,'卡塔布文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (562,546,'沃蒂艾克文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (563,546,'烏加列文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (564,546,'烏克蘭文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (565,546,'姆本杜文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (566,546,'未知語言');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (567,546,'上索布文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (568,546,'烏都文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (569,546,'維吾爾文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (570,546,'烏茲別克文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (571,546,'瓦伊文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (572,546,'溫達文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (573,546,'威尼斯文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (574,546,'維普森文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (575,546,'越南文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (576,546,'沃拉普克文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (577,546,'佛羅文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (578,546,'沃提克文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (579,546,'溫舊文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (580,546,'瓦隆文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (581,546,'瓦瑟文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (582,546,'瓦瑞文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (583,546,'Warlpiri');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (584,546,'瓦紹文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (585,546,'瓦尤文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (586,546,'威爾斯文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (587,546,'西佛蘭德文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (588,546,'西弗里西亞文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (589,546,'西馬裏文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (590,546,'瓦拉莫文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (591,546,'沃洛夫文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (592,546,'吳語');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (593,546,'科薩文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (594,546,'湘語');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (595,546,'洋卞文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (596,546,'瑤文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (597,546,'雅浦文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (598,546,'耶姆巴文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (599,546,'意第緒文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (600,546,'約魯巴文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (601,546,'薩波特克文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (602,546,'扎爾馬文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (603,546,'扎扎文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (604,546,'西蘭文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (605,546,'澤納加文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (606,546,'壯文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (607,546,'索羅亞斯德教達里文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (608,546,'祖魯文');
INSERT INTO language_translation (language_id, language_translation_id, text) VALUES (609,546,'祖尼文');
--
-- message_translation
--
INSERT INTO message_translation (language_id, message_code, text) VALUES (546,'20100','用戶名 5 - 100 個字符');
INSERT INTO message_translation (language_id, message_code, text) VALUES (546,'20101','無效的用戶名');
INSERT INTO message_translation (language_id, message_code, text) VALUES (546,'20102','簡歷最多 100 個字符');
INSERT INTO message_translation (language_id, message_code, text) VALUES (546,'20103','電子郵件最多 100 個字符');
INSERT INTO message_translation (language_id, message_code, text) VALUES (546,'20104','提醒最多 100 個字符');
INSERT INTO message_translation (language_id, message_code, text) VALUES (546,'20105','無效的電子郵件');
INSERT INTO message_translation (language_id, message_code, text) VALUES (546,'20106','密碼 10 - 100 個字符');
INSERT INTO message_translation (language_id, message_code, text) VALUES (546,'20107','需要用戶名、密碼和電子郵件');
INSERT INTO message_translation (language_id, message_code, text) VALUES (546,'20200','電子郵件已存在');
INSERT INTO message_translation (language_id, message_code, text) VALUES (546,'20201','Provider 已存在');
INSERT INTO message_translation (language_id, message_code, text) VALUES (546,'20203','用戶名已存在');
INSERT INTO message_translation (language_id, message_code, text) VALUES (546,'20204','值太長');
INSERT INTO message_translation (language_id, message_code, text) VALUES (546,'20300','未找到用戶名或密碼');
INSERT INTO message_translation (language_id, message_code, text) VALUES (546,'20301','密碼不一樣');
INSERT INTO message_translation (language_id, message_code, text) VALUES (546,'20302','您不能刪除最後一個用戶設置');
INSERT INTO message_translation (language_id, message_code, text) VALUES (546,'20303','請輸入用戶名');
INSERT INTO message_translation (language_id, message_code, text) VALUES (546,'20304','請輸入密碼');
INSERT INTO message_translation (language_id, message_code, text) VALUES (546,'20305','未找到用戶');
INSERT INTO message_translation (language_id, message_code, text) VALUES (546,'20306','代碼無效');
INSERT INTO message_translation (language_id, message_code, text) VALUES (546,'20307','不允許的文件類型');
INSERT INTO message_translation (language_id, message_code, text) VALUES (546,'20308','文件過大');
INSERT INTO message_translation (language_id, message_code, text) VALUES (546,'20309','文本無效');
INSERT INTO message_translation (language_id, message_code, text) VALUES (546,'20310','文本太長');
INSERT INTO message_translation (language_id, message_code, text) VALUES (546,'20400','記錄不存在');
INSERT INTO message_translation (language_id, message_code, text) VALUES (546,'20401','無效的密碼');
INSERT INTO message_translation (language_id, message_code, text) VALUES (546,'20500','缺少緯度或經度');
--
-- regional_setting_translation
--
INSERT INTO app_portfolio.regional_setting_translation (regional_setting_id, language_id, text) VALUES (490,546,'格里高利安');
INSERT INTO app_portfolio.regional_setting_translation (regional_setting_id, language_id, text) VALUES (491,546,'Hijri');
INSERT INTO app_portfolio.regional_setting_translation (regional_setting_id, language_id, text) VALUES (481,546,'音譯');
INSERT INTO app_portfolio.regional_setting_translation (regional_setting_id, language_id, text) VALUES (482,546,'音譯，翻譯');
INSERT INTO app_portfolio.regional_setting_translation (regional_setting_id, language_id, text) VALUES (483,546,'翻譯，音譯');
INSERT INTO app_portfolio.regional_setting_translation (regional_setting_id, language_id, text) VALUES (484,546,'翻譯');
INSERT INTO app_portfolio.regional_setting_translation (regional_setting_id, language_id, text) VALUES (479,546,'左到右');
INSERT INTO app_portfolio.regional_setting_translation (regional_setting_id, language_id, text) VALUES (480,546,'右到左');