--
-- app_translation app_setting
--
INSERT INTO <DB_SCHEMA/>.app_translation (app_setting_id, language_id, text) VALUES ((SELECT id FROM <DB_SCHEMA/>.app_setting WHERE app_setting_type_app_setting_type_name = 'HIGHLIGHT_ROW' and app_setting_type_app_id = <APP_ID/> AND value='0'),166,'Aucune');
INSERT INTO <DB_SCHEMA/>.app_translation (app_setting_id, language_id, text) VALUES ((SELECT id FROM <DB_SCHEMA/>.app_setting WHERE app_setting_type_app_setting_type_name = 'HIGHLIGHT_ROW' and app_setting_type_app_id = <APP_ID/> AND value='1'),166,'Vendredi');
INSERT INTO <DB_SCHEMA/>.app_translation (app_setting_id, language_id, text) VALUES ((SELECT id FROM <DB_SCHEMA/>.app_setting WHERE app_setting_type_app_setting_type_name = 'HIGHLIGHT_ROW' and app_setting_type_app_id = <APP_ID/> AND value='2'),166,'Samedi');
INSERT INTO <DB_SCHEMA/>.app_translation (app_setting_id, language_id, text) VALUES ((SELECT id FROM <DB_SCHEMA/>.app_setting WHERE app_setting_type_app_setting_type_name = 'HIGHLIGHT_ROW' and app_setting_type_app_id = <APP_ID/> AND value='3'),166,'Dimanche');
INSERT INTO <DB_SCHEMA/>.app_translation (app_setting_id, language_id, text) VALUES ((SELECT id FROM <DB_SCHEMA/>.app_setting WHERE app_setting_type_app_setting_type_name = 'HIGHLIGHT_ROW' and app_setting_type_app_id = <APP_ID/> AND value='4'),166,'Groupes de 10 jours');
INSERT INTO <DB_SCHEMA/>.app_translation (app_setting_id, language_id, text) VALUES ((SELECT id FROM <DB_SCHEMA/>.app_setting WHERE app_setting_type_app_setting_type_name = 'METHOD_ASR' and app_setting_type_app_id = <APP_ID/> AND value='Standard'),166,'Standard');
INSERT INTO <DB_SCHEMA/>.app_translation (app_setting_id, language_id, text) VALUES ((SELECT id FROM <DB_SCHEMA/>.app_setting WHERE app_setting_type_app_setting_type_name = 'METHOD_ASR' and app_setting_type_app_id = <APP_ID/> AND value='Hanafi'),166,'Hanafi');
INSERT INTO <DB_SCHEMA/>.app_translation (app_setting_id, language_id, text) VALUES ((SELECT id FROM <DB_SCHEMA/>.app_setting WHERE app_setting_type_app_setting_type_name = 'HIGH_LATITUDE_ADJUSTMENT' and app_setting_type_app_id = <APP_ID/> AND value='NightMiddle'),166,'Milieu de la nuit');
INSERT INTO <DB_SCHEMA/>.app_translation (app_setting_id, language_id, text) VALUES ((SELECT id FROM <DB_SCHEMA/>.app_setting WHERE app_setting_type_app_setting_type_name = 'HIGH_LATITUDE_ADJUSTMENT' and app_setting_type_app_id = <APP_ID/> AND value='AngleBased'),166,'Angle/60ème de nuit (recommandé)');
INSERT INTO <DB_SCHEMA/>.app_translation (app_setting_id, language_id, text) VALUES ((SELECT id FROM <DB_SCHEMA/>.app_setting WHERE app_setting_type_app_setting_type_name = 'HIGH_LATITUDE_ADJUSTMENT' and app_setting_type_app_id = <APP_ID/> AND value='OneSeventh'),166,'1/7ème de nuit');
INSERT INTO <DB_SCHEMA/>.app_translation (app_setting_id, language_id, text) VALUES ((SELECT id FROM <DB_SCHEMA/>.app_setting WHERE app_setting_type_app_setting_type_name = 'HIGH_LATITUDE_ADJUSTMENT' and app_setting_type_app_id = <APP_ID/> AND value='None'),166,'Aucun ajustement');
INSERT INTO <DB_SCHEMA/>.app_translation (app_setting_id, language_id, text) VALUES ((SELECT id FROM <DB_SCHEMA/>.app_setting WHERE app_setting_type_app_setting_type_name = 'TIMEFORMAT' and app_setting_type_app_id = <APP_ID/> AND value='12hNS'),166,'12-heures sans suffixe');
INSERT INTO <DB_SCHEMA/>.app_translation (app_setting_id, language_id, text) VALUES ((SELECT id FROM <DB_SCHEMA/>.app_setting WHERE app_setting_type_app_setting_type_name = 'TIMEFORMAT' and app_setting_type_app_id = <APP_ID/> AND value='24h'),166,'24-heures');
INSERT INTO <DB_SCHEMA/>.app_translation (app_setting_id, language_id, text) VALUES ((SELECT id FROM <DB_SCHEMA/>.app_setting WHERE app_setting_type_app_setting_type_name = 'TIMEFORMAT' and app_setting_type_app_id = <APP_ID/> AND value='12h'),166,'12-heures avec suffixe');
INSERT INTO <DB_SCHEMA/>.app_translation (app_setting_id, language_id, text) VALUES ((SELECT id FROM <DB_SCHEMA/>.app_setting WHERE app_setting_type_app_setting_type_name = 'IQAMAT' and app_setting_type_app_id = <APP_ID/> AND value='0'),166,'Aucune');
INSERT INTO <DB_SCHEMA/>.app_translation (app_setting_id, language_id, text) VALUES ((SELECT id FROM <DB_SCHEMA/>.app_setting WHERE app_setting_type_app_setting_type_name = 'IQAMAT' and app_setting_type_app_id = <APP_ID/> AND value='1'),166,'10 minutes');
INSERT INTO <DB_SCHEMA/>.app_translation (app_setting_id, language_id, text) VALUES ((SELECT id FROM <DB_SCHEMA/>.app_setting WHERE app_setting_type_app_setting_type_name = 'IQAMAT' and app_setting_type_app_id = <APP_ID/> AND value='2'),166,'15 minutes');
INSERT INTO <DB_SCHEMA/>.app_translation (app_setting_id, language_id, text) VALUES ((SELECT id FROM <DB_SCHEMA/>.app_setting WHERE app_setting_type_app_setting_type_name = 'IQAMAT' and app_setting_type_app_id = <APP_ID/> AND value='3'),166,'20 minutes');
INSERT INTO <DB_SCHEMA/>.app_translation (app_setting_id, language_id, text) VALUES ((SELECT id FROM <DB_SCHEMA/>.app_setting WHERE app_setting_type_app_setting_type_name = 'IQAMAT' and app_setting_type_app_id = <APP_ID/> AND value='4'),166,'25 minutes');
INSERT INTO <DB_SCHEMA/>.app_translation (app_setting_id, language_id, text) VALUES ((SELECT id FROM <DB_SCHEMA/>.app_setting WHERE app_setting_type_app_setting_type_name = 'IQAMAT' and app_setting_type_app_id = <APP_ID/> AND value='5'),166,'30 minutes');
INSERT INTO <DB_SCHEMA/>.app_translation (app_setting_id, language_id, text) VALUES ((SELECT id FROM <DB_SCHEMA/>.app_setting WHERE app_setting_type_app_setting_type_name = 'IQAMAT' and app_setting_type_app_id = <APP_ID/> AND value='6'),166,'Heure suivante');
INSERT INTO <DB_SCHEMA/>.app_translation (app_setting_id, language_id, text) VALUES ((SELECT id FROM <DB_SCHEMA/>.app_setting WHERE app_setting_type_app_setting_type_name = 'IQAMAT' and app_setting_type_app_id = <APP_ID/> AND value='7'),166,'Heure suivante + 15 minutes');
INSERT INTO <DB_SCHEMA/>.app_translation (app_setting_id, language_id, text) VALUES ((SELECT id FROM <DB_SCHEMA/>.app_setting WHERE app_setting_type_app_setting_type_name = 'IQAMAT' and app_setting_type_app_id = <APP_ID/> AND value='8'),166,'Heure suivante + 30 minutes');
INSERT INTO <DB_SCHEMA/>.app_translation (app_setting_id, language_id, text) VALUES ((SELECT id FROM <DB_SCHEMA/>.app_setting WHERE app_setting_type_app_setting_type_name = 'FAST_START_END' and app_setting_type_app_id = <APP_ID/> AND value='0'),166,'Non');
INSERT INTO <DB_SCHEMA/>.app_translation (app_setting_id, language_id, text) VALUES ((SELECT id FROM <DB_SCHEMA/>.app_setting WHERE app_setting_type_app_setting_type_name = 'FAST_START_END' and app_setting_type_app_id = <APP_ID/> AND value='1'),166,'Fajr & Mahgrib');
INSERT INTO <DB_SCHEMA/>.app_translation (app_setting_id, language_id, text) VALUES ((SELECT id FROM <DB_SCHEMA/>.app_setting WHERE app_setting_type_app_setting_type_name = 'FAST_START_END' and app_setting_type_app_id = <APP_ID/> AND value='2'),166,'Imsak & Mahgrib');
INSERT INTO <DB_SCHEMA/>.app_translation (app_setting_id, language_id, text) VALUES ((SELECT id FROM <DB_SCHEMA/>.app_setting WHERE app_setting_type_app_setting_type_name = 'FAST_START_END' and app_setting_type_app_id = <APP_ID/> AND value='3'),166,'Fajr & Isha');
INSERT INTO <DB_SCHEMA/>.app_translation (app_setting_id, language_id, text) VALUES ((SELECT id FROM <DB_SCHEMA/>.app_setting WHERE app_setting_type_app_setting_type_name = 'FAST_START_END' and app_setting_type_app_id = <APP_ID/> AND value='4'),166,'Imsak & Isha');